%% AeroStabilize
% Final Split-Screen Robustness Mission
%
% LQR + Feedforward vs 3-Axis LQI + Feedforward
%
% Mission:
%   0 - 8 s   : Nominal Figure-8 tracking
%   8 - 10 s  : +5 N X gust
%   14 - 16 s : -4 N Y gust
%   t = 20 s  : Payload 1.5 kg -> 1.8 kg
%   26 - 34 s : Constant diagonal crosswind
%   34 - 40 s : Disturbance removed / recovery
%
% Main goal:
% Visually demonstrate the difference between LQR and LQI under
% transient disturbances and persistent model mismatch.

clear;
clc;
close all;

%% ============================================================
% PARAMETERS
% ============================================================

g = 9.81;

m_nominal = 1.5;
m_payload = 1.8;

L = 0.225;

Ix = 0.020;
Iy = 0.020;
Iz = 0.040;

I = diag([Ix Iy Iz]);

k_yaw = 0.02;

T_motor_min = 0.0;
T_motor_max = 7.5;

%% ============================================================
% FIGURE-8 TRAJECTORY
% ============================================================

A_traj = 2.0;
B_traj = 1.5;

omega_traj = 0.30;

z0_traj = 2.0;
C_traj = 0.50;

%% ============================================================
% MISSION EVENTS
% ============================================================

gust_x_start = 8.0;
gust_x_end   = 10.0;

gust_y_start = 14.0;
gust_y_end   = 16.0;

payload_time = 20.0;

crosswind_start = 26.0;
crosswind_end   = 34.0;

F_gust_x = [5;0;0];

F_gust_y = [0;-4;0];

F_crosswind = [2;-2;0];

%% ============================================================
% SIMULATION SETTINGS
% ============================================================

t_start = 0;
t_end   = 40;

%% ============================================================
% LINEAR MODEL
% ============================================================

A = zeros(12);

A(1,4) = 1;
A(2,5) = 1;
A(3,6) = 1;

A(4,8) = g;
A(5,7) = -g;

A(7,10) = 1;
A(8,11) = 1;
A(9,12) = 1;

B = zeros(12,4);

B(6,1) = 1/m_nominal;

B(10,2) = 1/Ix;
B(11,3) = 1/Iy;
B(12,4) = 1/Iz;

%% ============================================================
% LQR
% ============================================================

Q = diag([ ...
    20,20,30, ...
    5,5,8, ...
    40,40,10, ...
    2,2,2]);

R = diag([ ...
    1.0, ...
    0.5, ...
    0.5, ...
    0.5]);

K_lqr = lqr(A,B,Q,R);

%% ============================================================
% 3-AXIS LQI
% ============================================================

C_pos = zeros(3,12);

C_pos(1,1) = 1;
C_pos(2,2) = 1;
C_pos(3,3) = 1;

A_aug = zeros(15,15);

A_aug(1:12,1:12) = A;
A_aug(13:15,1:12) = -C_pos;

B_aug = zeros(15,4);
B_aug(1:12,:) = B;

Q_aug = diag([ ...
    20,20,30, ...
    5,5,8, ...
    40,40,10, ...
    2,2,2, ...
    20,20,25]);

K_aug = lqr(A_aug,B_aug,Q_aug,R);

Kx_lqi = K_aug(:,1:12);
Ki_lqi = K_aug(:,13:15);

%% ============================================================
% INITIAL CONDITION
% ============================================================

[xd0,yd0,zd0, ...
 vxd0,vyd0,vzd0, ...
 ax0,ay0,~] = figure8_reference( ...
    0, ...
    A_traj, ...
    B_traj, ...
    omega_traj, ...
    z0_traj, ...
    C_traj);

phi_ff_0   = -ay0/g;
theta_ff_0 =  ax0/g;

x0_lqr = zeros(12,1);

x0_lqr(1:6) = [ ...
    xd0;
    yd0;
    zd0;
    vxd0;
    vyd0;
    vzd0];

x0_lqr(7) = phi_ff_0;
x0_lqr(8) = theta_ff_0;

x0_lqi = zeros(15,1);

x0_lqi(1:12) = x0_lqr;

%% ============================================================
% SIMULATE
% ============================================================

options = odeset( ...
    'RelTol',1e-7, ...
    'AbsTol',1e-9);

ode_lqr = @(t,x) lqr_dynamics( ...
    t, ...
    x, ...
    K_lqr, ...
    m_nominal, ...
    m_payload, ...
    payload_time, ...
    g, ...
    I, ...
    L, ...
    k_yaw, ...
    T_motor_min, ...
    T_motor_max, ...
    A_traj, ...
    B_traj, ...
    omega_traj, ...
    z0_traj, ...
    C_traj, ...
    gust_x_start, ...
    gust_x_end, ...
    gust_y_start, ...
    gust_y_end, ...
    crosswind_start, ...
    crosswind_end, ...
    F_gust_x, ...
    F_gust_y, ...
    F_crosswind);

[t_lqr,X_lqr_raw] = ode45( ...
    ode_lqr, ...
    [t_start t_end], ...
    x0_lqr, ...
    options);

ode_lqi = @(t,x) lqi_dynamics( ...
    t, ...
    x, ...
    Kx_lqi, ...
    Ki_lqi, ...
    m_nominal, ...
    m_payload, ...
    payload_time, ...
    g, ...
    I, ...
    L, ...
    k_yaw, ...
    T_motor_min, ...
    T_motor_max, ...
    A_traj, ...
    B_traj, ...
    omega_traj, ...
    z0_traj, ...
    C_traj, ...
    gust_x_start, ...
    gust_x_end, ...
    gust_y_start, ...
    gust_y_end, ...
    crosswind_start, ...
    crosswind_end, ...
    F_gust_x, ...
    F_gust_y, ...
    F_crosswind);

[t_lqi,X_lqi_raw] = ode45( ...
    ode_lqi, ...
    [t_start t_end], ...
    x0_lqi, ...
    options);

%% ============================================================
% COMMON TIME VECTOR
% ============================================================

t = linspace(t_start,t_end,4001)';

X_lqr = interp1( ...
    t_lqr, ...
    X_lqr_raw, ...
    t, ...
    'linear');

X_lqi = interp1( ...
    t_lqi, ...
    X_lqi_raw, ...
    t, ...
    'linear');

%% ============================================================
% REFERENCE TRAJECTORY
% ============================================================

N = length(t);

ref = zeros(N,9);

for k = 1:N

    [ ...
        ref(k,1), ...
        ref(k,2), ...
        ref(k,3), ...
        ref(k,4), ...
        ref(k,5), ...
        ref(k,6), ...
        ref(k,7), ...
        ref(k,8), ...
        ref(k,9)] = figure8_reference( ...
        t(k), ...
        A_traj, ...
        B_traj, ...
        omega_traj, ...
        z0_traj, ...
        C_traj);

end

%% ============================================================
% ERRORS
% ============================================================

error_xyz_lqr = ...
    ref(:,1:3) - X_lqr(:,1:3);

error_xyz_lqi = ...
    ref(:,1:3) - X_lqi(:,1:3);

error_lqr = sqrt( ...
    sum(error_xyz_lqr.^2,2));

error_lqi = sqrt( ...
    sum(error_xyz_lqi.^2,2));

%% ============================================================
% RECONSTRUCT MOTOR THRUST
% ============================================================

[motor_lqr,thrust_lqr] = reconstruct_lqr( ...
    t, ...
    X_lqr, ...
    K_lqr, ...
    m_nominal, ...
    g, ...
    L, ...
    k_yaw, ...
    T_motor_min, ...
    T_motor_max, ...
    A_traj, ...
    B_traj, ...
    omega_traj, ...
    z0_traj, ...
    C_traj);

[motor_lqi,thrust_lqi] = reconstruct_lqi( ...
    t, ...
    X_lqi, ...
    Kx_lqi, ...
    Ki_lqi, ...
    m_nominal, ...
    g, ...
    L, ...
    k_yaw, ...
    T_motor_min, ...
    T_motor_max, ...
    A_traj, ...
    B_traj, ...
    omega_traj, ...
    z0_traj, ...
    C_traj);

%% ============================================================
% ANIMATION SETTINGS
% ============================================================

animation_speed = 2.5;

frame_dt = 0.05;

t_anim = t_start:frame_dt:t_end;

Xlqr_anim = interp1(t,X_lqr,t_anim);
Xlqi_anim = interp1(t,X_lqi,t_anim);

ref_anim = interp1(t,ref,t_anim);

error_lqr_anim = interp1(t,error_lqr,t_anim);
error_lqi_anim = interp1(t,error_lqi,t_anim);

error_xyz_lqr_anim = interp1( ...
    t, ...
    error_xyz_lqr, ...
    t_anim);

error_xyz_lqi_anim = interp1( ...
    t, ...
    error_xyz_lqi, ...
    t_anim);

motor_lqr_anim = interp1( ...
    t, ...
    motor_lqr, ...
    t_anim);

motor_lqi_anim = interp1( ...
    t, ...
    motor_lqi, ...
    t_anim);

thrust_lqr_anim = interp1( ...
    t, ...
    thrust_lqr, ...
    t_anim);

thrust_lqi_anim = interp1( ...
    t, ...
    thrust_lqi, ...
    t_anim);

xi_lqi_anim = interp1( ...
    t, ...
    X_lqi(:,13:15), ...
    t_anim);

%% ============================================================
% FIGURE
% ============================================================

fig = figure( ...
    'Name','AeroStabilize - LQR vs LQI Robustness Mission', ...
    'NumberTitle','off');

fig.Position = [ ...
    70, ...
    60, ...
    1450, ...
    820];

tl = tiledlayout( ...
    fig, ...
    3, ...
    4, ...
    'TileSpacing','compact', ...
    'Padding','compact');

%% ============================================================
% LQR 3D PANEL
% ============================================================

ax_lqr = nexttile(tl,[2 2]);

hold(ax_lqr,'on');
grid(ax_lqr,'on');
axis(ax_lqr,'equal');

xlabel(ax_lqr,'X [m]');
ylabel(ax_lqr,'Y [m]');
zlabel(ax_lqr,'Z [m]');

title(ax_lqr,'LQR + Feedforward');

view(ax_lqr,40,25);

plot3( ...
    ax_lqr, ...
    ref(:,1), ...
    ref(:,2), ...
    ref(:,3), ...
    '--', ...
    'LineWidth',1.2);

path_lqr = plot3( ...
    ax_lqr, ...
    NaN,NaN,NaN, ...
    'LineWidth',2);

desired_lqr = plot3( ...
    ax_lqr, ...
    NaN,NaN,NaN, ...
    'o', ...
    'MarkerSize',7, ...
    'LineWidth',1.5);

arm1_lqr = plot3(ax_lqr,NaN,NaN,NaN,'LineWidth',4);
arm2_lqr = plot3(ax_lqr,NaN,NaN,NaN,'LineWidth',4);

body_lqr = plot3( ...
    ax_lqr, ...
    NaN,NaN,NaN, ...
    'o', ...
    'MarkerSize',7, ...
    'MarkerFaceColor','auto');

rotor_lqr(1) = plot3(ax_lqr,NaN,NaN,NaN,'LineWidth',1.2);
rotor_lqr(2) = plot3(ax_lqr,NaN,NaN,NaN,'LineWidth',1.2);
rotor_lqr(3) = plot3(ax_lqr,NaN,NaN,NaN,'LineWidth',1.2);
rotor_lqr(4) = plot3(ax_lqr,NaN,NaN,NaN,'LineWidth',1.2);

wind_lqr = quiver3( ...
    ax_lqr, ...
    0,0,0, ...
    0,0,0, ...
    0, ...
    'LineWidth',3);

status_lqr = text( ...
    ax_lqr, ...
    0.02, ...
    0.98, ...
    '', ...
    'Units','normalized', ...
    'VerticalAlignment','top', ...
    'FontName','Consolas', ...
    'FontSize',9);

%% ============================================================
% LQI 3D PANEL
% ============================================================

ax_lqi = nexttile(tl,[2 2]);

hold(ax_lqi,'on');
grid(ax_lqi,'on');
axis(ax_lqi,'equal');

xlabel(ax_lqi,'X [m]');
ylabel(ax_lqi,'Y [m]');
zlabel(ax_lqi,'Z [m]');

title(ax_lqi,'3-Axis LQI + Feedforward');

view(ax_lqi,40,25);

plot3( ...
    ax_lqi, ...
    ref(:,1), ...
    ref(:,2), ...
    ref(:,3), ...
    '--', ...
    'LineWidth',1.2);

path_lqi = plot3( ...
    ax_lqi, ...
    NaN,NaN,NaN, ...
    'LineWidth',2);

desired_lqi = plot3( ...
    ax_lqi, ...
    NaN,NaN,NaN, ...
    'o', ...
    'MarkerSize',7, ...
    'LineWidth',1.5);

arm1_lqi = plot3(ax_lqi,NaN,NaN,NaN,'LineWidth',4);
arm2_lqi = plot3(ax_lqi,NaN,NaN,NaN,'LineWidth',4);

body_lqi = plot3( ...
    ax_lqi, ...
    NaN,NaN,NaN, ...
    'o', ...
    'MarkerSize',7, ...
    'MarkerFaceColor','auto');

rotor_lqi(1) = plot3(ax_lqi,NaN,NaN,NaN,'LineWidth',1.2);
rotor_lqi(2) = plot3(ax_lqi,NaN,NaN,NaN,'LineWidth',1.2);
rotor_lqi(3) = plot3(ax_lqi,NaN,NaN,NaN,'LineWidth',1.2);
rotor_lqi(4) = plot3(ax_lqi,NaN,NaN,NaN,'LineWidth',1.2);

wind_lqi = quiver3( ...
    ax_lqi, ...
    0,0,0, ...
    0,0,0, ...
    0, ...
    'LineWidth',3);

status_lqi = text( ...
    ax_lqi, ...
    0.02, ...
    0.98, ...
    '', ...
    'Units','normalized', ...
    'VerticalAlignment','top', ...
    'FontName','Consolas', ...
    'FontSize',9);

%% ============================================================
% AXIS LIMITS
% ============================================================

xmin = min(ref(:,1))-1.5;
xmax = max(ref(:,1))+1.5;

ymin = min(ref(:,2))-1.5;
ymax = max(ref(:,2))+1.5;

zmin = 0.5;
zmax = max(ref(:,3))+1.2;

xlim(ax_lqr,[xmin xmax]);
ylim(ax_lqr,[ymin ymax]);
zlim(ax_lqr,[zmin zmax]);

xlim(ax_lqi,[xmin xmax]);
ylim(ax_lqi,[ymin ymax]);
zlim(ax_lqi,[zmin zmax]);

%% ============================================================
% TRACKING ERROR PANEL
% ============================================================

ax_error = nexttile(tl,[1 2]);

hold(ax_error,'on');
grid(ax_error,'on');

plot( ...
    ax_error, ...
    t, ...
    error_lqr, ...
    'LineWidth',1.3);

plot( ...
    ax_error, ...
    t, ...
    error_lqi, ...
    'LineWidth',1.5);

error_marker_lqr = plot( ...
    ax_error, ...
    NaN,NaN, ...
    'o', ...
    'MarkerSize',6, ...
    'MarkerFaceColor','auto');

error_marker_lqi = plot( ...
    ax_error, ...
    NaN,NaN, ...
    'o', ...
    'MarkerSize',6, ...
    'MarkerFaceColor','auto');

xline(ax_error,gust_x_start,'--');
xline(ax_error,gust_y_start,'--');
xline(ax_error,payload_time,'--');
xline(ax_error,crosswind_start,'--');
xline(ax_error,crosswind_end,'--');

xlabel(ax_error,'Time [s]');
ylabel(ax_error,'3D Error [m]');

title(ax_error,'Tracking Error');

legend( ...
    ax_error, ...
    'LQR', ...
    'LQI', ...
    'Location','best');

xlim(ax_error,[t_start t_end]);

%% ============================================================
% MOTOR THRUST PANEL
% ============================================================

ax_motor = nexttile(tl,[1 2]);

hold(ax_motor,'on');
grid(ax_motor,'on');

motor_x = [ ...
    1,2,3,4, ...
    6,7,8,9];

motor_values = zeros(1,8);

motor_bar = bar( ...
    ax_motor, ...
    motor_x, ...
    motor_values);

yline( ...
    ax_motor, ...
    T_motor_max, ...
    '--', ...
    'Limit');

xticks( ...
    ax_motor, ...
    motor_x);

xticklabels( ...
    ax_motor, ...
    { ...
    'L1','L2','L3','L4', ...
    'Q1','Q2','Q3','Q4'});

ylabel(ax_motor,'Motor Thrust [N]');

title(ax_motor,'Motor Thrust | L = LQR, Q = LQI');

ylim(ax_motor,[0 T_motor_max+0.5]);

%% ============================================================
% DRONE GEOMETRY
% ============================================================

arm_visual = 0.28;
rotor_radius = 0.08;

rotor_angle = linspace(0,2*pi,30);

rotor_centers_body = [ ...
     arm_visual, 0, 0;
     0, arm_visual, 0;
    -arm_visual, 0, 0;
     0,-arm_visual, 0]';

arm_x_body = [ ...
    -arm_visual,arm_visual;
    0,0;
    0,0];

arm_y_body = [ ...
    0,0;
    -arm_visual,arm_visual;
    0,0];

%% ============================================================
% ANIMATION
% ============================================================

for k = 1:length(t_anim)

    if ~isgraphics(fig)
        break;
    end

    tk = t_anim(k);

    %% --------------------------------------------------------
    % Mission event
    % ---------------------------------------------------------

    [ ...
        event_name, ...
        F_current, ...
        mass_current] = mission_status( ...
        tk, ...
        m_nominal, ...
        m_payload, ...
        payload_time, ...
        gust_x_start, ...
        gust_x_end, ...
        gust_y_start, ...
        gust_y_end, ...
        crosswind_start, ...
        crosswind_end, ...
        F_gust_x, ...
        F_gust_y, ...
        F_crosswind);

    sgtitle( ...
        tl, ...
        sprintf( ...
        'AeroStabilize Robustness Mission | %s', ...
        event_name), ...
        'FontWeight','bold');

    %% --------------------------------------------------------
    % LQR
    % ---------------------------------------------------------

    state_lqr = Xlqr_anim(k,:)';

    update_drone( ...
        state_lqr, ...
        Xlqr_anim, ...
        k, ...
        ref_anim(k,:), ...
        F_current, ...
        path_lqr, ...
        desired_lqr, ...
        arm1_lqr, ...
        arm2_lqr, ...
        body_lqr, ...
        rotor_lqr, ...
        wind_lqr, ...
        arm_x_body, ...
        arm_y_body, ...
        rotor_centers_body, ...
        rotor_radius, ...
        rotor_angle);

    %% --------------------------------------------------------
    % LQI
    % ---------------------------------------------------------

    state_lqi = Xlqi_anim(k,1:12)';

    update_drone( ...
        state_lqi, ...
        Xlqi_anim(:,1:12), ...
        k, ...
        ref_anim(k,:), ...
        F_current, ...
        path_lqi, ...
        desired_lqi, ...
        arm1_lqi, ...
        arm2_lqi, ...
        body_lqi, ...
        rotor_lqi, ...
        wind_lqi, ...
        arm_x_body, ...
        arm_y_body, ...
        rotor_centers_body, ...
        rotor_radius, ...
        rotor_angle);

    %% --------------------------------------------------------
    % Status LQR
    % ---------------------------------------------------------

    status_string_lqr = sprintf([ ...
        'Time:      %5.1f s\n' ...
        '3D error:  %6.3f m\n' ...
        'Z error:   %6.3f m\n' ...
        'Mass:      %4.2f kg\n' ...
        'Thrust:    %6.2f N\n' ...
        'Roll:      %6.2f deg\n' ...
        'Pitch:     %6.2f deg'], ...
        tk, ...
        error_lqr_anim(k), ...
        error_xyz_lqr_anim(k,3), ...
        mass_current, ...
        thrust_lqr_anim(k), ...
        rad2deg(state_lqr(7)), ...
        rad2deg(state_lqr(8)));

    if isgraphics(status_lqr)

        set( ...
            status_lqr, ...
            'String',status_string_lqr);

    end

    %% --------------------------------------------------------
    % Status LQI
    % ---------------------------------------------------------

    status_string_lqi = sprintf([ ...
        'Time:      %5.1f s\n' ...
        '3D error:  %6.3f m\n' ...
        'Z error:   %6.3f m\n' ...
        'Mass:      %4.2f kg\n' ...
        'Thrust:    %6.2f N\n' ...
        'xi_x:      %6.3f\n' ...
        'xi_y:      %6.3f\n' ...
        'xi_z:      %6.3f'], ...
        tk, ...
        error_lqi_anim(k), ...
        error_xyz_lqi_anim(k,3), ...
        mass_current, ...
        thrust_lqi_anim(k), ...
        xi_lqi_anim(k,1), ...
        xi_lqi_anim(k,2), ...
        xi_lqi_anim(k,3));

    if isgraphics(status_lqi)

        set( ...
            status_lqi, ...
            'String',status_string_lqi);

    end

    %% --------------------------------------------------------
    % Error markers
    % ---------------------------------------------------------

    if isgraphics(error_marker_lqr)

        set( ...
            error_marker_lqr, ...
            'XData',tk, ...
            'YData',error_lqr_anim(k));

    end

    if isgraphics(error_marker_lqi)

        set( ...
            error_marker_lqi, ...
            'XData',tk, ...
            'YData',error_lqi_anim(k));

    end

    %% --------------------------------------------------------
    % Motor bars
    % ---------------------------------------------------------

    if isgraphics(motor_bar)

        motor_bar.YData = [ ...
            motor_lqr_anim(k,:), ...
            motor_lqi_anim(k,:)];

    end

    drawnow limitrate;

    pause(frame_dt/animation_speed);

end

%% ============================================================
% LOCAL FUNCTION: UPDATE DRONE
% ============================================================

function update_drone( ...
    state, ...
    state_history, ...
    k, ...
    ref_current, ...
    F_current, ...
    path_handle, ...
    desired_handle, ...
    arm1_handle, ...
    arm2_handle, ...
    body_handle, ...
    rotor_handles, ...
    wind_handle, ...
    arm_x_body, ...
    arm_y_body, ...
    rotor_centers_body, ...
    rotor_radius, ...
    rotor_angle)

pos = state(1:3);

phi = state(7);
theta = state(8);
psi = state(9);

Rx = [ ...
    1,0,0;
    0,cos(phi),-sin(phi);
    0,sin(phi),cos(phi)];

Ry = [ ...
    cos(theta),0,sin(theta);
    0,1,0;
    -sin(theta),0,cos(theta)];

Rz = [ ...
    cos(psi),-sin(psi),0;
    sin(psi),cos(psi),0;
    0,0,1];

Rbw = Rz*Ry*Rx;

%% Path

if isgraphics(path_handle)

    set( ...
        path_handle, ...
        'XData',state_history(1:k,1), ...
        'YData',state_history(1:k,2), ...
        'ZData',state_history(1:k,3));

end

%% Desired point

if isgraphics(desired_handle)

    set( ...
        desired_handle, ...
        'XData',ref_current(1), ...
        'YData',ref_current(2), ...
        'ZData',ref_current(3));

end

%% Arms

arm1_world = Rbw*arm_x_body + pos;

arm2_world = Rbw*arm_y_body + pos;

if isgraphics(arm1_handle)

    set( ...
        arm1_handle, ...
        'XData',arm1_world(1,:), ...
        'YData',arm1_world(2,:), ...
        'ZData',arm1_world(3,:));

end

if isgraphics(arm2_handle)

    set( ...
        arm2_handle, ...
        'XData',arm2_world(1,:), ...
        'YData',arm2_world(2,:), ...
        'ZData',arm2_world(3,:));

end

%% Body

if isgraphics(body_handle)

    set( ...
        body_handle, ...
        'XData',pos(1), ...
        'YData',pos(2), ...
        'ZData',pos(3));

end

%% Rotors

for i = 1:4

    center = ...
        Rbw*rotor_centers_body(:,i) + pos;

    rotor_body = [ ...
        rotor_radius*cos(rotor_angle);
        rotor_radius*sin(rotor_angle);
        zeros(size(rotor_angle))];

    rotor_world = ...
        Rbw*rotor_body + center;

    if isgraphics(rotor_handles(i))

        set( ...
            rotor_handles(i), ...
            'XData',rotor_world(1,:), ...
            'YData',rotor_world(2,:), ...
            'ZData',rotor_world(3,:));

    end

end

%% Wind arrow

if isgraphics(wind_handle)

    scale = 0.10;

    set( ...
        wind_handle, ...
        'XData',pos(1), ...
        'YData',pos(2), ...
        'ZData',pos(3)+0.35, ...
        'UData',F_current(1)*scale, ...
        'VData',F_current(2)*scale, ...
        'WData',F_current(3)*scale);

end

end

%% ============================================================
% LOCAL FUNCTION: MISSION STATUS
% ============================================================

function [event,F,mass] = mission_status( ...
    t, ...
    m_nominal, ...
    m_payload, ...
    payload_time, ...
    gx1, ...
    gx2, ...
    gy1, ...
    gy2, ...
    cw1, ...
    cw2, ...
    Fx, ...
    Fy, ...
    Fc)

mass = m_nominal;

if t >= payload_time
    mass = m_payload;
end

F = [0;0;0];

if t >= gx1 && t <= gx2

    F = Fx;
    event = '+5 N X GUST';

elseif t >= gy1 && t <= gy2

    F = Fy;
    event = '-4 N Y GUST';

elseif t >= cw1 && t <= cw2

    F = Fc;
    event = 'DIAGONAL CROSSWIND';

elseif t >= payload_time && t < cw1

    event = 'PAYLOAD ATTACHED: 1.5 -> 1.8 kg';

elseif t > cw2

    event = 'FINAL RECOVERY';

else

    event = 'NOMINAL FLIGHT';

end

end

%% ============================================================
% FIGURE-8 REFERENCE
% ============================================================

function [x,y,z,vx,vy,vz,ax,ay,az] = ...
    figure8_reference(t,A,B,w,z0,C)

x = A*sin(w*t);

y = B*sin(2*w*t);

z = z0 + C*sin(0.5*w*t);

vx = A*w*cos(w*t);

vy = 2*B*w*cos(2*w*t);

vz = 0.5*C*w*cos(0.5*w*t);

ax = -A*w^2*sin(w*t);

ay = -4*B*w^2*sin(2*w*t);

az = -0.25*C*w^2*sin(0.5*w*t);

end

%% ============================================================
% EXTERNAL DISTURBANCE
% ============================================================

function F = disturbance_force( ...
    t, ...
    gx1,gx2, ...
    gy1,gy2, ...
    cw1,cw2, ...
    Fx,Fy,Fc)

F = [0;0;0];

if t >= gx1 && t <= gx2
    F = F + Fx;
end

if t >= gy1 && t <= gy2
    F = F + Fy;
end

if t >= cw1 && t <= cw2
    F = F + Fc;
end

end

%% ============================================================
% ACTUAL MASS
% ============================================================

function m = actual_mass( ...
    t, ...
    m_nominal, ...
    m_payload, ...
    payload_time)

if t < payload_time

    m = m_nominal;

else

    m = m_payload;

end

end

%% ============================================================
% LQR DYNAMICS
% ============================================================

function dx = lqr_dynamics( ...
    t,state,K, ...
    m_nominal,m_payload,payload_time, ...
    g,I,L,k_yaw,Tmin,Tmax, ...
    At,Bt,wt,z0,Ct, ...
    gx1,gx2,gy1,gy2,cw1,cw2, ...
    Fx,Fy,Fc)

[xd,yd,zd,vxd,vyd,vzd,ax,ay,az] = ...
    figure8_reference(t,At,Bt,wt,z0,Ct);

phi_ff = -ay/g;
theta_ff = ax/g;

x_ref = zeros(12,1);

x_ref(1:6) = [ ...
    xd;yd;zd; ...
    vxd;vyd;vzd];

x_ref(7) = phi_ff;
x_ref(8) = theta_ff;

delta_u = -K*(state-x_ref);

u_cmd = [ ...
    m_nominal*(g+az);
    0;
    0;
    0] + delta_u;

m = actual_mass( ...
    t, ...
    m_nominal, ...
    m_payload, ...
    payload_time);

F = disturbance_force( ...
    t, ...
    gx1,gx2, ...
    gy1,gy2, ...
    cw1,cw2, ...
    Fx,Fy,Fc);

dx = plant( ...
    state, ...
    u_cmd, ...
    m, ...
    F, ...
    g,I,L,k_yaw,Tmin,Tmax);

end

%% ============================================================
% LQI DYNAMICS
% ============================================================

function dx_aug = lqi_dynamics( ...
    t,x_aug,Kx,Ki, ...
    m_nominal,m_payload,payload_time, ...
    g,I,L,k_yaw,Tmin,Tmax, ...
    At,Bt,wt,z0,Ct, ...
    gx1,gx2,gy1,gy2,cw1,cw2, ...
    Fx,Fy,Fc)

state = x_aug(1:12);

xi = x_aug(13:15);

[xd,yd,zd,vxd,vyd,vzd,ax,ay,az] = ...
    figure8_reference(t,At,Bt,wt,z0,Ct);

phi_ff = -ay/g;
theta_ff = ax/g;

x_ref = zeros(12,1);

x_ref(1:6) = [ ...
    xd;yd;zd; ...
    vxd;vyd;vzd];

x_ref(7) = phi_ff;
x_ref(8) = theta_ff;

delta_u = ...
    -Kx*(state-x_ref) - ...
    Ki*xi;

u_cmd = [ ...
    m_nominal*(g+az);
    0;
    0;
    0] + delta_u;

m = actual_mass( ...
    t, ...
    m_nominal, ...
    m_payload, ...
    payload_time);

F = disturbance_force( ...
    t, ...
    gx1,gx2, ...
    gy1,gy2, ...
    cw1,cw2, ...
    Fx,Fy,Fc);

dx = plant( ...
    state, ...
    u_cmd, ...
    m, ...
    F, ...
    g,I,L,k_yaw,Tmin,Tmax);

xi_dot = [ ...
    xd-state(1);
    yd-state(2);
    zd-state(3)];

dx_aug = [ ...
    dx;
    xi_dot];

end

%% ============================================================
% NONLINEAR PLANT
% ============================================================

function dx = plant( ...
    state,u_cmd,m,F_ext, ...
    g,I,L,k_yaw,Tmin,Tmax)

vx = state(4);
vy = state(5);
vz = state(6);

phi = state(7);
theta = state(8);
psi = state(9);

p = state(10);
q = state(11);
r = state(12);

M = [ ...
    1,1,1,1;
    0,L,0,-L;
    -L,0,L,0;
    k_yaw,-k_yaw,k_yaw,-k_yaw];

motors = M\u_cmd;

motors = min( ...
    max(motors,Tmin), ...
    Tmax);

u_actual = M*motors;

T = u_actual(1);

tau = u_actual(2:4);

Rx = [ ...
    1,0,0;
    0,cos(phi),-sin(phi);
    0,sin(phi),cos(phi)];

Ry = [ ...
    cos(theta),0,sin(theta);
    0,1,0;
    -sin(theta),0,cos(theta)];

Rz = [ ...
    cos(psi),-sin(psi),0;
    sin(psi),cos(psi),0;
    0,0,1];

Rbw = Rz*Ry*Rx;

F_thrust = Rbw*[0;0;T];

F_gravity = [0;0;-m*g];

acc = ...
    (F_thrust + ...
     F_gravity + ...
     F_ext)/m;

omega_body = [p;q;r];

omega_dot = I \ ( ...
    tau - ...
    cross(omega_body,I*omega_body));

E = [ ...
    1, ...
    sin(phi)*tan(theta), ...
    cos(phi)*tan(theta);
    0, ...
    cos(phi), ...
    -sin(phi);
    0, ...
    sin(phi)/cos(theta), ...
    cos(phi)/cos(theta)];

euler_dot = E*omega_body;

dx = zeros(12,1);

dx(1:3) = [vx;vy;vz];

dx(4:6) = acc;

dx(7:9) = euler_dot;

dx(10:12) = omega_dot;

end

%% ============================================================
% RECONSTRUCT LQR CONTROL
% ============================================================

function [motor_log,T_log] = reconstruct_lqr( ...
    t,X,K,m_nominal,g,L,k_yaw,Tmin,Tmax, ...
    At,Bt,wt,z0,Ct)

N = length(t);

motor_log = zeros(N,4);
T_log = zeros(N,1);

M = [ ...
    1,1,1,1;
    0,L,0,-L;
    -L,0,L,0;
    k_yaw,-k_yaw,k_yaw,-k_yaw];

for k = 1:N

    [xd,yd,zd,vxd,vyd,vzd,ax,ay,az] = ...
        figure8_reference( ...
        t(k), ...
        At,Bt,wt,z0,Ct);

    x_ref = zeros(12,1);

    x_ref(1:6) = [ ...
        xd;yd;zd; ...
        vxd;vyd;vzd];

    x_ref(7) = -ay/g;
    x_ref(8) = ax/g;

    state = X(k,:)';

    delta_u = -K*(state-x_ref);

    u_cmd = [ ...
        m_nominal*(g+az);
        0;
        0;
        0] + delta_u;

    motors = M\u_cmd;

    motors = min( ...
        max(motors,Tmin), ...
        Tmax);

    u_actual = M*motors;

    motor_log(k,:) = motors';

    T_log(k) = u_actual(1);

end

end

%% ============================================================
% RECONSTRUCT LQI CONTROL
% ============================================================

function [motor_log,T_log] = reconstruct_lqi( ...
    t,X,Kx,Ki,m_nominal,g,L,k_yaw,Tmin,Tmax, ...
    At,Bt,wt,z0,Ct)

N = length(t);

motor_log = zeros(N,4);
T_log = zeros(N,1);

M = [ ...
    1,1,1,1;
    0,L,0,-L;
    -L,0,L,0;
    k_yaw,-k_yaw,k_yaw,-k_yaw];

for k = 1:N

    [xd,yd,zd,vxd,vyd,vzd,ax,ay,az] = ...
        figure8_reference( ...
        t(k), ...
        At,Bt,wt,z0,Ct);

    x_ref = zeros(12,1);

    x_ref(1:6) = [ ...
        xd;yd;zd; ...
        vxd;vyd;vzd];

    x_ref(7) = -ay/g;
    x_ref(8) = ax/g;

    state = X(k,1:12)';

    xi = X(k,13:15)';

    delta_u = ...
        -Kx*(state-x_ref) - ...
        Ki*xi;

    u_cmd = [ ...
        m_nominal*(g+az);
        0;
        0;
        0] + delta_u;

    motors = M\u_cmd;

    motors = min( ...
        max(motors,Tmin), ...
        Tmax);

    u_actual = M*motors;

    motor_log(k,:) = motors';

    T_log(k) = u_actual(1);

end

end