%% AeroStabilize - PID Mass Uncertainty 3D Animation
%
% Demonstrates integral action under +20% mass uncertainty.
%
% Controller assumes:
%   m_nominal = 1.5 kg
%
% Actual nonlinear plant:
%   m_actual = 1.8 kg
%
% Animation shows:
% - Desired helix
% - Actual PID trajectory
% - 3D quadrotor
% - Live altitude error
% - Integral state
% - Total thrust
%
% The key effect:
% Integral action builds additional thrust until the
% persistent altitude error caused by the mass mismatch disappears.

clear;
clc;
close all;

addpath('../models');
addpath('../trajectories');

run('../parameters/quadcopter_params.m');

%% ============================================================
%% MASS UNCERTAINTY
%% ============================================================

m_nominal = m;

mass_increase = 0.20;

m_actual = ...
    m_nominal * (1 + mass_increase);

fprintf('Nominal mass: %.3f kg\n', m_nominal);
fprintf('Actual mass:  %.3f kg\n', m_actual);
fprintf('Mass error:   +%.1f %%\n', mass_increase*100);

%% ============================================================
%% SIMULATION SETTINGS
%% ============================================================

tspan = [0 25];

motor_thrust_min = 0.0;
motor_thrust_max = 7.5;

%% ============================================================
%% POSITION PID / ATTITUDE PD GAINS
%% ============================================================

% Horizontal position
Kp_x = 1.0;
Kd_x = 1.4;

Kp_y = 1.0;
Kd_y = 1.4;

% Altitude PID
Kp_z = 4.0;
Ki_z = 1.0;
Kd_z = 3.0;

% Attitude PD
Kp_phi = 0.8;
Kd_phi = 0.25;

Kp_theta = 0.8;
Kd_theta = 0.25;

Kp_psi = 0.5;
Kd_psi = 0.20;

psi_des = 0;

%% ============================================================
%% INITIAL STATE
%% ============================================================

% 12 vehicle states + 1 altitude integral state
x0 = zeros(13,1);

[x_start, y_start, z_start, ...
 vx_start, vy_start, vz_start] = ...
    helix_trajectory(0);

x0(1) = x_start;
x0(2) = y_start;
x0(3) = z_start;

x0(4) = vx_start;
x0(5) = vy_start;
x0(6) = vz_start;

% x0(13) = integral altitude error = 0

%% ============================================================
%% RUN SIMULATION
%% ============================================================

dynamics = @(t,x) ...
    pid_mass_closed_loop( ...
        t, x, ...
        psi_des, ...
        Kp_x, Kd_x, ...
        Kp_y, Kd_y, ...
        Kp_z, Ki_z, Kd_z, ...
        Kp_phi, Kd_phi, ...
        Kp_theta, Kd_theta, ...
        Kp_psi, Kd_psi, ...
        m_nominal, ...
        m_actual, ...
        g, I, L, k_yaw, ...
        motor_thrust_min, ...
        motor_thrust_max);

[t, x] = ode45( ...
    dynamics, ...
    tspan, ...
    x0);

%% ============================================================
%% LOG DATA
%% ============================================================

N = length(t);

ref_log = zeros(N,12);

motor_log = zeros(N,4);
motor_raw_log = zeros(N,4);

thrust_log = zeros(N,1);

for k = 1:N

    [~, ...
     ref_k, ...
     motor_k, ...
     motor_raw_k, ...
     thrust_k] = ...
        pid_mass_closed_loop( ...
            t(k), ...
            x(k,:)', ...
            psi_des, ...
            Kp_x, Kd_x, ...
            Kp_y, Kd_y, ...
            Kp_z, Ki_z, Kd_z, ...
            Kp_phi, Kd_phi, ...
            Kp_theta, Kd_theta, ...
            Kp_psi, Kd_psi, ...
            m_nominal, ...
            m_actual, ...
            g, I, L, k_yaw, ...
            motor_thrust_min, ...
            motor_thrust_max);

    ref_log(k,:) = ref_k';

    motor_log(k,:) = motor_k';

    motor_raw_log(k,:) = motor_raw_k';

    thrust_log(k) = thrust_k;

end

%% ============================================================
%% ERROR
%% ============================================================

error_x = ref_log(:,1) - x(:,1);
error_y = ref_log(:,2) - x(:,2);
error_z = ref_log(:,3) - x(:,3);

position_error = sqrt( ...
    error_x.^2 + ...
    error_y.^2 + ...
    error_z.^2);

fprintf('\n============================================\n');
fprintf('PID MASS UNCERTAINTY RESULTS\n');
fprintf('============================================\n');

fprintf( ...
    'Final altitude error: %.4f m\n', ...
    error_z(end));

fprintf( ...
    'Final 3D position error: %.4f m\n', ...
    position_error(end));

fprintf( ...
    'Final integral state: %.4f m*s\n', ...
    x(end,13));

fprintf( ...
    'Final total thrust: %.3f N\n', ...
    thrust_log(end));

fprintf( ...
    'Actual hover thrust required: %.3f N\n', ...
    m_actual*g);

%% ============================================================
%% ANIMATION INTERPOLATION
%% ============================================================

frame_dt = 0.05;

animation_speed = 1.0;

t_anim = ...
    t(1):frame_dt:t(end);

x_anim = interp1( ...
    t, ...
    x, ...
    t_anim, ...
    'linear');

ref_anim = interp1( ...
    t, ...
    ref_log, ...
    t_anim, ...
    'linear');

thrust_anim = interp1( ...
    t, ...
    thrust_log, ...
    t_anim, ...
    'linear');

position_error_anim = interp1( ...
    t, ...
    position_error, ...
    t_anim, ...
    'linear');

alt_error_anim = interp1( ...
    t, ...
    error_z, ...
    t_anim, ...
    'linear');

%% ============================================================
%% DRONE VISUAL GEOMETRY
%% ============================================================

arm_visual = 0.35;

rotor_radius = 0.10;

rotor_points = 30;

motor1_body = [ arm_visual; 0; 0];
motor2_body = [0;  arm_visual; 0];
motor3_body = [-arm_visual; 0; 0];
motor4_body = [0; -arm_visual; 0];

rotor_angle = ...
    linspace(0,2*pi,rotor_points);

rotor_circle = [ ...
    rotor_radius*cos(rotor_angle);
    rotor_radius*sin(rotor_angle);
    zeros(1,rotor_points)];

%% ============================================================
%% FIGURE
%% ============================================================

fig = figure( ...
    'Name', ...
    'AeroStabilize - PID Mass Uncertainty');

fig.Position = ...
    [100 80 1400 780];

%% ============================================================
%% 3D AXIS
%% ============================================================

ax3d = axes( ...
    'Parent',fig, ...
    'Position',[0.05 0.12 0.61 0.80]);

hold(ax3d,'on');

grid(ax3d,'on');

axis(ax3d,'equal');

xlabel(ax3d,'x [m]');
ylabel(ax3d,'y [m]');
zlabel(ax3d,'z [m]');

view(ax3d,45,25);

%% Desired helix

plot3( ...
    ax3d, ...
    ref_anim(:,1), ...
    ref_anim(:,2), ...
    ref_anim(:,3), ...
    '--', ...
    'LineWidth',1.5);

%% Full actual trajectory

plot3( ...
    ax3d, ...
    x_anim(:,1), ...
    x_anim(:,2), ...
    x_anim(:,3), ...
    ':', ...
    'LineWidth',1.0);

%% Axis limits

margin = 1.0;

xlim(ax3d,[ ...
    min(ref_anim(:,1))-margin ...
    max(ref_anim(:,1))+margin]);

ylim(ax3d,[ ...
    min(ref_anim(:,2))-margin ...
    max(ref_anim(:,2))+margin]);

zlim(ax3d,[ ...
    min([x_anim(:,3);ref_anim(:,3)])-0.5 ...
    max(ref_anim(:,3))+0.8]);

%% ============================================================
%% DRONE GRAPHICS
%% ============================================================

flight_path = plot3( ...
    ax3d, ...
    NaN,NaN,NaN, ...
    'LineWidth',2);

arm1_plot = plot3( ...
    ax3d, ...
    NaN,NaN,NaN, ...
    'LineWidth',3);

arm2_plot = plot3( ...
    ax3d, ...
    NaN,NaN,NaN, ...
    'LineWidth',3);

body_plot = plot3( ...
    ax3d, ...
    NaN,NaN,NaN, ...
    'o', ...
    'MarkerSize',9, ...
    'MarkerFaceColor','auto');

rotor1_plot = plot3(ax3d,NaN,NaN,NaN,'LineWidth',1.5);
rotor2_plot = plot3(ax3d,NaN,NaN,NaN,'LineWidth',1.5);
rotor3_plot = plot3(ax3d,NaN,NaN,NaN,'LineWidth',1.5);
rotor4_plot = plot3(ax3d,NaN,NaN,NaN,'LineWidth',1.5);

desired_point = plot3( ...
    ax3d, ...
    NaN,NaN,NaN, ...
    'x', ...
    'MarkerSize',11, ...
    'LineWidth',2);

status_text = text( ...
    ax3d, ...
    0.02, ...
    0.97, ...
    '', ...
    'Units','normalized', ...
    'VerticalAlignment','top', ...
    'FontSize',10, ...
    'FontWeight','bold');

%% ============================================================
%% ALTITUDE ERROR GRAPH
%% ============================================================

ax_error = axes( ...
    'Parent',fig, ...
    'Position',[0.72 0.66 0.24 0.23]);

hold(ax_error,'on');
grid(ax_error,'on');

plot( ...
    ax_error, ...
    t_anim, ...
    alt_error_anim, ...
    'LineWidth',1.4);

yline( ...
    ax_error, ...
    0, ...
    '--');

error_marker = plot( ...
    ax_error, ...
    NaN,NaN, ...
    'o', ...
    'MarkerSize',7, ...
    'MarkerFaceColor','auto');

xlabel(ax_error,'Time [s]');
ylabel(ax_error,'Altitude Error [m]');

title(ax_error,'Altitude Error');

xlim(ax_error,tspan);

%% ============================================================
%% INTEGRAL STATE GRAPH
%% ============================================================

ax_integral = axes( ...
    'Parent',fig, ...
    'Position',[0.72 0.38 0.24 0.23]);

hold(ax_integral,'on');
grid(ax_integral,'on');

plot( ...
    ax_integral, ...
    t_anim, ...
    x_anim(:,13), ...
    'LineWidth',1.4);

integral_marker = plot( ...
    ax_integral, ...
    NaN,NaN, ...
    'o', ...
    'MarkerSize',7, ...
    'MarkerFaceColor','auto');

xlabel(ax_integral,'Time [s]');
ylabel(ax_integral,'Integral [m*s]');

title(ax_integral,'Altitude Integral State');

xlim(ax_integral,tspan);

%% ============================================================
%% TOTAL THRUST GRAPH
%% ============================================================

ax_thrust = axes( ...
    'Parent',fig, ...
    'Position',[0.72 0.10 0.24 0.23]);

hold(ax_thrust,'on');
grid(ax_thrust,'on');

plot( ...
    ax_thrust, ...
    t_anim, ...
    thrust_anim, ...
    'LineWidth',1.4);

yline( ...
    ax_thrust, ...
    m_nominal*g, ...
    '--', ...
    'Nominal Hover');

yline( ...
    ax_thrust, ...
    m_actual*g, ...
    '--', ...
    'Actual Hover Required');

thrust_marker = plot( ...
    ax_thrust, ...
    NaN,NaN, ...
    'o', ...
    'MarkerSize',7, ...
    'MarkerFaceColor','auto');

xlabel(ax_thrust,'Time [s]');
ylabel(ax_thrust,'Total Thrust [N]');

title(ax_thrust,'PID Thrust Compensation');

xlim(ax_thrust,tspan);

%% ============================================================
%% ANIMATION LOOP
%% ============================================================

for k = 1:length(t_anim)

    current_time = ...
        t_anim(k);

    %% Vehicle state

    position = [ ...
        x_anim(k,1);
        x_anim(k,2);
        x_anim(k,3)];

    phi = ...
        x_anim(k,7);

    theta = ...
        x_anim(k,8);

    psi = ...
        x_anim(k,9);

    %% Rotation matrix

    Rx = [ ...
        1 0 0;
        0 cos(phi) -sin(phi);
        0 sin(phi) cos(phi)];

    Ry = [ ...
        cos(theta) 0 sin(theta);
        0 1 0;
        -sin(theta) 0 cos(theta)];

    Rz = [ ...
        cos(psi) -sin(psi) 0;
        sin(psi) cos(psi) 0;
        0 0 1];

    Rbw = ...
        Rz * Ry * Rx;

    %% Motor locations

    motor1_world = ...
        position + Rbw*motor1_body;

    motor2_world = ...
        position + Rbw*motor2_body;

    motor3_world = ...
        position + Rbw*motor3_body;

    motor4_world = ...
        position + Rbw*motor4_body;

    %% Arms

    set( ...
        arm1_plot, ...
        'XData',[motor1_world(1) motor3_world(1)], ...
        'YData',[motor1_world(2) motor3_world(2)], ...
        'ZData',[motor1_world(3) motor3_world(3)]);

    set( ...
        arm2_plot, ...
        'XData',[motor2_world(1) motor4_world(1)], ...
        'YData',[motor2_world(2) motor4_world(2)], ...
        'ZData',[motor2_world(3) motor4_world(3)]);

    %% Body center

    set( ...
        body_plot, ...
        'XData',position(1), ...
        'YData',position(2), ...
        'ZData',position(3));

    %% Rotor geometry

    rotor_world = ...
        Rbw * rotor_circle;

    rotor1 = ...
        rotor_world + motor1_world;

    rotor2 = ...
        rotor_world + motor2_world;

    rotor3 = ...
        rotor_world + motor3_world;

    rotor4 = ...
        rotor_world + motor4_world;

    set(rotor1_plot, ...
        'XData',rotor1(1,:), ...
        'YData',rotor1(2,:), ...
        'ZData',rotor1(3,:));

    set(rotor2_plot, ...
        'XData',rotor2(1,:), ...
        'YData',rotor2(2,:), ...
        'ZData',rotor2(3,:));

    set(rotor3_plot, ...
        'XData',rotor3(1,:), ...
        'YData',rotor3(2,:), ...
        'ZData',rotor3(3,:));

    set(rotor4_plot, ...
        'XData',rotor4(1,:), ...
        'YData',rotor4(2,:), ...
        'ZData',rotor4(3,:));

    %% Actual travelled path

    set( ...
        flight_path, ...
        'XData',x_anim(1:k,1), ...
        'YData',x_anim(1:k,2), ...
        'ZData',x_anim(1:k,3));

    %% Desired point

    set( ...
        desired_point, ...
        'XData',ref_anim(k,1), ...
        'YData',ref_anim(k,2), ...
        'ZData',ref_anim(k,3));

    %% Graph markers

    set( ...
        error_marker, ...
        'XData',current_time, ...
        'YData',alt_error_anim(k));

    set( ...
        integral_marker, ...
        'XData',current_time, ...
        'YData',x_anim(k,13));

    set( ...
        thrust_marker, ...
        'XData',current_time, ...
        'YData',thrust_anim(k));

    %% Status text

    status_string = sprintf( ...
        ['Controller: PID + Feedforward\n' ...
         'Nominal Mass: %.2f kg\n' ...
         'Actual Mass: %.2f kg\n' ...
         'Time: %.2f s\n' ...
         '3D Error: %.3f m\n' ...
         'Altitude Error: %.3f m\n' ...
         'Integral: %.3f m*s\n' ...
         'Total Thrust: %.2f N'], ...
         m_nominal, ...
         m_actual, ...
         current_time, ...
         position_error_anim(k), ...
         alt_error_anim(k), ...
         x_anim(k,13), ...
         thrust_anim(k));

    set( ...
        status_text, ...
        'String', ...
        status_string);

    %% Main title

    sgtitle( ...
        fig, ...
        sprintf( ...
            'AeroStabilize | PID Rejecting +20%% Mass Error | t = %.2f s', ...
            current_time), ...
        'FontWeight','bold');

    drawnow;

    pause( ...
        frame_dt / animation_speed);

end

%% ============================================================
%% PID CLOSED LOOP
%% ============================================================

function [ ...
    xdot_aug, ...
    x_ref, ...
    motor_thrusts_sat, ...
    motor_thrusts_raw, ...
    T] = ...
    pid_mass_closed_loop( ...
    t, x_aug, ...
    psi_des, ...
    Kp_x, Kd_x, ...
    Kp_y, Kd_y, ...
    Kp_z, Ki_z, Kd_z, ...
    Kp_phi, Kd_phi, ...
    Kp_theta, Kd_theta, ...
    Kp_psi, Kd_psi, ...
    m_nominal, ...
    m_actual, ...
    g, I, L, k_yaw, ...
    motor_thrust_min, ...
    motor_thrust_max)

%% Vehicle states

x = ...
    x_aug(1:12);

integral_z = ...
    x_aug(13);

%% Desired trajectory

[x_des, y_des, z_des, ...
 vx_des, vy_des, vz_des, ...
 ax_ff, ay_ff, az_ff] = ...
    helix_trajectory(t);

%% Reference state

x_ref = zeros(12,1);

x_ref(1) = x_des;
x_ref(2) = y_des;
x_ref(3) = z_des;

x_ref(4) = vx_des;
x_ref(5) = vy_des;
x_ref(6) = vz_des;

%% State variables

x_pos = x(1);
y_pos = x(2);
z_pos = x(3);

vx = x(4);
vy = x(5);
vz = x(6);

phi = x(7);
theta = x(8);
psi = x(9);

p = x(10);
q = x(11);
r = x(12);

%% Position errors

e_x = ...
    x_des - x_pos;

e_y = ...
    y_des - y_pos;

e_z = ...
    z_des - z_pos;

e_vx = ...
    vx_des - vx;

e_vy = ...
    vy_des - vy;

e_vz = ...
    vz_des - vz;

%% ============================================================
%% HORIZONTAL POSITION CONTROL
%% ============================================================

ax_des = ...
    ax_ff + ...
    Kp_x*e_x + ...
    Kd_x*e_vx;

ay_des = ...
    ay_ff + ...
    Kp_y*e_y + ...
    Kd_y*e_vy;

theta_des = ...
    ax_des / g;

phi_des = ...
    -ay_des / g;

max_angle = ...
    deg2rad(20);

theta_des = max( ...
    min(theta_des,max_angle), ...
    -max_angle);

phi_des = max( ...
    min(phi_des,max_angle), ...
    -max_angle);

%% ============================================================
%% ALTITUDE PID
%%
%% Controller feedforward still assumes only 1.5 kg.
%% Integral term must learn the missing thrust.
%% ============================================================

T = ...
    m_nominal*g + ...
    m_nominal*az_ff + ...
    Kp_z*e_z + ...
    Ki_z*integral_z + ...
    Kd_z*e_vz;

%% ============================================================
%% ATTITUDE PD
%% ============================================================

tau_phi = ...
    Kp_phi*(phi_des-phi) - ...
    Kd_phi*p;

tau_theta = ...
    Kp_theta*(theta_des-theta) - ...
    Kd_theta*q;

tau_psi = ...
    Kp_psi*(psi_des-psi) - ...
    Kd_psi*r;

%% ============================================================
%% MOTOR MIXER
%% ============================================================

motor_thrusts_raw = ...
    motor_mixer( ...
        T, ...
        tau_phi, ...
        tau_theta, ...
        tau_psi, ...
        L, ...
        k_yaw);

motor_thrusts_sat = ...
    max( ...
        min( ...
            motor_thrusts_raw, ...
            motor_thrust_max), ...
        motor_thrust_min);

u_actual = ...
    motor_unmixer( ...
        motor_thrusts_sat, ...
        L, ...
        k_yaw);

%% ============================================================
%% ACTUAL 1.8 kg NONLINEAR PLANT
%% ============================================================

xdot = ...
    quad_dynamics( ...
        x, ...
        u_actual, ...
        m_actual, ...
        g, ...
        I);

%% Integral state

integral_z_dot = ...
    e_z;

xdot_aug = [ ...
    xdot;
    integral_z_dot];

end