%% AeroStabilize - 3D LQR Helix Animation
% Animates the nonlinear 6-DOF quadcopter following a helix
% using LQR + trajectory feedforward.

clear;
clc;
close all;

addpath('../models');
addpath('../trajectories');

run('../parameters/quadcopter_params.m');

%% ============================================================
%% LINEARIZED MODEL FOR LQR
%% ============================================================

A = zeros(12,12);

A(1,4) = 1;
A(2,5) = 1;
A(3,6) = 1;

A(4,8) = g;
A(5,7) = -g;

A(7,10) = 1;
A(8,11) = 1;
A(9,12) = 1;

B = zeros(12,4);

B(6,1)  = 1/m;
B(10,2) = 1/I(1,1);
B(11,3) = 1/I(2,2);
B(12,4) = 1/I(3,3);

%% ============================================================
%% LQR DESIGN
%% ============================================================

Q = diag([ ...
    20, ...
    20, ...
    30, ...
    5, ...
    5, ...
    8, ...
    40, ...
    40, ...
    10, ...
    2, ...
    2, ...
    2]);

R = diag([ ...
    1.0, ...
    0.5, ...
    0.5, ...
    0.5]);

K = lqr(A,B,Q,R);

%% ============================================================
%% INITIAL STATE
%% ============================================================

x0 = zeros(12,1);

[x_start, y_start, z_start, ...
 vx_start, vy_start, vz_start] = helix_trajectory(0);

x0(1) = x_start;
x0(2) = y_start;
x0(3) = z_start;

x0(4) = vx_start;
x0(5) = vy_start;
x0(6) = vz_start;

%% ============================================================
%% SIMULATION
%% ============================================================

tspan = [0 20];

motor_thrust_min = 0.0;
motor_thrust_max = 7.5;

dynamics = @(t,x) lqr_helix_animation_closed_loop( ...
    t, x, K, ...
    m, g, I, L, k_yaw, ...
    motor_thrust_min, ...
    motor_thrust_max);

[t, x] = ode45(dynamics, tspan, x0);

%% ============================================================
%% GENERATE DESIRED TRAJECTORY
%% ============================================================

x_des_log = zeros(length(t),1);
y_des_log = zeros(length(t),1);
z_des_log = zeros(length(t),1);

for k = 1:length(t)

    [x_des, y_des, z_des] = ...
        helix_trajectory(t(k));

    x_des_log(k) = x_des;
    y_des_log(k) = y_des;
    z_des_log(k) = z_des;

end

%% ============================================================
%% ANIMATION SETTINGS
%% ============================================================

% Visual arm length
arm_visual = 0.35;

% Rotor radius for visualization
rotor_radius = 0.09;

% Number of points used to draw each rotor
rotor_points = 30;

% Animation playback speed
animation_speed = 1.0;

% Frame time used for animation
frame_dt = 0.05;

% Uniform time vector for smoother animation
t_anim = t(1):frame_dt:t(end);

% Interpolate states
x_anim = interp1( ...
    t, ...
    x, ...
    t_anim, ...
    'linear');

% Interpolate desired path
x_des_anim = interp1( ...
    t, ...
    x_des_log, ...
    t_anim, ...
    'linear');

y_des_anim = interp1( ...
    t, ...
    y_des_log, ...
    t_anim, ...
    'linear');

z_des_anim = interp1( ...
    t, ...
    z_des_log, ...
    t_anim, ...
    'linear');

%% ============================================================
%% FIGURE
%% ============================================================

figure( ...
    'Name', ...
    'AeroStabilize 3D Flight Animation');

hold on;
grid on;
axis equal;

xlabel('x [m]');
ylabel('y [m]');
zlabel('z [m]');

title('AeroStabilize - LQR + Feedforward Helix Tracking');

%% Desired trajectory

plot3( ...
    x_des_anim, ...
    y_des_anim, ...
    z_des_anim, ...
    '--', ...
    'LineWidth', ...
    1.4);

%% Actual full trajectory in faint reference form

plot3( ...
    x_anim(:,1), ...
    x_anim(:,2), ...
    x_anim(:,3), ...
    ':', ...
    'LineWidth', ...
    1.0);

%% Axis limits

margin = 0.8;

xmin = min(x_des_anim) - margin;
xmax = max(x_des_anim) + margin;

ymin = min(y_des_anim) - margin;
ymax = max(y_des_anim) + margin;

zmin = min(z_des_anim) - 0.5;
zmax = max(z_des_anim) + 0.8;

xlim([xmin xmax]);
ylim([ymin ymax]);
zlim([zmin zmax]);

view(45,25);

%% ============================================================
%% CREATE GRAPHICS OBJECTS
%% ============================================================

% Actual travelled path
flight_path = plot3( ...
    NaN, ...
    NaN, ...
    NaN, ...
    'LineWidth', ...
    1.8);

% Quad arms
arm1_plot = plot3( ...
    NaN,NaN,NaN, ...
    'LineWidth',3);

arm2_plot = plot3( ...
    NaN,NaN,NaN, ...
    'LineWidth',3);

% Body center
body_plot = plot3( ...
    NaN,NaN,NaN, ...
    'o', ...
    'MarkerSize', ...
    8, ...
    'MarkerFaceColor', ...
    'auto');

% Rotor circles
rotor1_plot = plot3( ...
    NaN,NaN,NaN, ...
    'LineWidth',1.5);

rotor2_plot = plot3( ...
    NaN,NaN,NaN, ...
    'LineWidth',1.5);

rotor3_plot = plot3( ...
    NaN,NaN,NaN, ...
    'LineWidth',1.5);

rotor4_plot = plot3( ...
    NaN,NaN,NaN, ...
    'LineWidth',1.5);

% Current desired point
desired_point = plot3( ...
    NaN,NaN,NaN, ...
    'x', ...
    'MarkerSize',10, ...
    'LineWidth',2);

legend( ...
    'Desired Trajectory', ...
    'Actual Trajectory', ...
    'Travelled Path', ...
    'Location', ...
    'best');

%% ============================================================
%% BODY FRAME GEOMETRY
%% ============================================================

% Motor positions in BODY FRAME
motor1_body = [ arm_visual; 0; 0];
motor2_body = [0;  arm_visual; 0];
motor3_body = [-arm_visual; 0; 0];
motor4_body = [0; -arm_visual; 0];

%% Rotor circle in local body xy-plane

angle_rotor = linspace( ...
    0, ...
    2*pi, ...
    rotor_points);

rotor_circle = [ ...
    rotor_radius*cos(angle_rotor);
    rotor_radius*sin(angle_rotor);
    zeros(1,rotor_points)];

%% ============================================================
%% ANIMATION LOOP
%% ============================================================

for k = 1:length(t_anim)

    %% Current state

    position = [ ...
        x_anim(k,1);
        x_anim(k,2);
        x_anim(k,3)];

    phi   = x_anim(k,7);
    theta = x_anim(k,8);
    psi   = x_anim(k,9);

    %% Rotation matrices

    Rx = [ ...
        1, 0, 0;
        0, cos(phi), -sin(phi);
        0, sin(phi), cos(phi)];

    Ry = [ ...
        cos(theta), 0, sin(theta);
        0, 1, 0;
        -sin(theta), 0, cos(theta)];

    Rz = [ ...
        cos(psi), -sin(psi), 0;
        sin(psi), cos(psi), 0;
        0, 0, 1];

    R_body_world = Rz * Ry * Rx;

    %% Motor positions in WORLD FRAME

    motor1_world = ...
        position + R_body_world*motor1_body;

    motor2_world = ...
        position + R_body_world*motor2_body;

    motor3_world = ...
        position + R_body_world*motor3_body;

    motor4_world = ...
        position + R_body_world*motor4_body;

    %% ========================================================
    %% UPDATE ARMS
    %% ========================================================

    set( ...
        arm1_plot, ...
        'XData', ...
        [motor1_world(1),motor3_world(1)], ...
        'YData', ...
        [motor1_world(2),motor3_world(2)], ...
        'ZData', ...
        [motor1_world(3),motor3_world(3)]);

    set( ...
        arm2_plot, ...
        'XData', ...
        [motor2_world(1),motor4_world(1)], ...
        'YData', ...
        [motor2_world(2),motor4_world(2)], ...
        'ZData', ...
        [motor2_world(3),motor4_world(3)]);

    %% ========================================================
    %% UPDATE BODY
    %% ========================================================

    set( ...
        body_plot, ...
        'XData',position(1), ...
        'YData',position(2), ...
        'ZData',position(3));

    %% ========================================================
    %% ROTOR ORIENTATION
    %% ========================================================

    rotor_world = ...
        R_body_world * rotor_circle;

    rotor1 = ...
        rotor_world + motor1_world;

    rotor2 = ...
        rotor_world + motor2_world;

    rotor3 = ...
        rotor_world + motor3_world;

    rotor4 = ...
        rotor_world + motor4_world;

    %% Update rotors

    set( ...
        rotor1_plot, ...
        'XData',rotor1(1,:), ...
        'YData',rotor1(2,:), ...
        'ZData',rotor1(3,:));

    set( ...
        rotor2_plot, ...
        'XData',rotor2(1,:), ...
        'YData',rotor2(2,:), ...
        'ZData',rotor2(3,:));

    set( ...
        rotor3_plot, ...
        'XData',rotor3(1,:), ...
        'YData',rotor3(2,:), ...
        'ZData',rotor3(3,:));

    set( ...
        rotor4_plot, ...
        'XData',rotor4(1,:), ...
        'YData',rotor4(2,:), ...
        'ZData',rotor4(3,:));

    %% ========================================================
    %% UPDATE ACTUAL FLIGHT PATH
    %% ========================================================

    set( ...
        flight_path, ...
        'XData',x_anim(1:k,1), ...
        'YData',x_anim(1:k,2), ...
        'ZData',x_anim(1:k,3));

    %% ========================================================
    %% DESIRED CURRENT POSITION
    %% ========================================================

    set( ...
        desired_point, ...
        'XData',x_des_anim(k), ...
        'YData',y_des_anim(k), ...
        'ZData',z_des_anim(k));

    %% ========================================================
    %% DISPLAY CURRENT TIME
    %% ========================================================

    title(sprintf( ...
        'AeroStabilize - LQR Helix Tracking | t = %.2f s', ...
        t_anim(k)));

    drawnow;

    %% Playback timing

    pause(frame_dt / animation_speed);

end

%% ============================================================
%% CLOSED LOOP
%% ============================================================

function xdot = ...
    lqr_helix_animation_closed_loop( ...
    t, x, K, ...
    m, g, I, L, k_yaw, ...
    motor_thrust_min, ...
    motor_thrust_max)

%% Desired trajectory

[x_des, y_des, z_des, ...
 vx_des, vy_des, vz_des, ...
 ax_ff, ay_ff, az_ff] = ...
    helix_trajectory(t);

%% ============================================================
%% Feedforward attitude
%% ============================================================

theta_ff = ax_ff / g;

phi_ff = -ay_ff / g;

max_ff_angle = deg2rad(15);

theta_ff = max( ...
    min(theta_ff,max_ff_angle), ...
    -max_ff_angle);

phi_ff = max( ...
    min(phi_ff,max_ff_angle), ...
    -max_ff_angle);

%% ============================================================
%% Reference state
%% ============================================================

x_ref = zeros(12,1);

x_ref(1) = x_des;
x_ref(2) = y_des;
x_ref(3) = z_des;

x_ref(4) = vx_des;
x_ref(5) = vy_des;
x_ref(6) = vz_des;

x_ref(7) = phi_ff;
x_ref(8) = theta_ff;

%% ============================================================
%% LQR feedback
%% ============================================================

e = x - x_ref;

delta_u = -K*e;

delta_T = delta_u(1);

tau_phi = delta_u(2);

tau_theta = delta_u(3);

tau_psi = delta_u(4);

%% ============================================================
%% Feedforward thrust
%% ============================================================

T_ff = m*(g + az_ff);

T = T_ff + delta_T;

%% ============================================================
%% Motor mixer
%% ============================================================

motor_thrusts_raw = motor_mixer( ...
    T, ...
    tau_phi, ...
    tau_theta, ...
    tau_psi, ...
    L, ...
    k_yaw);

motor_thrusts_sat = max( ...
    min( ...
        motor_thrusts_raw, ...
        motor_thrust_max), ...
    motor_thrust_min);

%% Actual control after motor constraints

u_actual = motor_unmixer( ...
    motor_thrusts_sat, ...
    L, ...
    k_yaw);

%% ============================================================
%% Nonlinear plant
%% ============================================================

xdot = quad_dynamics( ...
    x, ...
    u_actual, ...
    m, ...
    g, ...
    I);

end