%% AeroStabilize - PID/PD Wind Disturbance Animation
% Cascaded PD/PID-style controller + feedforward
% Nonlinear 6-DOF quadcopter
% 5 N wind disturbance in +x direction from 8 s to 9 s

clear;
clc;
close all;

addpath('../models');
addpath('../trajectories');

run('../parameters/quadcopter_params.m');

%% ============================================================
%% SETTINGS
%% ============================================================

tspan = [0 20];

motor_thrust_min = 0.0;
motor_thrust_max = 7.5;

wind_force = 5.0;
wind_start = 8.0;
wind_end   = 9.0;

%% ============================================================
%% CONTROLLER GAINS
%% ============================================================

psi_des = 0;

Kp_x = 1.0;
Kd_x = 1.4;

Kp_y = 1.0;
Kd_y = 1.4;

Kp_z = 4.0;
Kd_z = 3.0;

Kp_phi = 0.8;
Kd_phi = 0.25;

Kp_theta = 0.8;
Kd_theta = 0.25;

Kp_psi = 0.5;
Kd_psi = 0.20;

%% ============================================================
%% INITIAL STATE
%% ============================================================

x0 = zeros(12,1);

[x_start, y_start, z_start, ...
 vx_start, vy_start, vz_start] = ...
    helix_trajectory(0);

x0(1) = x_start;
x0(2) = y_start;
x0(3) = z_start;

x0(4) = vx_start;
x0(5) = vy_start;
x0(6) = vz_start;

%% ============================================================
%% SIMULATION
%% ============================================================

dynamics = @(t,x) ...
    pid_wind_closed_loop( ...
        t, x, ...
        psi_des, ...
        Kp_x, Kd_x, ...
        Kp_y, Kd_y, ...
        Kp_z, Kd_z, ...
        Kp_phi, Kd_phi, ...
        Kp_theta, Kd_theta, ...
        Kp_psi, Kd_psi, ...
        m, g, I, L, k_yaw, ...
        motor_thrust_min, ...
        motor_thrust_max, ...
        wind_force, ...
        wind_start, ...
        wind_end);

[t, x] = ode45(dynamics, tspan, x0);

%% ============================================================
%% LOG DATA
%% ============================================================

N = length(t);

ref_log = zeros(N,12);
motor_log = zeros(N,4);
motor_raw_log = zeros(N,4);

for k = 1:N

    [~, ...
     ref_k, ...
     motor_k, ...
     motor_raw_k] = ...
        pid_wind_closed_loop( ...
            t(k), ...
            x(k,:)', ...
            psi_des, ...
            Kp_x, Kd_x, ...
            Kp_y, Kd_y, ...
            Kp_z, Kd_z, ...
            Kp_phi, Kd_phi, ...
            Kp_theta, Kd_theta, ...
            Kp_psi, Kd_psi, ...
            m, g, I, L, k_yaw, ...
            motor_thrust_min, ...
            motor_thrust_max, ...
            wind_force, ...
            wind_start, ...
            wind_end);

    ref_log(k,:) = ref_k';
    motor_log(k,:) = motor_k';
    motor_raw_log(k,:) = motor_raw_k';

end

%% ============================================================
%% TRACKING ERROR
%% ============================================================

error_x = ref_log(:,1) - x(:,1);
error_y = ref_log(:,2) - x(:,2);
error_z = ref_log(:,3) - x(:,3);

position_error = sqrt( ...
    error_x.^2 + ...
    error_y.^2 + ...
    error_z.^2);

RMSE = sqrt(mean(position_error.^2));
max_error = max(position_error);

%% ============================================================
%% SATURATION
%% ============================================================

saturation_log = any( ...
    motor_raw_log > motor_thrust_max | ...
    motor_raw_log < motor_thrust_min, ...
    2);

saturation_duration = trapz( ...
    t, ...
    double(saturation_log));

saturation_percentage = ...
    100 * saturation_duration / ...
    (t(end)-t(1));

%% ============================================================
%% PRINT RESULTS
%% ============================================================

fprintf('\n============================================\n');
fprintf('PID/PD WIND ANIMATION RESULTS\n');
fprintf('============================================\n');

fprintf('RMSE: %.4f m\n', RMSE);
fprintf('Maximum Tracking Error: %.4f m\n', max_error);

fprintf('\nWind\n');
fprintf('Force: %.1f N in +x\n', wind_force);
fprintf('Start: %.1f s\n', wind_start);
fprintf('End:   %.1f s\n', wind_end);

fprintf('\nSaturation\n');
fprintf('Duration: %.3f s\n', saturation_duration);
fprintf('Time: %.2f %%\n', saturation_percentage);

%% ============================================================
%% ANIMATION SETTINGS
%% ============================================================

frame_dt = 0.04;
animation_speed = 1.0;

t_anim = t(1):frame_dt:t(end);

x_anim = interp1( ...
    t, x, t_anim, 'linear');

ref_anim = interp1( ...
    t, ref_log, t_anim, 'linear');

motor_anim = interp1( ...
    t, motor_log, t_anim, 'linear');

error_anim = interp1( ...
    t, position_error, t_anim, 'linear');

%% ============================================================
%% DRONE GEOMETRY
%% ============================================================

arm_visual = 0.35;
rotor_radius = 0.10;
rotor_points = 30;

motor1_body = [ arm_visual; 0; 0];
motor2_body = [0;  arm_visual; 0];
motor3_body = [-arm_visual; 0; 0];
motor4_body = [0; -arm_visual; 0];

rotor_angle = linspace(0,2*pi,rotor_points);

rotor_circle = [ ...
    rotor_radius*cos(rotor_angle);
    rotor_radius*sin(rotor_angle);
    zeros(1,rotor_points)];

%% ============================================================
%% FIGURE
%% ============================================================

fig = figure( ...
    'Name', ...
    'AeroStabilize - PID Wind Disturbance');

fig.Position = [100 100 1300 750];

%% ============================================================
%% MAIN 3D AXIS
%% ============================================================

ax3d = axes( ...
    'Parent',fig, ...
    'Position',[0.06 0.12 0.62 0.80]);

hold(ax3d,'on');
grid(ax3d,'on');
axis(ax3d,'equal');

xlabel(ax3d,'x [m]');
ylabel(ax3d,'y [m]');
zlabel(ax3d,'z [m]');

view(ax3d,45,25);

%% Desired trajectory

plot3( ...
    ax3d, ...
    ref_anim(:,1), ...
    ref_anim(:,2), ...
    ref_anim(:,3), ...
    '--', ...
    'LineWidth',1.5);

%% Full actual trajectory

plot3( ...
    ax3d, ...
    x_anim(:,1), ...
    x_anim(:,2), ...
    x_anim(:,3), ...
    ':', ...
    'LineWidth',1.0);

%% Limits

margin = 1.0;

xlim(ax3d,[ ...
    min(ref_anim(:,1))-margin ...
    max(ref_anim(:,1))+margin]);

ylim(ax3d,[ ...
    min(ref_anim(:,2))-margin ...
    max(ref_anim(:,2))+margin]);

zlim(ax3d,[ ...
    min(ref_anim(:,3))-0.5 ...
    max(ref_anim(:,3))+0.8]);

%% ============================================================
%% DRONE OBJECTS
%% ============================================================

flight_path = plot3( ...
    ax3d,NaN,NaN,NaN, ...
    'LineWidth',2);

arm1_plot = plot3( ...
    ax3d,NaN,NaN,NaN, ...
    'LineWidth',3);

arm2_plot = plot3( ...
    ax3d,NaN,NaN,NaN, ...
    'LineWidth',3);

body_plot = plot3( ...
    ax3d,NaN,NaN,NaN, ...
    'o', ...
    'MarkerSize',9, ...
    'MarkerFaceColor','auto');

rotor1_plot = plot3(ax3d,NaN,NaN,NaN,'LineWidth',1.5);
rotor2_plot = plot3(ax3d,NaN,NaN,NaN,'LineWidth',1.5);
rotor3_plot = plot3(ax3d,NaN,NaN,NaN,'LineWidth',1.5);
rotor4_plot = plot3(ax3d,NaN,NaN,NaN,'LineWidth',1.5);

desired_point = plot3( ...
    ax3d,NaN,NaN,NaN, ...
    'x', ...
    'MarkerSize',11, ...
    'LineWidth',2);

%% ============================================================
%% WIND VECTOR
%% ============================================================

wind_arrow = quiver3( ...
    ax3d, ...
    0,0,0, ...
    0,0,0, ...
    0, ...
    'LineWidth',3, ...
    'MaxHeadSize',1.2);

%% ============================================================
%% STATUS TEXT
%% ============================================================

status_text = text( ...
    ax3d, ...
    0.02, ...
    0.97, ...
    '', ...
    'Units','normalized', ...
    'VerticalAlignment','top', ...
    'FontSize',11, ...
    'FontWeight','bold');

%% ============================================================
%% MOTOR THRUST DISPLAY
%% ============================================================

ax_motor = axes( ...
    'Parent',fig, ...
    'Position',[0.73 0.58 0.23 0.30]);

motor_bar = bar( ...
    ax_motor, ...
    [0 0 0 0]);

ylim(ax_motor,[0 motor_thrust_max]);
xlim(ax_motor,[0.5 4.5]);

xticks(ax_motor,1:4);
xticklabels(ax_motor,{'M1','M2','M3','M4'});

ylabel(ax_motor,'Motor Thrust [N]');
title(ax_motor,'Individual Motor Thrust');

grid(ax_motor,'on');

yline( ...
    ax_motor, ...
    motor_thrust_max, ...
    '--', ...
    'Limit');

%% ============================================================
%% TRACKING ERROR DISPLAY
%% ============================================================

ax_error = axes( ...
    'Parent',fig, ...
    'Position',[0.73 0.14 0.23 0.30]);

hold(ax_error,'on');
grid(ax_error,'on');

plot( ...
    ax_error, ...
    t_anim, ...
    error_anim, ...
    'LineWidth',1.2);

error_marker = plot( ...
    ax_error, ...
    NaN,NaN, ...
    'o', ...
    'MarkerSize',7, ...
    'MarkerFaceColor','auto');

xline(ax_error,wind_start,'--');
xline(ax_error,wind_end,'--');

xlabel(ax_error,'Time [s]');
ylabel(ax_error,'Position Error [m]');

title(ax_error,'Live Tracking Error');

xlim(ax_error,[0 tspan(2)]);

%% ============================================================
%% ANIMATION LOOP
%% ============================================================

for k = 1:length(t_anim)

    current_time = t_anim(k);

    position = [ ...
        x_anim(k,1);
        x_anim(k,2);
        x_anim(k,3)];

    phi = x_anim(k,7);
    theta = x_anim(k,8);
    psi = x_anim(k,9);

    %% Rotation matrix

    Rx = [ ...
        1 0 0;
        0 cos(phi) -sin(phi);
        0 sin(phi) cos(phi)];

    Ry = [ ...
        cos(theta) 0 sin(theta);
        0 1 0;
        -sin(theta) 0 cos(theta)];

    Rz = [ ...
        cos(psi) -sin(psi) 0;
        sin(psi) cos(psi) 0;
        0 0 1];

    Rbw = Rz * Ry * Rx;

    %% Motor positions

    motor1_world = position + Rbw*motor1_body;
    motor2_world = position + Rbw*motor2_body;
    motor3_world = position + Rbw*motor3_body;
    motor4_world = position + Rbw*motor4_body;

    %% Arms

    set(arm1_plot, ...
        'XData',[motor1_world(1) motor3_world(1)], ...
        'YData',[motor1_world(2) motor3_world(2)], ...
        'ZData',[motor1_world(3) motor3_world(3)]);

    set(arm2_plot, ...
        'XData',[motor2_world(1) motor4_world(1)], ...
        'YData',[motor2_world(2) motor4_world(2)], ...
        'ZData',[motor2_world(3) motor4_world(3)]);

    %% Body

    set(body_plot, ...
        'XData',position(1), ...
        'YData',position(2), ...
        'ZData',position(3));

    %% Rotors

    rotor_world = Rbw * rotor_circle;

    rotor1 = rotor_world + motor1_world;
    rotor2 = rotor_world + motor2_world;
    rotor3 = rotor_world + motor3_world;
    rotor4 = rotor_world + motor4_world;

    set(rotor1_plot, ...
        'XData',rotor1(1,:), ...
        'YData',rotor1(2,:), ...
        'ZData',rotor1(3,:));

    set(rotor2_plot, ...
        'XData',rotor2(1,:), ...
        'YData',rotor2(2,:), ...
        'ZData',rotor2(3,:));

    set(rotor3_plot, ...
        'XData',rotor3(1,:), ...
        'YData',rotor3(2,:), ...
        'ZData',rotor3(3,:));

    set(rotor4_plot, ...
        'XData',rotor4(1,:), ...
        'YData',rotor4(2,:), ...
        'ZData',rotor4(3,:));

    %% Travelled path

    set(flight_path, ...
        'XData',x_anim(1:k,1), ...
        'YData',x_anim(1:k,2), ...
        'ZData',x_anim(1:k,3));

    %% Desired position

    set(desired_point, ...
        'XData',ref_anim(k,1), ...
        'YData',ref_anim(k,2), ...
        'ZData',ref_anim(k,3));

    %% Wind

    wind_active = ...
        current_time >= wind_start && ...
        current_time <= wind_end;

    if wind_active

        set(wind_arrow, ...
            'XData',position(1)-1.0, ...
            'YData',position(2), ...
            'ZData',position(3), ...
            'UData',1.2, ...
            'VData',0, ...
            'WData',0, ...
            'Visible','on');

        wind_status = 'ON | 5.0 N +x';

    else

        set(wind_arrow,'Visible','off');

        wind_status = 'OFF';

    end

    %% Motor thrust bars

    motor_bar.YData = motor_anim(k,:);

    %% Error marker

    set(error_marker, ...
        'XData',current_time, ...
        'YData',error_anim(k));

    %% Status text

    status_string = sprintf([ ...
        'Controller: PD + Feedforward\n' ...
        'Time: %.2f s\n' ...
        'Wind: %s\n' ...
        'Tracking Error: %.3f m\n' ...
        'Roll: %.1f deg\n' ...
        'Pitch: %.1f deg'], ...
        current_time, ...
        wind_status, ...
        error_anim(k), ...
        rad2deg(phi), ...
        rad2deg(theta));

    set(status_text, ...
        'String',status_string);

    %% Main title

    if wind_active

        sgtitle(fig, ...
            sprintf( ...
                'AeroStabilize | PD + FF | 5 N Wind Active | t = %.2f s', ...
                current_time), ...
            'FontWeight','bold');

    else

        sgtitle(fig, ...
            sprintf( ...
                'AeroStabilize | PD + Feedforward | t = %.2f s', ...
                current_time), ...
            'FontWeight','bold');

    end

    drawnow;

    pause(frame_dt / animation_speed);

end

%% ============================================================
%% CLOSED LOOP
%% ============================================================

function [ ...
    xdot, ...
    x_ref, ...
    motor_thrusts_sat, ...
    motor_thrusts_raw] = ...
    pid_wind_closed_loop( ...
    t, x, ...
    psi_des, ...
    Kp_x, Kd_x, ...
    Kp_y, Kd_y, ...
    Kp_z, Kd_z, ...
    Kp_phi, Kd_phi, ...
    Kp_theta, Kd_theta, ...
    Kp_psi, Kd_psi, ...
    m, g, I, L, k_yaw, ...
    motor_thrust_min, ...
    motor_thrust_max, ...
    wind_force, ...
    wind_start, ...
    wind_end)

%% Desired trajectory

[x_des, y_des, z_des, ...
 vx_des, vy_des, vz_des, ...
 ax_ff, ay_ff, az_ff] = ...
    helix_trajectory(t);

%% Reference

x_ref = zeros(12,1);

x_ref(1) = x_des;
x_ref(2) = y_des;
x_ref(3) = z_des;

x_ref(4) = vx_des;
x_ref(5) = vy_des;
x_ref(6) = vz_des;

%% States

x_pos = x(1);
y_pos = x(2);
z_pos = x(3);

vx = x(4);
vy = x(5);
vz = x(6);

phi = x(7);
theta = x(8);
psi = x(9);

p = x(10);
q = x(11);
r = x(12);

%% Errors

e_x = x_des - x_pos;
e_y = y_des - y_pos;
e_z = z_des - z_pos;

e_vx = vx_des - vx;
e_vy = vy_des - vy;
e_vz = vz_des - vz;

%% Position + FF

ax_des = ...
    ax_ff + ...
    Kp_x*e_x + ...
    Kd_x*e_vx;

ay_des = ...
    ay_ff + ...
    Kp_y*e_y + ...
    Kd_y*e_vy;

theta_des = ax_des/g;
phi_des = -ay_des/g;

max_angle = deg2rad(20);

theta_des = max( ...
    min(theta_des,max_angle), ...
    -max_angle);

phi_des = max( ...
    min(phi_des,max_angle), ...
    -max_angle);

%% Altitude

T = ...
    m*g + ...
    m*az_ff + ...
    Kp_z*e_z + ...
    Kd_z*e_vz;

%% Attitude

tau_phi = ...
    Kp_phi*(phi_des-phi) - ...
    Kd_phi*p;

tau_theta = ...
    Kp_theta*(theta_des-theta) - ...
    Kd_theta*q;

tau_psi = ...
    Kp_psi*(psi_des-psi) - ...
    Kd_psi*r;

%% Motor mixer

motor_thrusts_raw = ...
    motor_mixer( ...
        T, ...
        tau_phi, ...
        tau_theta, ...
        tau_psi, ...
        L, ...
        k_yaw);

motor_thrusts_sat = max( ...
    min( ...
        motor_thrusts_raw, ...
        motor_thrust_max), ...
    motor_thrust_min);

u_actual = ...
    motor_unmixer( ...
        motor_thrusts_sat, ...
        L, ...
        k_yaw);

%% Nonlinear plant

xdot = ...
    quad_dynamics( ...
        x, ...
        u_actual, ...
        m, ...
        g, ...
        I);

%% Wind disturbance

if t >= wind_start && t <= wind_end

    xdot(4) = ...
        xdot(4) + wind_force/m;

end

end