%% AeroStabilize - LQI Mass Uncertainty 3D Animation
%
% Demonstrates LQI rejecting +20% mass model mismatch.
%
% Controller model:
%   nominal mass = 1.5 kg
%
% Actual nonlinear plant:
%   actual mass = 1.8 kg
%
% Animation shows:
% - Desired helix
% - Actual LQI trajectory
% - 3D quadrotor
% - Live altitude error
% - Integral state
% - Total thrust
%
% Main effect:
% The LQI integral state builds the additional thrust
% required to eliminate the persistent altitude error.

clear;
clc;
close all;

addpath('../models');
addpath('../trajectories');

run('../parameters/quadcopter_params.m');

%% ============================================================
%% MASS UNCERTAINTY
%% ============================================================

m_nominal = m;

mass_increase = 0.20;

m_actual = ...
    m_nominal * (1 + mass_increase);

fprintf('Nominal mass: %.3f kg\n', m_nominal);
fprintf('Actual mass:  %.3f kg\n', m_actual);
fprintf('Mass error:   +%.1f %%\n', mass_increase*100);

%% ============================================================
%% SETTINGS
%% ============================================================

tspan = [0 25];

motor_thrust_min = 0.0;
motor_thrust_max = 7.5;

frame_dt = 0.05;

animation_speed = 2.0;

%% ============================================================
%% NOMINAL LINEAR MODEL
%% ============================================================

A = zeros(12,12);

A(1,4) = 1;
A(2,5) = 1;
A(3,6) = 1;

A(4,8) = g;
A(5,7) = -g;

A(7,10) = 1;
A(8,11) = 1;
A(9,12) = 1;

B = zeros(12,4);

B(6,1)  = 1/m_nominal;
B(10,2) = 1/I(1,1);
B(11,3) = 1/I(2,2);
B(12,4) = 1/I(3,3);

%% ============================================================
%% AUGMENT MODEL WITH ALTITUDE INTEGRATOR
%% ============================================================

A_aug = zeros(13,13);

A_aug(1:12,1:12) = A;

% xi_dot = z_ref - z
% error state is x - x_ref
% therefore xi_dot = -e_z

A_aug(13,3) = -1;

B_aug = zeros(13,4);

B_aug(1:12,:) = B;

%% ============================================================
%% CONTROLLABILITY
%% ============================================================

Co_aug = ctrb(A_aug,B_aug);

fprintf( ...
    'Augmented controllability rank: %d / 13\n', ...
    rank(Co_aug));

%% ============================================================
%% LQI DESIGN
%% ============================================================

Q_aug = diag([ ...
    20, ...
    20, ...
    30, ...
    5, ...
    5, ...
    8, ...
    40, ...
    40, ...
    10, ...
    2, ...
    2, ...
    2, ...
    25]);

R = diag([ ...
    1.0, ...
    0.5, ...
    0.5, ...
    0.5]);

K_aug = lqr( ...
    A_aug, ...
    B_aug, ...
    Q_aug, ...
    R);

Kx = K_aug(:,1:12);

Ki = K_aug(:,13);

%% ============================================================
%% INITIAL STATE
%% ============================================================

x0 = zeros(13,1);

[x_start, ...
 y_start, ...
 z_start, ...
 vx_start, ...
 vy_start, ...
 vz_start] = ...
    helix_trajectory(0);

x0(1) = x_start;
x0(2) = y_start;
x0(3) = z_start;

x0(4) = vx_start;
x0(5) = vy_start;
x0(6) = vz_start;

x0(13) = 0;

%% ============================================================
%% RUN SIMULATION
%% ============================================================

dynamics = @(t,x) ...
    lqi_mass_animation_closed_loop( ...
        t, ...
        x, ...
        Kx, ...
        Ki, ...
        m_nominal, ...
        m_actual, ...
        g, ...
        I, ...
        L, ...
        k_yaw, ...
        motor_thrust_min, ...
        motor_thrust_max);

[t,x] = ode45( ...
    dynamics, ...
    tspan, ...
    x0);

%% ============================================================
%% LOG DATA
%% ============================================================

N = length(t);

ref_log = zeros(N,12);
motor_log = zeros(N,4);
motor_raw_log = zeros(N,4);
control_log = zeros(N,4);

for k = 1:N

    [~, ...
     ref_k, ...
     motor_k, ...
     motor_raw_k, ...
     u_k] = ...
        lqi_mass_animation_closed_loop( ...
            t(k), ...
            x(k,:)', ...
            Kx, ...
            Ki, ...
            m_nominal, ...
            m_actual, ...
            g, ...
            I, ...
            L, ...
            k_yaw, ...
            motor_thrust_min, ...
            motor_thrust_max);

    ref_log(k,:) = ref_k';

    motor_log(k,:) = motor_k';

    motor_raw_log(k,:) = motor_raw_k';

    control_log(k,:) = u_k';

end

%% ============================================================
%% ERRORS
%% ============================================================

error_x = ref_log(:,1) - x(:,1);
error_y = ref_log(:,2) - x(:,2);
error_z = ref_log(:,3) - x(:,3);

position_error = sqrt( ...
    error_x.^2 + ...
    error_y.^2 + ...
    error_z.^2);

fprintf('\n============================================\n');
fprintf('LQI MASS UNCERTAINTY ANIMATION RESULTS\n');
fprintf('============================================\n');

fprintf( ...
    'Final altitude error: %.4f m\n', ...
    error_z(end));

fprintf( ...
    'Final 3D position error: %.4f m\n', ...
    position_error(end));

fprintf( ...
    'Final integral state: %.4f m*s\n', ...
    x(end,13));

fprintf( ...
    'Final total thrust: %.3f N\n', ...
    control_log(end,1));

fprintf( ...
    'Actual hover thrust required: %.3f N\n', ...
    m_actual*g);

%% ============================================================
%% INTERPOLATE FOR ANIMATION
%% ============================================================

t_anim = ...
    t(1):frame_dt:t(end);

x_anim = interp1( ...
    t, ...
    x, ...
    t_anim, ...
    'linear');

ref_anim = interp1( ...
    t, ...
    ref_log, ...
    t_anim, ...
    'linear');

error_anim = interp1( ...
    t, ...
    position_error, ...
    t_anim, ...
    'linear');

alt_error_anim = interp1( ...
    t, ...
    error_z, ...
    t_anim, ...
    'linear');

thrust_anim = interp1( ...
    t, ...
    control_log(:,1), ...
    t_anim, ...
    'linear');

%% ============================================================
%% DRONE GEOMETRY
%% ============================================================

arm_visual = 0.35;

rotor_radius = 0.10;

rotor_points = 40;

motor1_body = [ arm_visual; 0; 0];
motor2_body = [0;  arm_visual; 0];
motor3_body = [-arm_visual; 0; 0];
motor4_body = [0; -arm_visual; 0];

rotor_angle = ...
    linspace(0,2*pi,rotor_points);

rotor_circle = [ ...
    rotor_radius*cos(rotor_angle);
    rotor_radius*sin(rotor_angle);
    zeros(1,rotor_points)];

%% ============================================================
%% FIGURE
%% ============================================================

fig = figure( ...
    'Name', ...
    'AeroStabilize - LQI Mass Uncertainty', ...
    'NumberTitle', ...
    'off');

fig.Position = [ ...
    100 ...
    80 ...
    1400 ...
    780];

%% ============================================================
%% MAIN 3D AXIS
%% ============================================================

ax3d = axes( ...
    'Parent', ...
    fig, ...
    'Position', ...
    [0.05 0.12 0.61 0.80]);

hold(ax3d,'on');

grid(ax3d,'on');

axis(ax3d,'equal');

xlabel(ax3d,'x [m]');
ylabel(ax3d,'y [m]');
zlabel(ax3d,'z [m]');

view(ax3d,45,25);

%% Desired trajectory

plot3( ...
    ax3d, ...
    ref_anim(:,1), ...
    ref_anim(:,2), ...
    ref_anim(:,3), ...
    '--', ...
    'LineWidth',1.5);

%% Full actual trajectory

plot3( ...
    ax3d, ...
    x_anim(:,1), ...
    x_anim(:,2), ...
    x_anim(:,3), ...
    ':', ...
    'LineWidth',1.0);

%% Axis limits

margin = 1.0;

all_x = [ ...
    ref_anim(:,1);
    x_anim(:,1)];

all_y = [ ...
    ref_anim(:,2);
    x_anim(:,2)];

all_z = [ ...
    ref_anim(:,3);
    x_anim(:,3)];

xlim( ...
    ax3d, ...
    [min(all_x)-margin ...
     max(all_x)+margin]);

ylim( ...
    ax3d, ...
    [min(all_y)-margin ...
     max(all_y)+margin]);

zlim( ...
    ax3d, ...
    [min(all_z)-0.6 ...
     max(all_z)+0.8]);

%% ============================================================
%% DRONE OBJECTS
%% ============================================================

flight_path = plot3( ...
    ax3d, ...
    NaN,NaN,NaN, ...
    'LineWidth',2);

arm1_plot = plot3( ...
    ax3d, ...
    NaN,NaN,NaN, ...
    'LineWidth',3);

arm2_plot = plot3( ...
    ax3d, ...
    NaN,NaN,NaN, ...
    'LineWidth',3);

body_plot = plot3( ...
    ax3d, ...
    NaN,NaN,NaN, ...
    'o', ...
    'MarkerSize',9, ...
    'MarkerFaceColor','auto');

rotor1_plot = plot3(ax3d,NaN,NaN,NaN,'LineWidth',1.5);
rotor2_plot = plot3(ax3d,NaN,NaN,NaN,'LineWidth',1.5);
rotor3_plot = plot3(ax3d,NaN,NaN,NaN,'LineWidth',1.5);
rotor4_plot = plot3(ax3d,NaN,NaN,NaN,'LineWidth',1.5);

desired_point = plot3( ...
    ax3d, ...
    NaN,NaN,NaN, ...
    'x', ...
    'MarkerSize',11, ...
    'LineWidth',2);

status_text = text( ...
    ax3d, ...
    0.02, ...
    0.97, ...
    '', ...
    'Units','normalized', ...
    'VerticalAlignment','top', ...
    'FontSize',10, ...
    'FontWeight','bold');

%% ============================================================
%% ALTITUDE ERROR AXIS
%% ============================================================

ax_alt = axes( ...
    'Parent',fig, ...
    'Position',[0.72 0.66 0.24 0.23]);

hold(ax_alt,'on');

grid(ax_alt,'on');

plot( ...
    ax_alt, ...
    t_anim, ...
    alt_error_anim, ...
    'LineWidth',1.4);

yline(ax_alt,0,'--');

alt_marker = plot( ...
    ax_alt, ...
    NaN,NaN, ...
    'o', ...
    'MarkerSize',7, ...
    'MarkerFaceColor','auto');

xlabel(ax_alt,'Time [s]');
ylabel(ax_alt,'Altitude Error [m]');

title(ax_alt,'Altitude Error');

xlim(ax_alt,tspan);

%% ============================================================
%% INTEGRAL STATE AXIS
%% ============================================================

ax_integral = axes( ...
    'Parent',fig, ...
    'Position',[0.72 0.38 0.24 0.23]);

hold(ax_integral,'on');

grid(ax_integral,'on');

plot( ...
    ax_integral, ...
    t_anim, ...
    x_anim(:,13), ...
    'LineWidth',1.4);

integral_marker = plot( ...
    ax_integral, ...
    NaN,NaN, ...
    'o', ...
    'MarkerSize',7, ...
    'MarkerFaceColor','auto');

xlabel(ax_integral,'Time [s]');
ylabel(ax_integral,'Integral [m*s]');

title(ax_integral,'LQI Integral State');

xlim(ax_integral,tspan);

%% ============================================================
%% THRUST AXIS
%% ============================================================

ax_thrust = axes( ...
    'Parent',fig, ...
    'Position',[0.72 0.10 0.24 0.23]);

hold(ax_thrust,'on');

grid(ax_thrust,'on');

plot( ...
    ax_thrust, ...
    t_anim, ...
    thrust_anim, ...
    'LineWidth',1.4);

yline( ...
    ax_thrust, ...
    m_nominal*g, ...
    '--', ...
    'Nominal Hover');

yline( ...
    ax_thrust, ...
    m_actual*g, ...
    '--', ...
    'Actual Hover');

thrust_marker = plot( ...
    ax_thrust, ...
    NaN,NaN, ...
    'o', ...
    'MarkerSize',7, ...
    'MarkerFaceColor','auto');

xlabel(ax_thrust,'Time [s]');
ylabel(ax_thrust,'Total Thrust [N]');

title(ax_thrust,'LQI Thrust Compensation');

xlim(ax_thrust,tspan);

%% ============================================================
%% ANIMATION LOOP
%% ============================================================

for k = 1:length(t_anim)

    if ~isgraphics(fig)
        break;
    end

    current_time = ...
        t_anim(k);

    %% Current state

    position = [ ...
        x_anim(k,1);
        x_anim(k,2);
        x_anim(k,3)];

    phi = ...
        x_anim(k,7);

    theta = ...
        x_anim(k,8);

    psi = ...
        x_anim(k,9);

    %% Rotation matrix

    Rx = [ ...
        1 0 0;
        0 cos(phi) -sin(phi);
        0 sin(phi) cos(phi)];

    Ry = [ ...
        cos(theta) 0 sin(theta);
        0 1 0;
        -sin(theta) 0 cos(theta)];

    Rz = [ ...
        cos(psi) -sin(psi) 0;
        sin(psi) cos(psi) 0;
        0 0 1];

    Rbw = ...
        Rz * Ry * Rx;

    %% Motor positions

    motor1_world = ...
        position + Rbw*motor1_body;

    motor2_world = ...
        position + Rbw*motor2_body;

    motor3_world = ...
        position + Rbw*motor3_body;

    motor4_world = ...
        position + Rbw*motor4_body;

    %% Arms

    if isgraphics(arm1_plot)

        set( ...
            arm1_plot, ...
            'XData',[motor1_world(1) motor3_world(1)], ...
            'YData',[motor1_world(2) motor3_world(2)], ...
            'ZData',[motor1_world(3) motor3_world(3)]);

    end

    if isgraphics(arm2_plot)

        set( ...
            arm2_plot, ...
            'XData',[motor2_world(1) motor4_world(1)], ...
            'YData',[motor2_world(2) motor4_world(2)], ...
            'ZData',[motor2_world(3) motor4_world(3)]);

    end

    %% Body

    if isgraphics(body_plot)

        set( ...
            body_plot, ...
            'XData',position(1), ...
            'YData',position(2), ...
            'ZData',position(3));

    end

    %% Rotors

    rotor_world = ...
        Rbw * rotor_circle;

    rotor1 = ...
        rotor_world + motor1_world;

    rotor2 = ...
        rotor_world + motor2_world;

    rotor3 = ...
        rotor_world + motor3_world;

    rotor4 = ...
        rotor_world + motor4_world;

    if isgraphics(rotor1_plot)

        set( ...
            rotor1_plot, ...
            'XData',rotor1(1,:), ...
            'YData',rotor1(2,:), ...
            'ZData',rotor1(3,:));

    end

    if isgraphics(rotor2_plot)

        set( ...
            rotor2_plot, ...
            'XData',rotor2(1,:), ...
            'YData',rotor2(2,:), ...
            'ZData',rotor2(3,:));

    end

    if isgraphics(rotor3_plot)

        set( ...
            rotor3_plot, ...
            'XData',rotor3(1,:), ...
            'YData',rotor3(2,:), ...
            'ZData',rotor3(3,:));

    end

    if isgraphics(rotor4_plot)

        set( ...
            rotor4_plot, ...
            'XData',rotor4(1,:), ...
            'YData',rotor4(2,:), ...
            'ZData',rotor4(3,:));

    end

    %% Travelled path

    if isgraphics(flight_path)

        set( ...
            flight_path, ...
            'XData',x_anim(1:k,1), ...
            'YData',x_anim(1:k,2), ...
            'ZData',x_anim(1:k,3));

    end

    %% Desired point

    if isgraphics(desired_point)

        set( ...
            desired_point, ...
            'XData',ref_anim(k,1), ...
            'YData',ref_anim(k,2), ...
            'ZData',ref_anim(k,3));

    end

    %% Live graph markers

    if isgraphics(alt_marker)

        set( ...
            alt_marker, ...
            'XData',current_time, ...
            'YData',alt_error_anim(k));

    end

    if isgraphics(integral_marker)

        set( ...
            integral_marker, ...
            'XData',current_time, ...
            'YData',x_anim(k,13));

    end

    if isgraphics(thrust_marker)

        set( ...
            thrust_marker, ...
            'XData',current_time, ...
            'YData',thrust_anim(k));

    end

    %% Status text

    status_string = sprintf( ...
        ['Controller: LQI + Feedforward\n' ...
         'Nominal Mass: %.2f kg\n' ...
         'Actual Mass: %.2f kg\n' ...
         'Time: %.2f s\n' ...
         '3D Error: %.3f m\n' ...
         'Altitude Error: %.3f m\n' ...
         'Integral State: %.3f m*s\n' ...
         'Total Thrust: %.2f N'], ...
         m_nominal, ...
         m_actual, ...
         current_time, ...
         error_anim(k), ...
         alt_error_anim(k), ...
         x_anim(k,13), ...
         thrust_anim(k));

    if isgraphics(status_text)

        set( ...
            status_text, ...
            'String', ...
            status_string);

    end

    %% Main title

    if isgraphics(fig)

        sgtitle( ...
            fig, ...
            sprintf( ...
                'AeroStabilize | LQI Rejecting +20%% Mass Error | t = %.2f s', ...
                current_time), ...
            'FontWeight','bold');

    end

    drawnow;

    if ~isgraphics(fig)
        break;
    end

    pause( ...
        frame_dt / animation_speed);

end

%% ============================================================
%% FINISHED
%% ============================================================

if isgraphics(fig)

    sgtitle( ...
        fig, ...
        'AeroStabilize | LQI + Feedforward | Mass Error Rejected', ...
        'FontWeight','bold');

end

fprintf('\nAnimation completed.\n');

%% ============================================================
%% CLOSED LOOP FUNCTION
%% ============================================================

function [ ...
    xdot_aug, ...
    x_ref, ...
    motor_thrusts_sat, ...
    motor_thrusts_raw, ...
    u_actual] = ...
    lqi_mass_animation_closed_loop( ...
    t, ...
    x_aug, ...
    Kx, ...
    Ki, ...
    m_nominal, ...
    m_actual, ...
    g, ...
    I, ...
    L, ...
    k_yaw, ...
    motor_thrust_min, ...
    motor_thrust_max)

%% Vehicle state

x = ...
    x_aug(1:12);

xi = ...
    x_aug(13);

%% Desired trajectory

[x_des, ...
 y_des, ...
 z_des, ...
 vx_des, ...
 vy_des, ...
 vz_des, ...
 ax_ff, ...
 ay_ff, ...
 az_ff] = ...
    helix_trajectory(t);

%% Feedforward attitude

theta_ff = ...
    ax_ff / g;

phi_ff = ...
    -ay_ff / g;

max_ff_angle = ...
    deg2rad(15);

theta_ff = max( ...
    min(theta_ff,max_ff_angle), ...
    -max_ff_angle);

phi_ff = max( ...
    min(phi_ff,max_ff_angle), ...
    -max_ff_angle);

%% Reference

x_ref = zeros(12,1);

x_ref(1) = x_des;
x_ref(2) = y_des;
x_ref(3) = z_des;

x_ref(4) = vx_des;
x_ref(5) = vy_des;
x_ref(6) = vz_des;

x_ref(7) = phi_ff;
x_ref(8) = theta_ff;

%% State error

e = ...
    x - x_ref;

%% LQI control

delta_u = ...
    -Kx*e - Ki*xi;

delta_T = ...
    delta_u(1);

tau_phi = ...
    delta_u(2);

tau_theta = ...
    delta_u(3);

tau_psi = ...
    delta_u(4);

%% Nominal feedforward

T_ff = ...
    m_nominal * ...
    (g + az_ff);

T = ...
    T_ff + delta_T;

%% Motor allocation

motor_thrusts_raw = ...
    motor_mixer( ...
        T, ...
        tau_phi, ...
        tau_theta, ...
        tau_psi, ...
        L, ...
        k_yaw);

motor_thrusts_sat = max( ...
    min( ...
        motor_thrusts_raw, ...
        motor_thrust_max), ...
    motor_thrust_min);

u_actual = ...
    motor_unmixer( ...
        motor_thrusts_sat, ...
        L, ...
        k_yaw);

%% Actual nonlinear plant

xdot = ...
    quad_dynamics( ...
        x, ...
        u_actual, ...
        m_actual, ...
        g, ...
        I);

%% Integral state

z_error = ...
    z_des - x(3);

xi_dot = ...
    z_error;

xdot_aug = [ ...
    xdot;
    xi_dot];

end