%% AeroStabilize
% PD + FF vs LQR + FF vs 3-Axis LQI + FF
%
% Fair robustness comparison under identical conditions.
%
% Scenario:
%   0 - 10 s : nominal hover at [1 1 2] m
%   t = 10 s : constant +2 N X disturbance begins
%   t = 20 s : mass changes from 1.5 kg to 1.8 kg
%   20 - 35 s: wind + payload mismatch both remain active
%
% All controllers:
%   - Same nonlinear 6-DOF plant
%   - Same motor mixer
%   - Same motor limits
%   - Same initial condition
%   - Same disturbances
%
% Goal:
% Compare steady-state disturbance rejection and model-mismatch
% compensation.

clear;
clc;
close all;

%% ============================================================
% PARAMETERS
% ============================================================

g = 9.81;

m_nominal = 1.5;
m_payload = 1.8;

L = 0.225;

Ix = 0.020;
Iy = 0.020;
Iz = 0.040;

I = diag([Ix Iy Iz]);

k_yaw = 0.02;

%% Motor limits

T_motor_min = 0.0;
T_motor_max = 7.5;

%% ============================================================
% DESIRED POSITION
% ============================================================

x_des = 1.0;
y_des = 1.0;
z_des = 2.0;

%% ============================================================
% DISTURBANCE SCHEDULE
% ============================================================

wind_start = 10.0;

payload_time = 20.0;

F_wind = [ ...
    2.0;
    0.0;
    0.0];

%% ============================================================
% SIMULATION SETTINGS
% ============================================================

t_start = 0;
t_end   = 35;

%% ============================================================
% INITIAL STATE
% ============================================================

% Start exactly at the desired position.
% This avoids contaminating RMSE with a large initial step error.

x0_12 = zeros(12,1);

x0_12(1) = x_des;
x0_12(2) = y_des;
x0_12(3) = z_des;

%% ============================================================
% CASCADED PD + FEEDFORWARD GAINS
% ============================================================

Kp_x = 1.0;
Kd_x = 1.4;

Kp_y = 1.0;
Kd_y = 1.4;

Kp_z = 4.0;
Kd_z = 3.0;

Kp_phi = 0.8;
Kd_phi = 0.25;

Kp_theta = 0.8;
Kd_theta = 0.25;

Kp_psi = 0.5;
Kd_psi = 0.20;

%% ============================================================
% LQR MODEL
% ============================================================

A = zeros(12);

A(1,4) = 1;
A(2,5) = 1;
A(3,6) = 1;

A(4,8) = g;
A(5,7) = -g;

A(7,10) = 1;
A(8,11) = 1;
A(9,12) = 1;

B = zeros(12,4);

B(6,1) = 1/m_nominal;

B(10,2) = 1/Ix;
B(11,3) = 1/Iy;
B(12,4) = 1/Iz;

Q = diag([ ...
    20, ...
    20, ...
    30, ...
    5, ...
    5, ...
    8, ...
    40, ...
    40, ...
    10, ...
    2, ...
    2, ...
    2]);

R_lqr = diag([ ...
    1.0, ...
    0.5, ...
    0.5, ...
    0.5]);

K_lqr = lqr(A,B,Q,R_lqr);

%% ============================================================
% 3-AXIS LQI MODEL
% ============================================================

C_pos = zeros(3,12);

C_pos(1,1) = 1;
C_pos(2,2) = 1;
C_pos(3,3) = 1;

A_aug = zeros(15,15);

A_aug(1:12,1:12) = A;

% Integral definition:
%
% xi_dot = desired - actual
%
% With e = x - x_ref:
%
% xi_dot = -C_pos * e

A_aug(13:15,1:12) = -C_pos;

B_aug = zeros(15,4);

B_aug(1:12,:) = B;

q_aug_weights = [ ...
    20, ...
    20, ...
    30, ...
    5, ...
    5, ...
    8, ...
    40, ...
    40, ...
    10, ...
    2, ...
    2, ...
    2, ...
    20, ...
    20, ...
    25];

Q_aug = diag(q_aug_weights);

K_aug = lqr( ...
    A_aug, ...
    B_aug, ...
    Q_aug, ...
    R_lqr);

Kx_lqi = K_aug(:,1:12);

Ki_lqi = K_aug(:,13:15);

%% ============================================================
% CONTROLLABILITY
% ============================================================

rank_lqr = rank(ctrb(A,B));

rank_lqi = rank(ctrb(A_aug,B_aug));

fprintf('============================================\n');
fprintf('PD vs LQR vs LQI Robustness Comparison\n');
fprintf('============================================\n');

fprintf('LQR controllability rank: %d / 12\n', ...
    rank_lqr);

fprintf('LQI controllability rank: %d / 15\n', ...
    rank_lqi);

%% ============================================================
% RUN PD SIMULATION
% ============================================================

ode_pd = @(t,x) dynamics_pd( ...
    t, ...
    x, ...
    x_des, ...
    y_des, ...
    z_des, ...
    Kp_x, ...
    Kd_x, ...
    Kp_y, ...
    Kd_y, ...
    Kp_z, ...
    Kd_z, ...
    Kp_phi, ...
    Kd_phi, ...
    Kp_theta, ...
    Kd_theta, ...
    Kp_psi, ...
    Kd_psi, ...
    m_nominal, ...
    m_payload, ...
    payload_time, ...
    wind_start, ...
    F_wind, ...
    g, ...
    I, ...
    L, ...
    k_yaw, ...
    T_motor_min, ...
    T_motor_max);

options = odeset( ...
    'RelTol',1e-7, ...
    'AbsTol',1e-9);

[t_pd,X_pd] = ode45( ...
    ode_pd, ...
    [t_start t_end], ...
    x0_12, ...
    options);

%% ============================================================
% RUN LQR SIMULATION
% ============================================================

ode_lqr = @(t,x) dynamics_lqr( ...
    t, ...
    x, ...
    K_lqr, ...
    x_des, ...
    y_des, ...
    z_des, ...
    m_nominal, ...
    m_payload, ...
    payload_time, ...
    wind_start, ...
    F_wind, ...
    g, ...
    I, ...
    L, ...
    k_yaw, ...
    T_motor_min, ...
    T_motor_max);

[t_lqr,X_lqr] = ode45( ...
    ode_lqr, ...
    [t_start t_end], ...
    x0_12, ...
    options);

%% ============================================================
% RUN LQI SIMULATION
% ============================================================

x0_15 = zeros(15,1);

x0_15(1:12) = x0_12;

ode_lqi = @(t,x) dynamics_lqi( ...
    t, ...
    x, ...
    Kx_lqi, ...
    Ki_lqi, ...
    x_des, ...
    y_des, ...
    z_des, ...
    m_nominal, ...
    m_payload, ...
    payload_time, ...
    wind_start, ...
    F_wind, ...
    g, ...
    I, ...
    L, ...
    k_yaw, ...
    T_motor_min, ...
    T_motor_max);

[t_lqi,X_lqi] = ode45( ...
    ode_lqi, ...
    [t_start t_end], ...
    x0_15, ...
    options);

%% ============================================================
% INTERPOLATE TO COMMON TIME VECTOR
% ============================================================

t_common = linspace( ...
    t_start, ...
    t_end, ...
    3501)';

Xpd = interp1( ...
    t_pd, ...
    X_pd, ...
    t_common, ...
    'linear');

Xlqr = interp1( ...
    t_lqr, ...
    X_lqr, ...
    t_common, ...
    'linear');

Xlqi = interp1( ...
    t_lqi, ...
    X_lqi, ...
    t_common, ...
    'linear');

%% ============================================================
% POSITION ERRORS
% ============================================================

ref_position = [ ...
    x_des, ...
    y_des, ...
    z_des];

err_pd_xyz = ...
    ref_position - Xpd(:,1:3);

err_lqr_xyz = ...
    ref_position - Xlqr(:,1:3);

err_lqi_xyz = ...
    ref_position - Xlqi(:,1:3);

err_pd = sqrt(sum(err_pd_xyz.^2,2));

err_lqr = sqrt(sum(err_lqr_xyz.^2,2));

err_lqi = sqrt(sum(err_lqi_xyz.^2,2));

%% ============================================================
% ANALYSIS WINDOWS
% ============================================================

idx_nominal = ...
    t_common < wind_start;

idx_wind = ...
    t_common >= wind_start & ...
    t_common < payload_time;

idx_combined = ...
    t_common >= payload_time;

%% ============================================================
% RMSE
% ============================================================

RMSE_pd_all = sqrt(mean(err_pd.^2));

RMSE_lqr_all = sqrt(mean(err_lqr.^2));

RMSE_lqi_all = sqrt(mean(err_lqi.^2));

RMSE_pd_wind = sqrt( ...
    mean(err_pd(idx_wind).^2));

RMSE_lqr_wind = sqrt( ...
    mean(err_lqr(idx_wind).^2));

RMSE_lqi_wind = sqrt( ...
    mean(err_lqi(idx_wind).^2));

RMSE_pd_combined = sqrt( ...
    mean(err_pd(idx_combined).^2));

RMSE_lqr_combined = sqrt( ...
    mean(err_lqr(idx_combined).^2));

RMSE_lqi_combined = sqrt( ...
    mean(err_lqi(idx_combined).^2));

%% ============================================================
% PEAK ERRORS AFTER WIND
% ============================================================

peak_pd_wind = max( ...
    err_pd(idx_wind));

peak_lqr_wind = max( ...
    err_lqr(idx_wind));

peak_lqi_wind = max( ...
    err_lqi(idx_wind));

%% ============================================================
% FINAL ERRORS
% ============================================================

final_pd_xyz = err_pd_xyz(end,:);

final_lqr_xyz = err_lqr_xyz(end,:);

final_lqi_xyz = err_lqi_xyz(end,:);

final_pd = err_pd(end);

final_lqr = err_lqr(end);

final_lqi = err_lqi(end);

%% ============================================================
% CONTROL HISTORY
% ============================================================

[ ...
    motors_pd, ...
    thrust_pd, ...
    sat_pd] = reconstruct_pd_controls( ...
    t_common, ...
    Xpd, ...
    x_des, ...
    y_des, ...
    z_des, ...
    Kp_x, ...
    Kd_x, ...
    Kp_y, ...
    Kd_y, ...
    Kp_z, ...
    Kd_z, ...
    Kp_phi, ...
    Kd_phi, ...
    Kp_theta, ...
    Kd_theta, ...
    Kp_psi, ...
    Kd_psi, ...
    m_nominal, ...
    g, ...
    L, ...
    k_yaw, ...
    T_motor_min, ...
    T_motor_max);

[ ...
    motors_lqr, ...
    thrust_lqr, ...
    sat_lqr] = reconstruct_lqr_controls( ...
    t_common, ...
    Xlqr, ...
    K_lqr, ...
    x_des, ...
    y_des, ...
    z_des, ...
    m_nominal, ...
    g, ...
    L, ...
    k_yaw, ...
    T_motor_min, ...
    T_motor_max);

[ ...
    motors_lqi, ...
    thrust_lqi, ...
    sat_lqi] = reconstruct_lqi_controls( ...
    t_common, ...
    Xlqi, ...
    Kx_lqi, ...
    Ki_lqi, ...
    x_des, ...
    y_des, ...
    z_des, ...
    m_nominal, ...
    g, ...
    L, ...
    k_yaw, ...
    T_motor_min, ...
    T_motor_max);

%% Saturation time

sat_time_pd = trapz( ...
    t_common, ...
    double(sat_pd));

sat_time_lqr = trapz( ...
    t_common, ...
    double(sat_lqr));

sat_time_lqi = trapz( ...
    t_common, ...
    double(sat_lqi));

sat_pct_pd = ...
    100*sat_time_pd/t_end;

sat_pct_lqr = ...
    100*sat_time_lqr/t_end;

sat_pct_lqi = ...
    100*sat_time_lqi/t_end;

%% ============================================================
% PRINT RESULTS
% ============================================================

fprintf('\n');
fprintf('============================================\n');
fprintf('OVERALL RMSE\n');
fprintf('============================================\n');

fprintf('PD  + FF: %.6f m\n', ...
    RMSE_pd_all);

fprintf('LQR + FF: %.6f m\n', ...
    RMSE_lqr_all);

fprintf('LQI + FF: %.6f m\n', ...
    RMSE_lqi_all);

fprintf('\n');

fprintf('============================================\n');
fprintf('CONSTANT WIND WINDOW: 10 - 20 s\n');
fprintf('============================================\n');

fprintf('PD  RMSE: %.6f m\n', ...
    RMSE_pd_wind);

fprintf('LQR RMSE: %.6f m\n', ...
    RMSE_lqr_wind);

fprintf('LQI RMSE: %.6f m\n', ...
    RMSE_lqi_wind);

fprintf('\n');

fprintf('PD  peak error: %.6f m\n', ...
    peak_pd_wind);

fprintf('LQR peak error: %.6f m\n', ...
    peak_lqr_wind);

fprintf('LQI peak error: %.6f m\n', ...
    peak_lqi_wind);

fprintf('\n');

fprintf('============================================\n');
fprintf('WIND + PAYLOAD WINDOW: 20 - 35 s\n');
fprintf('============================================\n');

fprintf('PD  RMSE: %.6f m\n', ...
    RMSE_pd_combined);

fprintf('LQR RMSE: %.6f m\n', ...
    RMSE_lqr_combined);

fprintf('LQI RMSE: %.6f m\n', ...
    RMSE_lqi_combined);

fprintf('\n');

fprintf('============================================\n');
fprintf('FINAL POSITION ERRORS\n');
fprintf('============================================\n');

fprintf('PD:\n');

fprintf('  Ex = %.6f m\n', ...
    final_pd_xyz(1));

fprintf('  Ey = %.6f m\n', ...
    final_pd_xyz(2));

fprintf('  Ez = %.6f m\n', ...
    final_pd_xyz(3));

fprintf('  3D = %.6f m\n', ...
    final_pd);

fprintf('\n');

fprintf('LQR:\n');

fprintf('  Ex = %.6f m\n', ...
    final_lqr_xyz(1));

fprintf('  Ey = %.6f m\n', ...
    final_lqr_xyz(2));

fprintf('  Ez = %.6f m\n', ...
    final_lqr_xyz(3));

fprintf('  3D = %.6f m\n', ...
    final_lqr);

fprintf('\n');

fprintf('LQI:\n');

fprintf('  Ex = %.6f m\n', ...
    final_lqi_xyz(1));

fprintf('  Ey = %.6f m\n', ...
    final_lqi_xyz(2));

fprintf('  Ez = %.6f m\n', ...
    final_lqi_xyz(3));

fprintf('  3D = %.6f m\n', ...
    final_lqi);

fprintf('\n');

fprintf('============================================\n');
fprintf('MOTOR SATURATION\n');
fprintf('============================================\n');

fprintf('PD:  %.3f s  (%.2f %%)\n', ...
    sat_time_pd, ...
    sat_pct_pd);

fprintf('LQR: %.3f s  (%.2f %%)\n', ...
    sat_time_lqr, ...
    sat_pct_lqr);

fprintf('LQI: %.3f s  (%.2f %%)\n', ...
    sat_time_lqi, ...
    sat_pct_lqi);

fprintf('\n');

fprintf('Maximum motor thrust:\n');

fprintf('PD:  %.3f N\n', ...
    max(motors_pd,[],'all'));

fprintf('LQR: %.3f N\n', ...
    max(motors_lqr,[],'all'));

fprintf('LQI: %.3f N\n', ...
    max(motors_lqi,[],'all'));

fprintf('\n');

fprintf('Final total thrust:\n');

fprintf('PD:  %.3f N\n', ...
    thrust_pd(end));

fprintf('LQR: %.3f N\n', ...
    thrust_lqr(end));

fprintf('LQI: %.3f N\n', ...
    thrust_lqi(end));

fprintf('\n');

fprintf('Required vertical hover thrust at 1.8 kg:\n');

fprintf('%.3f N\n', ...
    m_payload*g);

fprintf('============================================\n');

%% ============================================================
% PLOT 1: 3D POSITION ERROR
% ============================================================

figure('Position',[120 100 850 500]);

plot( ...
    t_common, ...
    err_pd, ...
    'LineWidth',1.5);

hold on;

plot( ...
    t_common, ...
    err_lqr, ...
    'LineWidth',1.5);

plot( ...
    t_common, ...
    err_lqi, ...
    'LineWidth',1.7);

xline( ...
    wind_start, ...
    '--', ...
    'Constant Wind ON');

xline( ...
    payload_time, ...
    '--', ...
    'Payload +20%');

grid on;

xlabel('Time [s]');

ylabel('3D Position Error [m]');

title('PD vs LQR vs LQI Robustness');

legend( ...
    'PD + FF', ...
    'LQR + FF', ...
    'LQI + FF', ...
    'Location','best');

%% ============================================================
% PLOT 2: X ERROR
% ============================================================

figure('Position',[150 120 850 500]);

plot( ...
    t_common, ...
    err_pd_xyz(:,1), ...
    'LineWidth',1.5);

hold on;

plot( ...
    t_common, ...
    err_lqr_xyz(:,1), ...
    'LineWidth',1.5);

plot( ...
    t_common, ...
    err_lqi_xyz(:,1), ...
    'LineWidth',1.7);

xline(wind_start,'--','Wind ON');

xline(payload_time,'--','Payload +20%');

yline(0,'--');

grid on;

xlabel('Time [s]');

ylabel('X Position Error [m]');

title('Constant Lateral Disturbance Rejection');

legend( ...
    'PD + FF', ...
    'LQR + FF', ...
    'LQI + FF', ...
    'Location','best');

%% ============================================================
% PLOT 3: ALTITUDE ERROR
% ============================================================

figure('Position',[180 140 850 500]);

plot( ...
    t_common, ...
    err_pd_xyz(:,3), ...
    'LineWidth',1.5);

hold on;

plot( ...
    t_common, ...
    err_lqr_xyz(:,3), ...
    'LineWidth',1.5);

plot( ...
    t_common, ...
    err_lqi_xyz(:,3), ...
    'LineWidth',1.7);

xline(wind_start,'--','Wind ON');

xline(payload_time,'--','Payload +20%');

yline(0,'--');

grid on;

xlabel('Time [s]');

ylabel('Altitude Error [m]');

title('Payload-Mismatch Rejection');

legend( ...
    'PD + FF', ...
    'LQR + FF', ...
    'LQI + FF', ...
    'Location','best');

%% ============================================================
% PLOT 4: X POSITION
% ============================================================

figure('Position',[210 160 850 500]);

plot( ...
    t_common, ...
    Xpd(:,1), ...
    'LineWidth',1.4);

hold on;

plot( ...
    t_common, ...
    Xlqr(:,1), ...
    'LineWidth',1.4);

plot( ...
    t_common, ...
    Xlqi(:,1), ...
    'LineWidth',1.6);

yline( ...
    x_des, ...
    '--', ...
    'Desired');

xline(wind_start,'--','Wind ON');

xline(payload_time,'--','Payload +20%');

grid on;

xlabel('Time [s]');
ylabel('X Position [m]');

title('X Position Response');

legend( ...
    'PD + FF', ...
    'LQR + FF', ...
    'LQI + FF', ...
    'Location','best');

%% ============================================================
% PLOT 5: ALTITUDE
% ============================================================

figure('Position',[240 180 850 500]);

plot( ...
    t_common, ...
    Xpd(:,3), ...
    'LineWidth',1.4);

hold on;

plot( ...
    t_common, ...
    Xlqr(:,3), ...
    'LineWidth',1.4);

plot( ...
    t_common, ...
    Xlqi(:,3), ...
    'LineWidth',1.6);

yline( ...
    z_des, ...
    '--', ...
    'Desired');

xline(wind_start,'--','Wind ON');

xline(payload_time,'--','Payload +20%');

grid on;

xlabel('Time [s]');
ylabel('Altitude [m]');

title('Altitude Response');

legend( ...
    'PD + FF', ...
    'LQR + FF', ...
    'LQI + FF', ...
    'Location','best');

%% ============================================================
% PLOT 6: TOTAL THRUST
% ============================================================

figure('Position',[270 200 850 500]);

plot( ...
    t_common, ...
    thrust_pd, ...
    'LineWidth',1.4);

hold on;

plot( ...
    t_common, ...
    thrust_lqr, ...
    'LineWidth',1.4);

plot( ...
    t_common, ...
    thrust_lqi, ...
    'LineWidth',1.6);

yline( ...
    m_nominal*g, ...
    '--', ...
    '1.5 kg Hover');

yline( ...
    m_payload*g, ...
    '--', ...
    '1.8 kg Vertical Hover');

xline(wind_start,'--','Wind ON');

xline(payload_time,'--','Payload +20%');

grid on;

xlabel('Time [s]');
ylabel('Total Thrust [N]');

title('Controller Thrust Response');

legend( ...
    'PD + FF', ...
    'LQR + FF', ...
    'LQI + FF', ...
    'Location','best');

%% ============================================================
% PLOT 7: LQI INTEGRAL STATES
% ============================================================

figure('Position',[300 220 850 500]);

plot( ...
    t_common, ...
    Xlqi(:,13), ...
    'LineWidth',1.5);

hold on;

plot( ...
    t_common, ...
    Xlqi(:,14), ...
    'LineWidth',1.5);

plot( ...
    t_common, ...
    Xlqi(:,15), ...
    'LineWidth',1.5);

xline(wind_start,'--','Wind ON');

xline(payload_time,'--','Payload +20%');

grid on;

xlabel('Time [s]');
ylabel('Integral State');

title('LQI Integral Compensation');

legend( ...
    '\xi_x', ...
    '\xi_y', ...
    '\xi_z', ...
    'Location','best');

%% ============================================================
% LOCAL FUNCTION: PD DYNAMICS
% ============================================================

function dx = dynamics_pd( ...
    t, ...
    state, ...
    x_des, ...
    y_des, ...
    z_des, ...
    Kp_x, ...
    Kd_x, ...
    Kp_y, ...
    Kd_y, ...
    Kp_z, ...
    Kd_z, ...
    Kp_phi, ...
    Kd_phi, ...
    Kp_theta, ...
    Kd_theta, ...
    Kp_psi, ...
    Kd_psi, ...
    m_nominal, ...
    m_payload, ...
    payload_time, ...
    wind_start, ...
    F_wind, ...
    g, ...
    I, ...
    L, ...
    k_yaw, ...
    T_motor_min, ...
    T_motor_max)

%% Extract state

x = state(1);
y = state(2);
z = state(3);

vx = state(4);
vy = state(5);
vz = state(6);

phi = state(7);
theta = state(8);
psi = state(9);

p = state(10);
q = state(11);
r = state(12);

%% Actual mass

if t < payload_time

    m_actual = m_nominal;

else

    m_actual = m_payload;

end

%% Position errors

ex = x_des - x;
ey = y_des - y;
ez = z_des - z;

%% Desired accelerations
% Static position target, therefore reference velocities and
% accelerations are zero.

ax_des = ...
    Kp_x*ex + ...
    Kd_x*(0-vx);

ay_des = ...
    Kp_y*ey + ...
    Kd_y*(0-vy);

%% Desired attitude

theta_des = ax_des/g;

phi_des = -ay_des/g;

psi_des = 0;

%% Altitude thrust

T_cmd = ...
    m_nominal*g + ...
    Kp_z*ez + ...
    Kd_z*(0-vz);

%% Attitude PD

tau_phi = ...
    Kp_phi*(phi_des-phi) + ...
    Kd_phi*(0-p);

tau_theta = ...
    Kp_theta*(theta_des-theta) + ...
    Kd_theta*(0-q);

tau_psi = ...
    Kp_psi*(psi_des-psi) + ...
    Kd_psi*(0-r);

u_cmd = [ ...
    T_cmd;
    tau_phi;
    tau_theta;
    tau_psi];

%% Plant

dx = nonlinear_plant( ...
    t, ...
    state, ...
    u_cmd, ...
    m_actual, ...
    wind_start, ...
    F_wind, ...
    g, ...
    I, ...
    L, ...
    k_yaw, ...
    T_motor_min, ...
    T_motor_max);

end

%% ============================================================
% LOCAL FUNCTION: LQR DYNAMICS
% ============================================================

function dx = dynamics_lqr( ...
    t, ...
    state, ...
    K, ...
    x_des, ...
    y_des, ...
    z_des, ...
    m_nominal, ...
    m_payload, ...
    payload_time, ...
    wind_start, ...
    F_wind, ...
    g, ...
    I, ...
    L, ...
    k_yaw, ...
    T_motor_min, ...
    T_motor_max)

%% Actual mass

if t < payload_time

    m_actual = m_nominal;

else

    m_actual = m_payload;

end

%% Desired state

x_ref = zeros(12,1);

x_ref(1) = x_des;
x_ref(2) = y_des;
x_ref(3) = z_des;

%% State error

e = state - x_ref;

%% LQR feedback

delta_u = -K*e;

u_cmd = [ ...
    m_nominal*g;
    0;
    0;
    0] + delta_u;

%% Plant

dx = nonlinear_plant( ...
    t, ...
    state, ...
    u_cmd, ...
    m_actual, ...
    wind_start, ...
    F_wind, ...
    g, ...
    I, ...
    L, ...
    k_yaw, ...
    T_motor_min, ...
    T_motor_max);

end

%% ============================================================
% LOCAL FUNCTION: LQI DYNAMICS
% ============================================================

function dx_aug = dynamics_lqi( ...
    t, ...
    x_aug, ...
    Kx, ...
    Ki, ...
    x_des, ...
    y_des, ...
    z_des, ...
    m_nominal, ...
    m_payload, ...
    payload_time, ...
    wind_start, ...
    F_wind, ...
    g, ...
    I, ...
    L, ...
    k_yaw, ...
    T_motor_min, ...
    T_motor_max)

state = x_aug(1:12);

xi = x_aug(13:15);

%% Actual mass

if t < payload_time

    m_actual = m_nominal;

else

    m_actual = m_payload;

end

%% Reference

x_ref = zeros(12,1);

x_ref(1) = x_des;
x_ref(2) = y_des;
x_ref(3) = z_des;

%% State error

e = state - x_ref;

%% LQI

delta_u = ...
    -Kx*e - ...
    Ki*xi;

u_cmd = [ ...
    m_nominal*g;
    0;
    0;
    0] + delta_u;

%% Physical plant

dx = nonlinear_plant( ...
    t, ...
    state, ...
    u_cmd, ...
    m_actual, ...
    wind_start, ...
    F_wind, ...
    g, ...
    I, ...
    L, ...
    k_yaw, ...
    T_motor_min, ...
    T_motor_max);

%% Integral states

xi_dot = [ ...
    x_des - state(1);
    y_des - state(2);
    z_des - state(3)];

dx_aug = [ ...
    dx;
    xi_dot];

end

%% ============================================================
% LOCAL FUNCTION: NONLINEAR PLANT
% ============================================================

function dx = nonlinear_plant( ...
    t, ...
    state, ...
    u_cmd, ...
    m_actual, ...
    wind_start, ...
    F_wind, ...
    g, ...
    I, ...
    L, ...
    k_yaw, ...
    T_motor_min, ...
    T_motor_max)

vx = state(4);
vy = state(5);
vz = state(6);

phi = state(7);
theta = state(8);
psi = state(9);

p = state(10);
q = state(11);
r = state(12);

%% Mixer

M = [ ...
    1,      1,      1,      1;
    0,      L,      0,     -L;
   -L,      0,      L,      0;
    k_yaw, -k_yaw,  k_yaw, -k_yaw];

motor_thrust = M\u_cmd;

motor_thrust = min( ...
    max(motor_thrust,T_motor_min), ...
    T_motor_max);

u_actual = M*motor_thrust;

T = u_actual(1);

tau = u_actual(2:4);

%% Rotation

Rx = [ ...
    1,0,0;
    0,cos(phi),-sin(phi);
    0,sin(phi),cos(phi)];

Ry = [ ...
    cos(theta),0,sin(theta);
    0,1,0;
    -sin(theta),0,cos(theta)];

Rz = [ ...
    cos(psi),-sin(psi),0;
    sin(psi),cos(psi),0;
    0,0,1];

Rbw = Rz*Ry*Rx;

%% Forces

F_thrust = ...
    Rbw*[0;0;T];

F_gravity = ...
    [0;0;-m_actual*g];

if t >= wind_start

    F_external = F_wind;

else

    F_external = [0;0;0];

end

acc = ...
    (F_thrust + ...
     F_gravity + ...
     F_external) / m_actual;

%% Rotational dynamics

omega_body = [p;q;r];

omega_dot = I \ ( ...
    tau - ...
    cross(omega_body,I*omega_body));

%% Euler kinematics

E = [ ...
    1, ...
    sin(phi)*tan(theta), ...
    cos(phi)*tan(theta);
    0, ...
    cos(phi), ...
    -sin(phi);
    0, ...
    sin(phi)/cos(theta), ...
    cos(phi)/cos(theta)];

euler_dot = ...
    E*omega_body;

%% State derivative

dx = zeros(12,1);

dx(1) = vx;
dx(2) = vy;
dx(3) = vz;

dx(4:6) = acc;

dx(7:9) = euler_dot;

dx(10:12) = omega_dot;

end

%% ============================================================
% CONTROL RECONSTRUCTION: PD
% ============================================================

function [motor_log,T_log,sat_log] = ...
    reconstruct_pd_controls( ...
    t, ...
    X, ...
    x_des, ...
    y_des, ...
    z_des, ...
    Kp_x, ...
    Kd_x, ...
    Kp_y, ...
    Kd_y, ...
    Kp_z, ...
    Kd_z, ...
    Kp_phi, ...
    Kd_phi, ...
    Kp_theta, ...
    Kd_theta, ...
    Kp_psi, ...
    Kd_psi, ...
    m_nominal, ...
    g, ...
    L, ...
    k_yaw, ...
    T_motor_min, ...
    T_motor_max)

N = length(t);

motor_log = zeros(N,4);

T_log = zeros(N,1);

sat_log = false(N,1);

M = [ ...
    1,      1,      1,      1;
    0,      L,      0,     -L;
   -L,      0,      L,      0;
    k_yaw, -k_yaw,  k_yaw, -k_yaw];

for k = 1:N

    state = X(k,:)';

    ex = x_des - state(1);
    ey = y_des - state(2);
    ez = z_des - state(3);

    ax_des = ...
        Kp_x*ex - ...
        Kd_x*state(4);

    ay_des = ...
        Kp_y*ey - ...
        Kd_y*state(5);

    theta_des = ax_des/g;

    phi_des = -ay_des/g;

    T_cmd = ...
        m_nominal*g + ...
        Kp_z*ez - ...
        Kd_z*state(6);

    tau_phi = ...
        Kp_phi*(phi_des-state(7)) - ...
        Kd_phi*state(10);

    tau_theta = ...
        Kp_theta*(theta_des-state(8)) - ...
        Kd_theta*state(11);

    tau_psi = ...
        Kp_psi*(0-state(9)) - ...
        Kd_psi*state(12);

    u_cmd = [ ...
        T_cmd;
        tau_phi;
        tau_theta;
        tau_psi];

    requested = M\u_cmd;

    sat_log(k) = any( ...
        requested < T_motor_min | ...
        requested > T_motor_max);

    motors = min( ...
        max(requested,T_motor_min), ...
        T_motor_max);

    u_actual = M*motors;

    motor_log(k,:) = motors';

    T_log(k) = u_actual(1);

end

end

%% ============================================================
% CONTROL RECONSTRUCTION: LQR
% ============================================================

function [motor_log,T_log,sat_log] = ...
    reconstruct_lqr_controls( ...
    t, ...
    X, ...
    K, ...
    x_des, ...
    y_des, ...
    z_des, ...
    m_nominal, ...
    g, ...
    L, ...
    k_yaw, ...
    T_motor_min, ...
    T_motor_max)

N = length(t);

motor_log = zeros(N,4);

T_log = zeros(N,1);

sat_log = false(N,1);

M = [ ...
    1,      1,      1,      1;
    0,      L,      0,     -L;
   -L,      0,      L,      0;
    k_yaw, -k_yaw,  k_yaw, -k_yaw];

x_ref = zeros(12,1);

x_ref(1) = x_des;
x_ref(2) = y_des;
x_ref(3) = z_des;

for k = 1:N

    state = X(k,:)';

    e = state-x_ref;

    delta_u = -K*e;

    u_cmd = [ ...
        m_nominal*g;
        0;
        0;
        0] + delta_u;

    requested = M\u_cmd;

    sat_log(k) = any( ...
        requested < T_motor_min | ...
        requested > T_motor_max);

    motors = min( ...
        max(requested,T_motor_min), ...
        T_motor_max);

    u_actual = M*motors;

    motor_log(k,:) = motors';

    T_log(k) = u_actual(1);

end

end

%% ============================================================
% CONTROL RECONSTRUCTION: LQI
% ============================================================

function [motor_log,T_log,sat_log] = ...
    reconstruct_lqi_controls( ...
    t, ...
    X, ...
    Kx, ...
    Ki, ...
    x_des, ...
    y_des, ...
    z_des, ...
    m_nominal, ...
    g, ...
    L, ...
    k_yaw, ...
    T_motor_min, ...
    T_motor_max)

N = length(t);

motor_log = zeros(N,4);

T_log = zeros(N,1);

sat_log = false(N,1);

M = [ ...
    1,      1,      1,      1;
    0,      L,      0,     -L;
   -L,      0,      L,      0;
    k_yaw, -k_yaw,  k_yaw, -k_yaw];

x_ref = zeros(12,1);

x_ref(1) = x_des;
x_ref(2) = y_des;
x_ref(3) = z_des;

for k = 1:N

    state = X(k,1:12)';

    xi = X(k,13:15)';

    e = state-x_ref;

    delta_u = ...
        -Kx*e - ...
        Ki*xi;

    u_cmd = [ ...
        m_nominal*g;
        0;
        0;
        0] + delta_u;

    requested = M\u_cmd;

    sat_log(k) = any( ...
        requested < T_motor_min | ...
        requested > T_motor_max);

    motors = min( ...
        max(requested,T_motor_min), ...
        T_motor_max);

    u_actual = M*motors;

    motor_log(k,:) = motors';

    T_log(k) = u_actual(1);

end

end