%% AeroStabilize - PD vs LQR under Mass Uncertainty
%
% Robustness comparison:
% Cascaded PD + Feedforward
% vs.
% LQR + Feedforward
%
% Controller model:
% Nominal mass = 1.5 kg
%
% Actual nonlinear plant:
% +20 % mass uncertainty = 1.8 kg
%
% Both controllers use the NOMINAL model.
% Neither controller knows the actual increased mass.

clear;
clc;
close all;

addpath('../models');
addpath('../trajectories');

run('../parameters/quadcopter_params.m');

%% ============================================================
%% NOMINAL AND ACTUAL MASS
%% ============================================================

m_nominal = m;

mass_increase = 0.20;

m_actual = ...
    m_nominal * (1 + mass_increase);

fprintf('Nominal mass: %.3f kg\n', m_nominal);
fprintf('Actual mass:  %.3f kg\n', m_actual);
fprintf('Mass error:   +%.1f %%\n', mass_increase*100);

%% ============================================================
%% COMMON SETTINGS
%% ============================================================

tspan = [0 20];

motor_thrust_min = 0.0;
motor_thrust_max = 7.5;

%% ============================================================
%% INITIAL STATE
%% ============================================================

x0 = zeros(12,1);

[x_start, y_start, z_start, ...
 vx_start, vy_start, vz_start] = ...
    helix_trajectory(0);

x0(1) = x_start;
x0(2) = y_start;
x0(3) = z_start;

x0(4) = vx_start;
x0(5) = vy_start;
x0(6) = vz_start;

%% ============================================================
%% PD CONTROLLER GAINS
%% ============================================================

psi_des = 0;

Kp_x = 1.0;
Kd_x = 1.4;

Kp_y = 1.0;
Kd_y = 1.4;

Kp_z = 4.0;
Kd_z = 3.0;

Kp_phi = 0.8;
Kd_phi = 0.25;

Kp_theta = 0.8;
Kd_theta = 0.25;

Kp_psi = 0.5;
Kd_psi = 0.20;

%% ============================================================
%% LQR DESIGN USING NOMINAL MODEL
%% ============================================================

A = zeros(12,12);

A(1,4) = 1;
A(2,5) = 1;
A(3,6) = 1;

A(4,8) = g;
A(5,7) = -g;

A(7,10) = 1;
A(8,11) = 1;
A(9,12) = 1;

B = zeros(12,4);

B(6,1) = ...
    1 / m_nominal;

B(10,2) = ...
    1 / I(1,1);

B(11,3) = ...
    1 / I(2,2);

B(12,4) = ...
    1 / I(3,3);

Co = ctrb(A,B);

fprintf( ...
    'LQR controllability rank: %d / 12\n', ...
    rank(Co));

%% LQR weighting

Q = diag([ ...
    20, ...
    20, ...
    30, ...
    5, ...
    5, ...
    8, ...
    40, ...
    40, ...
    10, ...
    2, ...
    2, ...
    2]);

R = diag([ ...
    1.0, ...
    0.5, ...
    0.5, ...
    0.5]);

K = lqr(A,B,Q,R);

%% ============================================================
%% RUN PD SIMULATION
%% ============================================================

pd_dynamics = @(t,x) ...
    pd_mass_uncertainty_closed_loop( ...
        t, x, ...
        psi_des, ...
        Kp_x, Kd_x, ...
        Kp_y, Kd_y, ...
        Kp_z, Kd_z, ...
        Kp_phi, Kd_phi, ...
        Kp_theta, Kd_theta, ...
        Kp_psi, Kd_psi, ...
        m_nominal, ...
        m_actual, ...
        g, I, L, k_yaw, ...
        motor_thrust_min, ...
        motor_thrust_max);

[t_pd, x_pd] = ...
    ode45( ...
        pd_dynamics, ...
        tspan, ...
        x0);

%% ============================================================
%% RUN LQR SIMULATION
%% ============================================================

lqr_dynamics = @(t,x) ...
    lqr_mass_uncertainty_closed_loop( ...
        t, x, ...
        K, ...
        m_nominal, ...
        m_actual, ...
        g, I, L, k_yaw, ...
        motor_thrust_min, ...
        motor_thrust_max);

[t_lqr, x_lqr] = ...
    ode45( ...
        lqr_dynamics, ...
        tspan, ...
        x0);

%% ============================================================
%% LOG PD DATA
%% ============================================================

N_pd = length(t_pd);

pd_ref = zeros(N_pd,12);

pd_motor = zeros(N_pd,4);
pd_motor_raw = zeros(N_pd,4);

for k = 1:N_pd

    [~, ...
     ref_k, ...
     motor_k, ...
     motor_raw_k] = ...
        pd_mass_uncertainty_closed_loop( ...
            t_pd(k), ...
            x_pd(k,:)', ...
            psi_des, ...
            Kp_x, Kd_x, ...
            Kp_y, Kd_y, ...
            Kp_z, Kd_z, ...
            Kp_phi, Kd_phi, ...
            Kp_theta, Kd_theta, ...
            Kp_psi, Kd_psi, ...
            m_nominal, ...
            m_actual, ...
            g, I, L, k_yaw, ...
            motor_thrust_min, ...
            motor_thrust_max);

    pd_ref(k,:) = ref_k';

    pd_motor(k,:) = motor_k';
    pd_motor_raw(k,:) = motor_raw_k';

end

%% ============================================================
%% LOG LQR DATA
%% ============================================================

N_lqr = length(t_lqr);

lqr_ref = zeros(N_lqr,12);

lqr_motor = zeros(N_lqr,4);
lqr_motor_raw = zeros(N_lqr,4);

for k = 1:N_lqr

    [~, ...
     ref_k, ...
     motor_k, ...
     motor_raw_k] = ...
        lqr_mass_uncertainty_closed_loop( ...
            t_lqr(k), ...
            x_lqr(k,:)', ...
            K, ...
            m_nominal, ...
            m_actual, ...
            g, I, L, k_yaw, ...
            motor_thrust_min, ...
            motor_thrust_max);

    lqr_ref(k,:) = ref_k';

    lqr_motor(k,:) = motor_k';
    lqr_motor_raw(k,:) = motor_raw_k';

end

%% ============================================================
%% PD TRACKING ERRORS
%% ============================================================

pd_error_x = ...
    pd_ref(:,1) - x_pd(:,1);

pd_error_y = ...
    pd_ref(:,2) - x_pd(:,2);

pd_error_z = ...
    pd_ref(:,3) - x_pd(:,3);

pd_position_error = sqrt( ...
    pd_error_x.^2 + ...
    pd_error_y.^2 + ...
    pd_error_z.^2);

pd_RMSE = ...
    sqrt(mean(pd_position_error.^2));

pd_max_error = ...
    max(pd_position_error);

pd_final_error = ...
    pd_position_error(end);

pd_final_altitude_error = ...
    pd_error_z(end);

%% ============================================================
%% LQR TRACKING ERRORS
%% ============================================================

lqr_error_x = ...
    lqr_ref(:,1) - x_lqr(:,1);

lqr_error_y = ...
    lqr_ref(:,2) - x_lqr(:,2);

lqr_error_z = ...
    lqr_ref(:,3) - x_lqr(:,3);

lqr_position_error = sqrt( ...
    lqr_error_x.^2 + ...
    lqr_error_y.^2 + ...
    lqr_error_z.^2);

lqr_RMSE = ...
    sqrt(mean(lqr_position_error.^2));

lqr_max_error = ...
    max(lqr_position_error);

lqr_final_error = ...
    lqr_position_error(end);

lqr_final_altitude_error = ...
    lqr_error_z(end);

%% ============================================================
%% MAXIMUM ATTITUDE
%% ============================================================

pd_max_roll = ...
    max(abs(rad2deg(x_pd(:,7))));

pd_max_pitch = ...
    max(abs(rad2deg(x_pd(:,8))));

pd_max_yaw = ...
    max(abs(rad2deg(x_pd(:,9))));

lqr_max_roll = ...
    max(abs(rad2deg(x_lqr(:,7))));

lqr_max_pitch = ...
    max(abs(rad2deg(x_lqr(:,8))));

lqr_max_yaw = ...
    max(abs(rad2deg(x_lqr(:,9))));

%% ============================================================
%% MOTOR STATISTICS
%% ============================================================

pd_max_motor = ...
    max(pd_motor, [], 'all');

pd_min_motor = ...
    min(pd_motor, [], 'all');

lqr_max_motor = ...
    max(lqr_motor, [], 'all');

lqr_min_motor = ...
    min(lqr_motor, [], 'all');

%% ============================================================
%% SATURATION ANALYSIS
%% ============================================================

pd_sat_log = any( ...
    pd_motor_raw > motor_thrust_max | ...
    pd_motor_raw < motor_thrust_min, ...
    2);

pd_sat_duration = ...
    trapz( ...
        t_pd, ...
        double(pd_sat_log));

pd_sat_percentage = ...
    100 * pd_sat_duration / ...
    (t_pd(end)-t_pd(1));

lqr_sat_log = any( ...
    lqr_motor_raw > motor_thrust_max | ...
    lqr_motor_raw < motor_thrust_min, ...
    2);

lqr_sat_duration = ...
    trapz( ...
        t_lqr, ...
        double(lqr_sat_log));

lqr_sat_percentage = ...
    100 * lqr_sat_duration / ...
    (t_lqr(end)-t_lqr(1));

%% ============================================================
%% PRINT RESULTS
%% ============================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf('PD vs LQR - +20%% MASS UNCERTAINTY\n');
fprintf('============================================================\n');

fprintf('\nPlant Conditions\n');

fprintf( ...
    'Controller nominal mass: %.3f kg\n', ...
    m_nominal);

fprintf( ...
    'Actual plant mass:       %.3f kg\n', ...
    m_actual);

fprintf( ...
    'Model mismatch:          +%.1f %%\n', ...
    mass_increase*100);

fprintf('\n------------------------------------------------------------\n');
fprintf('TRACKING PERFORMANCE\n');

fprintf('\nPD + Feedforward\n');

fprintf( ...
    'RMSE:                  %.4f m\n', ...
    pd_RMSE);

fprintf( ...
    'Maximum Error:         %.4f m\n', ...
    pd_max_error);

fprintf( ...
    'Final Position Error:  %.4f m\n', ...
    pd_final_error);

fprintf( ...
    'Final Altitude Error:  %.4f m\n', ...
    pd_final_altitude_error);

fprintf('\nLQR + Feedforward\n');

fprintf( ...
    'RMSE:                  %.4f m\n', ...
    lqr_RMSE);

fprintf( ...
    'Maximum Error:         %.4f m\n', ...
    lqr_max_error);

fprintf( ...
    'Final Position Error:  %.4f m\n', ...
    lqr_final_error);

fprintf( ...
    'Final Altitude Error:  %.4f m\n', ...
    lqr_final_altitude_error);

%% ============================================================
%% RELATIVE PERFORMANCE
%% ============================================================

rmse_improvement = ...
    100 * ...
    (pd_RMSE - lqr_RMSE) / ...
    pd_RMSE;

fprintf('\n');

fprintf( ...
    'LQR RMSE improvement relative to PD: %.2f %%\n', ...
    rmse_improvement);

fprintf('\n------------------------------------------------------------\n');
fprintf('MAXIMUM ATTITUDE\n');

fprintf('\nPD\n');

fprintf( ...
    'Roll:  %.2f deg\n', ...
    pd_max_roll);

fprintf( ...
    'Pitch: %.2f deg\n', ...
    pd_max_pitch);

fprintf( ...
    'Yaw:   %.2f deg\n', ...
    pd_max_yaw);

fprintf('\nLQR\n');

fprintf( ...
    'Roll:  %.2f deg\n', ...
    lqr_max_roll);

fprintf( ...
    'Pitch: %.2f deg\n', ...
    lqr_max_pitch);

fprintf( ...
    'Yaw:   %.2f deg\n', ...
    lqr_max_yaw);

fprintf('\n------------------------------------------------------------\n');
fprintf('MOTOR THRUST\n');

fprintf('\nPD\n');

fprintf( ...
    'Maximum: %.3f N\n', ...
    pd_max_motor);

fprintf( ...
    'Minimum: %.3f N\n', ...
    pd_min_motor);

fprintf('\nLQR\n');

fprintf( ...
    'Maximum: %.3f N\n', ...
    lqr_max_motor);

fprintf( ...
    'Minimum: %.3f N\n', ...
    lqr_min_motor);

fprintf('\n------------------------------------------------------------\n');
fprintf('ACTUATOR SATURATION\n');

fprintf('\nPD\n');

fprintf( ...
    'Duration: %.3f s\n', ...
    pd_sat_duration);

fprintf( ...
    'Time:     %.2f %%\n', ...
    pd_sat_percentage);

fprintf('\nLQR\n');

fprintf( ...
    'Duration: %.3f s\n', ...
    lqr_sat_duration);

fprintf( ...
    'Time:     %.2f %%\n', ...
    lqr_sat_percentage);

%% ============================================================
%% PLOT 1 - 3D TRAJECTORY
%% ============================================================

figure;

plot3( ...
    pd_ref(:,1), ...
    pd_ref(:,2), ...
    pd_ref(:,3), ...
    '--', ...
    'LineWidth',1.6);

hold on;

plot3( ...
    x_pd(:,1), ...
    x_pd(:,2), ...
    x_pd(:,3), ...
    'LineWidth',1.6);

plot3( ...
    x_lqr(:,1), ...
    x_lqr(:,2), ...
    x_lqr(:,3), ...
    'LineWidth',1.6);

grid on;

xlabel('x [m]');
ylabel('y [m]');
zlabel('z [m]');

title( ...
    'PD vs LQR - Helix Tracking with +20% Mass Uncertainty');

legend( ...
    'Desired', ...
    'PD + Feedforward', ...
    'LQR + Feedforward');

view(3);

%% ============================================================
%% PLOT 2 - 3D POSITION ERROR
%% ============================================================

figure;

plot( ...
    t_pd, ...
    pd_position_error, ...
    'LineWidth',1.5);

hold on;

plot( ...
    t_lqr, ...
    lqr_position_error, ...
    'LineWidth',1.5);

grid on;

xlabel('Time [s]');
ylabel('3D Position Error [m]');

title( ...
    'PD vs LQR - Tracking Error under Mass Uncertainty');

legend( ...
    'PD + Feedforward', ...
    'LQR + Feedforward');

%% ============================================================
%% PLOT 3 - ALTITUDE
%% ============================================================

figure;

plot( ...
    t_pd, ...
    pd_ref(:,3), ...
    '--', ...
    'LineWidth',1.5);

hold on;

plot( ...
    t_pd, ...
    x_pd(:,3), ...
    'LineWidth',1.5);

plot( ...
    t_lqr, ...
    x_lqr(:,3), ...
    'LineWidth',1.5);

grid on;

xlabel('Time [s]');
ylabel('Altitude z [m]');

title( ...
    'PD vs LQR - Altitude with +20% Mass Uncertainty');

legend( ...
    'Desired', ...
    'PD', ...
    'LQR');

%% ============================================================
%% PLOT 4 - ALTITUDE ERROR
%% ============================================================

figure;

plot( ...
    t_pd, ...
    pd_error_z, ...
    'LineWidth',1.5);

hold on;

plot( ...
    t_lqr, ...
    lqr_error_z, ...
    'LineWidth',1.5);

yline( ...
    0, ...
    '--');

grid on;

xlabel('Time [s]');
ylabel('Altitude Error [m]');

title( ...
    'PD vs LQR - Altitude Error under Model Mismatch');

legend( ...
    'PD + Feedforward', ...
    'LQR + Feedforward');

%% ============================================================
%% PLOT 5 - ROLL
%% ============================================================

figure;

plot( ...
    t_pd, ...
    rad2deg(x_pd(:,7)), ...
    'LineWidth',1.5);

hold on;

plot( ...
    t_lqr, ...
    rad2deg(x_lqr(:,7)), ...
    'LineWidth',1.5);

grid on;

xlabel('Time [s]');
ylabel('Roll [deg]');

title( ...
    'PD vs LQR - Roll Response');

legend( ...
    'PD', ...
    'LQR');

%% ============================================================
%% PLOT 6 - PITCH
%% ============================================================

figure;

plot( ...
    t_pd, ...
    rad2deg(x_pd(:,8)), ...
    'LineWidth',1.5);

hold on;

plot( ...
    t_lqr, ...
    rad2deg(x_lqr(:,8)), ...
    'LineWidth',1.5);

grid on;

xlabel('Time [s]');
ylabel('Pitch [deg]');

title( ...
    'PD vs LQR - Pitch Response');

legend( ...
    'PD', ...
    'LQR');

%% ============================================================
%% PLOT 7 - PEAK MOTOR THRUST
%% ============================================================

pd_peak_motor = ...
    max(pd_motor,[],2);

lqr_peak_motor = ...
    max(lqr_motor,[],2);

figure;

plot( ...
    t_pd, ...
    pd_peak_motor, ...
    'LineWidth',1.5);

hold on;

plot( ...
    t_lqr, ...
    lqr_peak_motor, ...
    'LineWidth',1.5);

yline( ...
    motor_thrust_max, ...
    '--', ...
    'Motor Limit');

grid on;

xlabel('Time [s]');
ylabel('Peak Motor Thrust [N]');

title( ...
    'PD vs LQR - Motor Effort under Mass Uncertainty');

legend( ...
    'PD', ...
    'LQR', ...
    'Motor Limit');

%% ============================================================
%% PLOT 8 - SATURATION
%% ============================================================

figure;

stairs( ...
    t_pd, ...
    pd_sat_log, ...
    'LineWidth',1.4);

hold on;

stairs( ...
    t_lqr, ...
    lqr_sat_log, ...
    'LineWidth',1.4);

grid on;

ylim([-0.1 1.1]);

xlabel('Time [s]');
ylabel('Motor Saturation');

yticks([0 1]);

yticklabels({ ...
    'No', ...
    'Yes'});

title( ...
    'PD vs LQR - Motor Saturation');

legend( ...
    'PD', ...
    'LQR');

%% ============================================================
%% PD CLOSED LOOP
%% ============================================================

function [ ...
    xdot, ...
    x_ref, ...
    motor_thrusts_sat, ...
    motor_thrusts_raw] = ...
    pd_mass_uncertainty_closed_loop( ...
    t, x, ...
    psi_des, ...
    Kp_x, Kd_x, ...
    Kp_y, Kd_y, ...
    Kp_z, Kd_z, ...
    Kp_phi, Kd_phi, ...
    Kp_theta, Kd_theta, ...
    Kp_psi, Kd_psi, ...
    m_nominal, ...
    m_actual, ...
    g, I, L, k_yaw, ...
    motor_thrust_min, ...
    motor_thrust_max)

%% Desired trajectory

[x_des, y_des, z_des, ...
 vx_des, vy_des, vz_des, ...
 ax_ff, ay_ff, az_ff] = ...
    helix_trajectory(t);

%% Reference state

x_ref = zeros(12,1);

x_ref(1) = x_des;
x_ref(2) = y_des;
x_ref(3) = z_des;

x_ref(4) = vx_des;
x_ref(5) = vy_des;
x_ref(6) = vz_des;

%% States

x_pos = x(1);
y_pos = x(2);
z_pos = x(3);

vx = x(4);
vy = x(5);
vz = x(6);

phi = x(7);
theta = x(8);
psi = x(9);

p = x(10);
q = x(11);
r = x(12);

%% Position error

e_x = ...
    x_des - x_pos;

e_y = ...
    y_des - y_pos;

e_z = ...
    z_des - z_pos;

e_vx = ...
    vx_des - vx;

e_vy = ...
    vy_des - vy;

e_vz = ...
    vz_des - vz;

%% ============================================================
%% OUTER LOOP + FEEDFORWARD
%% ============================================================

ax_des = ...
    ax_ff + ...
    Kp_x*e_x + ...
    Kd_x*e_vx;

ay_des = ...
    ay_ff + ...
    Kp_y*e_y + ...
    Kd_y*e_vy;

theta_des = ...
    ax_des / g;

phi_des = ...
    -ay_des / g;

max_angle = ...
    deg2rad(20);

theta_des = max( ...
    min(theta_des,max_angle), ...
    -max_angle);

phi_des = max( ...
    min(phi_des,max_angle), ...
    -max_angle);

%% ============================================================
%% ALTITUDE CONTROL
%%
%% IMPORTANT:
%% Controller uses NOMINAL mass, not actual mass.
%% ============================================================

T = ...
    m_nominal*g + ...
    m_nominal*az_ff + ...
    Kp_z*e_z + ...
    Kd_z*e_vz;

%% ============================================================
%% ATTITUDE PD
%% ============================================================

tau_phi = ...
    Kp_phi*(phi_des-phi) - ...
    Kd_phi*p;

tau_theta = ...
    Kp_theta*(theta_des-theta) - ...
    Kd_theta*q;

tau_psi = ...
    Kp_psi*(psi_des-psi) - ...
    Kd_psi*r;

%% ============================================================
%% MOTOR ALLOCATION
%% ============================================================

motor_thrusts_raw = ...
    motor_mixer( ...
        T, ...
        tau_phi, ...
        tau_theta, ...
        tau_psi, ...
        L, ...
        k_yaw);

motor_thrusts_sat = ...
    max( ...
        min( ...
            motor_thrusts_raw, ...
            motor_thrust_max), ...
        motor_thrust_min);

u_actual = ...
    motor_unmixer( ...
        motor_thrusts_sat, ...
        L, ...
        k_yaw);

%% ============================================================
%% ACTUAL PLANT
%%
%% Uses m_actual = 1.8 kg
%% ============================================================

xdot = ...
    quad_dynamics( ...
        x, ...
        u_actual, ...
        m_actual, ...
        g, ...
        I);

end

%% ============================================================
%% LQR CLOSED LOOP
%% ============================================================

function [ ...
    xdot, ...
    x_ref, ...
    motor_thrusts_sat, ...
    motor_thrusts_raw] = ...
    lqr_mass_uncertainty_closed_loop( ...
    t, x, ...
    K, ...
    m_nominal, ...
    m_actual, ...
    g, I, L, k_yaw, ...
    motor_thrust_min, ...
    motor_thrust_max)

%% Desired trajectory

[x_des, y_des, z_des, ...
 vx_des, vy_des,vz_des, ...
 ax_ff, ay_ff, az_ff] = ...
    helix_trajectory(t);

%% ============================================================
%% FEEDFORWARD ATTITUDE
%% ============================================================

theta_ff = ...
    ax_ff / g;

phi_ff = ...
    -ay_ff / g;

max_ff_angle = ...
    deg2rad(15);

theta_ff = max( ...
    min(theta_ff,max_ff_angle), ...
    -max_ff_angle);

phi_ff = max( ...
    min(phi_ff,max_ff_angle), ...
    -max_ff_angle);

%% ============================================================
%% REFERENCE STATE
%% ============================================================

x_ref = zeros(12,1);

x_ref(1) = x_des;
x_ref(2) = y_des;
x_ref(3) = z_des;

x_ref(4) = vx_des;
x_ref(5) = vy_des;
x_ref(6) = vz_des;

x_ref(7) = phi_ff;
x_ref(8) = theta_ff;

%% ============================================================
%% LQR FEEDBACK
%% ============================================================

e = ...
    x - x_ref;

delta_u = ...
    -K * e;

delta_T = ...
    delta_u(1);

tau_phi = ...
    delta_u(2);

tau_theta = ...
    delta_u(3);

tau_psi = ...
    delta_u(4);

%% ============================================================
%% NOMINAL FEEDFORWARD THRUST
%%
%% LQR also does NOT know actual mass.
%% ============================================================

T_ff = ...
    m_nominal * ...
    (g + az_ff);

T = ...
    T_ff + delta_T;

%% ============================================================
%% MOTOR ALLOCATION
%% ============================================================

motor_thrusts_raw = ...
    motor_mixer( ...
        T, ...
        tau_phi, ...
        tau_theta, ...
        tau_psi, ...
        L, ...
        k_yaw);

motor_thrusts_sat = ...
    max( ...
        min( ...
            motor_thrusts_raw, ...
            motor_thrust_max), ...
        motor_thrust_min);

u_actual = ...
    motor_unmixer( ...
        motor_thrusts_sat, ...
        L, ...
        k_yaw);

%% ============================================================
%% ACTUAL NONLINEAR PLANT
%% ============================================================

xdot = ...
    quad_dynamics( ...
        x, ...
        u_actual, ...
        m_actual, ...
        g, ...
        I);

end