%% AeroStabilize
% Monte-Carlo Robustness Analysis
%
% Controllers:
%   1) Cascaded PD + Feedforward
%   2) LQR + Feedforward
%   3) LQI + Feedforward
%
% Random uncertainty:
%   - Mass: +/-20%
%   - Inertia: +/-15%
%   - Wind magnitude: 0...5 N
%   - Random horizontal wind direction
%
% Output:
%   - Statistical robustness metrics
%   - RMSE distribution boxplot
%   - Summary bar chart
%
% NOTE:
% The exact same randomized plant/disturbance conditions are
% applied to all three controllers in every Monte-Carlo run.

clear;
clc;
close all;

rng(42);   % Reproducible Monte-Carlo experiment

%% ============================================================
% MONTE-CARLO SETTINGS
% ============================================================

N_runs = 100;

t_start = 0;
t_end   = 20;

%% Desired fixed position

x_des = 1.0;
y_des = 1.0;
z_des = 2.0;

%% Constant disturbance starts here

wind_start = 5.0;

%% Success criterion

success_error_threshold = 0.50;   % final 3D error [m]

%% ============================================================
% NOMINAL PARAMETERS
% ============================================================

g = 9.81;

m_nominal = 1.5;

L = 0.225;

Ix_nominal = 0.020;
Iy_nominal = 0.020;
Iz_nominal = 0.040;

k_yaw = 0.02;

%% Motor limits

T_motor_min = 0.0;
T_motor_max = 7.5;

%% ============================================================
% CLASSICAL PD GAINS
% ============================================================

Kp_x = 1.0;
Kd_x = 1.4;

Kp_y = 1.0;
Kd_y = 1.4;

Kp_z = 4.0;
Kd_z = 3.0;

Kp_phi = 0.8;
Kd_phi = 0.25;

Kp_theta = 0.8;
Kd_theta = 0.25;

Kp_psi = 0.5;
Kd_psi = 0.20;

%% ============================================================
% NOMINAL LINEAR MODEL FOR LQR/LQI
% ============================================================

A = zeros(12);

A(1,4) = 1;
A(2,5) = 1;
A(3,6) = 1;

A(4,8) = g;
A(5,7) = -g;

A(7,10) = 1;
A(8,11) = 1;
A(9,12) = 1;

B = zeros(12,4);

B(6,1) = 1/m_nominal;

B(10,2) = 1/Ix_nominal;
B(11,3) = 1/Iy_nominal;
B(12,4) = 1/Iz_nominal;

%% ============================================================
% LQR DESIGN
% ============================================================

Q = diag([ ...
    20,20,30, ...
    5,5,8, ...
    40,40,10, ...
    2,2,2]);

R = diag([ ...
    1.0, ...
    0.5, ...
    0.5, ...
    0.5]);

K_lqr = lqr(A,B,Q,R);

%% ============================================================
% LQI DESIGN
% ============================================================

C_pos = zeros(3,12);

C_pos(1,1) = 1;
C_pos(2,2) = 1;
C_pos(3,3) = 1;

A_aug = zeros(15,15);

A_aug(1:12,1:12) = A;
A_aug(13:15,1:12) = -C_pos;

B_aug = zeros(15,4);

B_aug(1:12,:) = B;

Q_aug = diag([ ...
    20,20,30, ...
    5,5,8, ...
    40,40,10, ...
    2,2,2, ...
    20,20,25]);

K_aug = lqr( ...
    A_aug, ...
    B_aug, ...
    Q_aug, ...
    R);

Kx_lqi = K_aug(:,1:12);
Ki_lqi = K_aug(:,13:15);

%% ============================================================
% INITIAL CONDITION
% ============================================================

% Start exactly at reference to isolate robustness performance

x0 = zeros(12,1);

x0(1) = x_des;
x0(2) = y_des;
x0(3) = z_des;

x0_lqi = zeros(15,1);

x0_lqi(1:12) = x0;

%% ============================================================
% RESULT ARRAYS
% ============================================================

RMSE_PD  = zeros(N_runs,1);
RMSE_LQR = zeros(N_runs,1);
RMSE_LQI = zeros(N_runs,1);

FINAL_PD  = zeros(N_runs,1);
FINAL_LQR = zeros(N_runs,1);
FINAL_LQI = zeros(N_runs,1);

PEAK_PD  = zeros(N_runs,1);
PEAK_LQR = zeros(N_runs,1);
PEAK_LQI = zeros(N_runs,1);

SAT_PD  = zeros(N_runs,1);
SAT_LQR = zeros(N_runs,1);
SAT_LQI = zeros(N_runs,1);

mass_actual_log = zeros(N_runs,1);
wind_mag_log = zeros(N_runs,1);
wind_angle_log = zeros(N_runs,1);

%% ============================================================
% COMMON ODE SETTINGS
% ============================================================

options = odeset( ...
    'RelTol',1e-5, ...
    'AbsTol',1e-7);

t_eval = linspace( ...
    t_start, ...
    t_end, ...
    1001)';

fprintf('============================================\n');
fprintf('AeroStabilize Monte-Carlo Robustness Test\n');
fprintf('============================================\n');
fprintf('Runs: %d\n\n',N_runs);

%% ============================================================
% MONTE-CARLO LOOP
% ============================================================

for run = 1:N_runs

    %% --------------------------------------------------------
    % RANDOM PLANT PARAMETERS
    % ---------------------------------------------------------

    mass_scale = ...
        1 + (-0.20 + 0.40*rand);

    m_actual = ...
        m_nominal*mass_scale;

    Ix_actual = ...
        Ix_nominal*(1 + (-0.15 + 0.30*rand));

    Iy_actual = ...
        Iy_nominal*(1 + (-0.15 + 0.30*rand));

    Iz_actual = ...
        Iz_nominal*(1 + (-0.15 + 0.30*rand));

    I_actual = diag([ ...
        Ix_actual, ...
        Iy_actual, ...
        Iz_actual]);

    %% --------------------------------------------------------
    % RANDOM WIND
    % ---------------------------------------------------------

    wind_mag = ...
        5.0*rand;

    wind_angle = ...
        2*pi*rand;

    F_wind = [ ...
        wind_mag*cos(wind_angle);
        wind_mag*sin(wind_angle);
        0];

    mass_actual_log(run) = m_actual;
    wind_mag_log(run) = wind_mag;
    wind_angle_log(run) = wind_angle;

    %% ========================================================
    % PD
    % ========================================================

    ode_pd = @(t,x) dynamics_pd_mc( ...
        t, ...
        x, ...
        x_des, ...
        y_des, ...
        z_des, ...
        Kp_x, ...
        Kd_x, ...
        Kp_y, ...
        Kd_y, ...
        Kp_z, ...
        Kd_z, ...
        Kp_phi, ...
        Kd_phi, ...
        Kp_theta, ...
        Kd_theta, ...
        Kp_psi, ...
        Kd_psi, ...
        m_nominal, ...
        m_actual, ...
        F_wind, ...
        wind_start, ...
        g, ...
        I_actual, ...
        L, ...
        k_yaw, ...
        T_motor_min, ...
        T_motor_max);

    [t_pd,X_pd] = ode45( ...
        ode_pd, ...
        [t_start t_end], ...
        x0, ...
        options);

    Xpd = interp1( ...
        t_pd, ...
        X_pd, ...
        t_eval, ...
        'linear');

    %% ========================================================
    % LQR
    % ========================================================

    ode_lqr = @(t,x) dynamics_lqr_mc( ...
        t, ...
        x, ...
        K_lqr, ...
        x_des, ...
        y_des, ...
        z_des, ...
        m_nominal, ...
        m_actual, ...
        F_wind, ...
        wind_start, ...
        g, ...
        I_actual, ...
        L, ...
        k_yaw, ...
        T_motor_min, ...
        T_motor_max);

    [t_lqr,X_lqr] = ode45( ...
        ode_lqr, ...
        [t_start t_end], ...
        x0, ...
        options);

    Xlqr = interp1( ...
        t_lqr, ...
        X_lqr, ...
        t_eval, ...
        'linear');

    %% ========================================================
    % LQI
    % ========================================================

    ode_lqi = @(t,x) dynamics_lqi_mc( ...
        t, ...
        x, ...
        Kx_lqi, ...
        Ki_lqi, ...
        x_des, ...
        y_des, ...
        z_des, ...
        m_nominal, ...
        m_actual, ...
        F_wind, ...
        wind_start, ...
        g, ...
        I_actual, ...
        L, ...
        k_yaw, ...
        T_motor_min, ...
        T_motor_max);

    [t_lqi,X_lqi] = ode45( ...
        ode_lqi, ...
        [t_start t_end], ...
        x0_lqi, ...
        options);

    Xlqi = interp1( ...
        t_lqi, ...
        X_lqi, ...
        t_eval, ...
        'linear');

    %% ========================================================
    % ERRORS
    % ========================================================

    ref = [ ...
        x_des, ...
        y_des, ...
        z_des];

    err_pd_xyz = ...
        ref - Xpd(:,1:3);

    err_lqr_xyz = ...
        ref - Xlqr(:,1:3);

    err_lqi_xyz = ...
        ref - Xlqi(:,1:3);

    err_pd = sqrt( ...
        sum(err_pd_xyz.^2,2));

    err_lqr = sqrt( ...
        sum(err_lqr_xyz.^2,2));

    err_lqi = sqrt( ...
        sum(err_lqi_xyz.^2,2));

    %% Evaluate only after disturbance begins

    idx_eval = ...
        t_eval >= wind_start;

    RMSE_PD(run) = sqrt( ...
        mean(err_pd(idx_eval).^2));

    RMSE_LQR(run) = sqrt( ...
        mean(err_lqr(idx_eval).^2));

    RMSE_LQI(run) = sqrt( ...
        mean(err_lqi(idx_eval).^2));

    FINAL_PD(run) = err_pd(end);
    FINAL_LQR(run) = err_lqr(end);
    FINAL_LQI(run) = err_lqi(end);

    PEAK_PD(run) = max( ...
        err_pd(idx_eval));

    PEAK_LQR(run) = max( ...
        err_lqr(idx_eval));

    PEAK_LQI(run) = max( ...
        err_lqi(idx_eval));

    %% ========================================================
    % SATURATION PERCENTAGE
    % ========================================================

    SAT_PD(run) = saturation_percentage_pd( ...
        t_eval, ...
        Xpd, ...
        x_des, ...
        y_des, ...
        z_des, ...
        Kp_x, ...
        Kd_x, ...
        Kp_y, ...
        Kd_y, ...
        Kp_z, ...
        Kd_z, ...
        Kp_phi, ...
        Kd_phi, ...
        Kp_theta, ...
        Kd_theta, ...
        Kp_psi, ...
        Kd_psi, ...
        m_nominal, ...
        g, ...
        L, ...
        k_yaw, ...
        T_motor_min, ...
        T_motor_max);

    SAT_LQR(run) = saturation_percentage_lqr( ...
        t_eval, ...
        Xlqr, ...
        K_lqr, ...
        x_des, ...
        y_des, ...
        z_des, ...
        m_nominal, ...
        g, ...
        L, ...
        k_yaw, ...
        T_motor_min, ...
        T_motor_max);

    SAT_LQI(run) = saturation_percentage_lqi( ...
        t_eval, ...
        Xlqi, ...
        Kx_lqi, ...
        Ki_lqi, ...
        x_des, ...
        y_des, ...
        z_des, ...
        m_nominal, ...
        g, ...
        L, ...
        k_yaw, ...
        T_motor_min, ...
        T_motor_max);

    %% Progress

    if mod(run,10) == 0

        fprintf( ...
            'Completed %d / %d runs\n', ...
            run, ...
            N_runs);

    end

end

%% ============================================================
% STATISTICS
% ============================================================

mean_rmse = [ ...
    mean(RMSE_PD), ...
    mean(RMSE_LQR), ...
    mean(RMSE_LQI)];

median_rmse = [ ...
    median(RMSE_PD), ...
    median(RMSE_LQR), ...
    median(RMSE_LQI)];

p95_rmse = [ ...
    prctile(RMSE_PD,95), ...
    prctile(RMSE_LQR,95), ...
    prctile(RMSE_LQI,95)];

worst_rmse = [ ...
    max(RMSE_PD), ...
    max(RMSE_LQR), ...
    max(RMSE_LQI)];

mean_peak = [ ...
    mean(PEAK_PD), ...
    mean(PEAK_LQR), ...
    mean(PEAK_LQI)];

mean_final = [ ...
    mean(FINAL_PD), ...
    mean(FINAL_LQR), ...
    mean(FINAL_LQI)];

success_PD = ...
    100*mean(FINAL_PD < success_error_threshold);

success_LQR = ...
    100*mean(FINAL_LQR < success_error_threshold);

success_LQI = ...
    100*mean(FINAL_LQI < success_error_threshold);

success_rate = [ ...
    success_PD, ...
    success_LQR, ...
    success_LQI];

mean_saturation = [ ...
    mean(SAT_PD), ...
    mean(SAT_LQR), ...
    mean(SAT_LQI)];

%% ============================================================
% PRINT SUMMARY
% ============================================================

fprintf('\n');
fprintf('============================================\n');
fprintf('MONTE-CARLO RESULTS (%d RUNS)\n',N_runs);
fprintf('============================================\n');

fprintf('\nMean RMSE:\n');
fprintf('PD  + FF: %.4f m\n',mean_rmse(1));
fprintf('LQR + FF: %.4f m\n',mean_rmse(2));
fprintf('LQI + FF: %.4f m\n',mean_rmse(3));

fprintf('\nMedian RMSE:\n');
fprintf('PD  + FF: %.4f m\n',median_rmse(1));
fprintf('LQR + FF: %.4f m\n',median_rmse(2));
fprintf('LQI + FF: %.4f m\n',median_rmse(3));

fprintf('\n95th percentile RMSE:\n');
fprintf('PD  + FF: %.4f m\n',p95_rmse(1));
fprintf('LQR + FF: %.4f m\n',p95_rmse(2));
fprintf('LQI + FF: %.4f m\n',p95_rmse(3));

fprintf('\nWorst-case RMSE:\n');
fprintf('PD  + FF: %.4f m\n',worst_rmse(1));
fprintf('LQR + FF: %.4f m\n',worst_rmse(2));
fprintf('LQI + FF: %.4f m\n',worst_rmse(3));

fprintf('\nMean peak position error:\n');
fprintf('PD  + FF: %.4f m\n',mean_peak(1));
fprintf('LQR + FF: %.4f m\n',mean_peak(2));
fprintf('LQI + FF: %.4f m\n',mean_peak(3));

fprintf('\nMean final position error:\n');
fprintf('PD  + FF: %.4f m\n',mean_final(1));
fprintf('LQR + FF: %.4f m\n',mean_final(2));
fprintf('LQI + FF: %.4f m\n',mean_final(3));

fprintf('\nSuccess rate (final error < %.2f m):\n', ...
    success_error_threshold);

fprintf('PD  + FF: %.1f %%\n',success_rate(1));
fprintf('LQR + FF: %.1f %%\n',success_rate(2));
fprintf('LQI + FF: %.1f %%\n',success_rate(3));

fprintf('\nMean actuator saturation:\n');
fprintf('PD  + FF: %.3f %%\n',mean_saturation(1));
fprintf('LQR + FF: %.3f %%\n',mean_saturation(2));
fprintf('LQI + FF: %.3f %%\n',mean_saturation(3));

fprintf('\nRandomized plant range:\n');

fprintf('Mass: %.3f ... %.3f kg\n', ...
    min(mass_actual_log), ...
    max(mass_actual_log));

fprintf('Wind: %.3f ... %.3f N\n', ...
    min(wind_mag_log), ...
    max(wind_mag_log));

fprintf('============================================\n');

%% ============================================================
% DISPLAY SUMMARY TABLE
% ============================================================

Controller = [ ...
    "PD + FF";
    "LQR + FF";
    "LQI + FF"];

Mean_RMSE_m = mean_rmse';

Median_RMSE_m = median_rmse';

P95_RMSE_m = p95_rmse';

Worst_RMSE_m = worst_rmse';

Mean_Final_Error_m = mean_final';

Success_Rate_pct = success_rate';

Mean_Saturation_pct = mean_saturation';

ResultsTable = table( ...
    Controller, ...
    Mean_RMSE_m, ...
    Median_RMSE_m, ...
    P95_RMSE_m, ...
    Worst_RMSE_m, ...
    Mean_Final_Error_m, ...
    Success_Rate_pct, ...
    Mean_Saturation_pct);

disp(ResultsTable);

%% ============================================================
% PLOT 1: RMSE DISTRIBUTION
% ============================================================

figure('Position',[150 120 850 520]);

boxchart( ...
    [ ...
    ones(N_runs,1);
    2*ones(N_runs,1);
    3*ones(N_runs,1)], ...
    [ ...
    RMSE_PD;
    RMSE_LQR;
    RMSE_LQI]);

grid on;

xticks([1 2 3]);

xticklabels({ ...
    'PD + FF', ...
    'LQR + FF', ...
    'LQI + FF'});

ylabel('Tracking RMSE [m]');

title(sprintf( ...
    'Monte-Carlo Tracking Robustness (%d Runs)', ...
    N_runs));

%% ============================================================
% PLOT 2: SUMMARY METRICS
% ============================================================

figure('Position',[180 140 850 520]);

metrics_plot = [ ...
    mean_rmse;
    p95_rmse;
    worst_rmse];

bar(metrics_plot);

grid on;

xticks([1 2 3]);

xticklabels({ ...
    'Mean RMSE', ...
    '95th Percentile', ...
    'Worst Case'});

ylabel('Position Error [m]');

title('Monte-Carlo Robustness Summary');

legend( ...
    'PD + FF', ...
    'LQR + FF', ...
    'LQI + FF', ...
    'Location','best');

%% ============================================================
% LOCAL FUNCTION: PD DYNAMICS
% ============================================================

function dx = dynamics_pd_mc( ...
    t,state, ...
    x_des,y_des,z_des, ...
    Kp_x,Kd_x, ...
    Kp_y,Kd_y, ...
    Kp_z,Kd_z, ...
    Kp_phi,Kd_phi, ...
    Kp_theta,Kd_theta, ...
    Kp_psi,Kd_psi, ...
    m_nominal,m_actual, ...
    F_wind,wind_start, ...
    g,I,L,k_yaw,Tmin,Tmax)

x = state(1);
y = state(2);
z = state(3);

vx = state(4);
vy = state(5);
vz = state(6);

phi = state(7);
theta = state(8);
psi = state(9);

p = state(10);
q = state(11);
r = state(12);

ex = x_des-x;
ey = y_des-y;
ez = z_des-z;

ax_des = ...
    Kp_x*ex - ...
    Kd_x*vx;

ay_des = ...
    Kp_y*ey - ...
    Kd_y*vy;

theta_des = ax_des/g;
phi_des = -ay_des/g;

T_cmd = ...
    m_nominal*g + ...
    Kp_z*ez - ...
    Kd_z*vz;

tau_phi = ...
    Kp_phi*(phi_des-phi) - ...
    Kd_phi*p;

tau_theta = ...
    Kp_theta*(theta_des-theta) - ...
    Kd_theta*q;

tau_psi = ...
    Kp_psi*(0-psi) - ...
    Kd_psi*r;

u_cmd = [ ...
    T_cmd;
    tau_phi;
    tau_theta;
    tau_psi];

if t >= wind_start
    F_ext = F_wind;
else
    F_ext = [0;0;0];
end

dx = plant_mc( ...
    state, ...
    u_cmd, ...
    m_actual, ...
    I, ...
    F_ext, ...
    g,L,k_yaw,Tmin,Tmax);

end

%% ============================================================
% LQR DYNAMICS
% ============================================================

function dx = dynamics_lqr_mc( ...
    t,state,K, ...
    x_des,y_des,z_des, ...
    m_nominal,m_actual, ...
    F_wind,wind_start, ...
    g,I,L,k_yaw,Tmin,Tmax)

x_ref = zeros(12,1);

x_ref(1) = x_des;
x_ref(2) = y_des;
x_ref(3) = z_des;

e = state-x_ref;

delta_u = -K*e;

u_cmd = [ ...
    m_nominal*g;
    0;
    0;
    0] + delta_u;

if t >= wind_start
    F_ext = F_wind;
else
    F_ext = [0;0;0];
end

dx = plant_mc( ...
    state, ...
    u_cmd, ...
    m_actual, ...
    I, ...
    F_ext, ...
    g,L,k_yaw,Tmin,Tmax);

end

%% ============================================================
% LQI DYNAMICS
% ============================================================

function dx_aug = dynamics_lqi_mc( ...
    t,x_aug,Kx,Ki, ...
    x_des,y_des,z_des, ...
    m_nominal,m_actual, ...
    F_wind,wind_start, ...
    g,I,L,k_yaw,Tmin,Tmax)

state = x_aug(1:12);

xi = x_aug(13:15);

x_ref = zeros(12,1);

x_ref(1) = x_des;
x_ref(2) = y_des;
x_ref(3) = z_des;

e = state-x_ref;

delta_u = ...
    -Kx*e - ...
    Ki*xi;

u_cmd = [ ...
    m_nominal*g;
    0;
    0;
    0] + delta_u;

if t >= wind_start
    F_ext = F_wind;
else
    F_ext = [0;0;0];
end

dx = plant_mc( ...
    state, ...
    u_cmd, ...
    m_actual, ...
    I, ...
    F_ext, ...
    g,L,k_yaw,Tmin,Tmax);

xi_dot = [ ...
    x_des-state(1);
    y_des-state(2);
    z_des-state(3)];

dx_aug = [ ...
    dx;
    xi_dot];

end

%% ============================================================
% NONLINEAR PLANT
% ============================================================

function dx = plant_mc( ...
    state,u_cmd,m,I,F_ext, ...
    g,L,k_yaw,Tmin,Tmax)

vx = state(4);
vy = state(5);
vz = state(6);

phi = state(7);
theta = state(8);
psi = state(9);

p = state(10);
q = state(11);
r = state(12);

M = [ ...
    1,1,1,1;
    0,L,0,-L;
    -L,0,L,0;
    k_yaw,-k_yaw,k_yaw,-k_yaw];

motors = M\u_cmd;

motors = min( ...
    max(motors,Tmin), ...
    Tmax);

u_actual = M*motors;

T = u_actual(1);
tau = u_actual(2:4);

Rx = [ ...
    1,0,0;
    0,cos(phi),-sin(phi);
    0,sin(phi),cos(phi)];

Ry = [ ...
    cos(theta),0,sin(theta);
    0,1,0;
    -sin(theta),0,cos(theta)];

Rz = [ ...
    cos(psi),-sin(psi),0;
    sin(psi),cos(psi),0;
    0,0,1];

Rbw = Rz*Ry*Rx;

F_thrust = Rbw*[0;0;T];

F_gravity = [0;0;-m*g];

acc = ( ...
    F_thrust + ...
    F_gravity + ...
    F_ext)/m;

omega = [p;q;r];

omega_dot = I \ ( ...
    tau - ...
    cross(omega,I*omega));

E = [ ...
    1, ...
    sin(phi)*tan(theta), ...
    cos(phi)*tan(theta);
    0, ...
    cos(phi), ...
    -sin(phi);
    0, ...
    sin(phi)/cos(theta), ...
    cos(phi)/cos(theta)];

euler_dot = E*omega;

dx = zeros(12,1);

dx(1:3) = [vx;vy;vz];

dx(4:6) = acc;

dx(7:9) = euler_dot;

dx(10:12) = omega_dot;

end

%% ============================================================
% SATURATION: PD
% ============================================================

function pct = saturation_percentage_pd( ...
    t,X, ...
    x_des,y_des,z_des, ...
    Kp_x,Kd_x, ...
    Kp_y,Kd_y, ...
    Kp_z,Kd_z, ...
    Kp_phi,Kd_phi, ...
    Kp_theta,Kd_theta, ...
    Kp_psi,Kd_psi, ...
    m_nominal,g,L,k_yaw,Tmin,Tmax)

N = length(t);

sat = false(N,1);

M = [ ...
    1,1,1,1;
    0,L,0,-L;
    -L,0,L,0;
    k_yaw,-k_yaw,k_yaw,-k_yaw];

for k = 1:N

    s = X(k,:)';

    ex = x_des-s(1);
    ey = y_des-s(2);
    ez = z_des-s(3);

    ax_des = ...
        Kp_x*ex - ...
        Kd_x*s(4);

    ay_des = ...
        Kp_y*ey - ...
        Kd_y*s(5);

    theta_des = ax_des/g;
    phi_des = -ay_des/g;

    T_cmd = ...
        m_nominal*g + ...
        Kp_z*ez - ...
        Kd_z*s(6);

    tau_phi = ...
        Kp_phi*(phi_des-s(7)) - ...
        Kd_phi*s(10);

    tau_theta = ...
        Kp_theta*(theta_des-s(8)) - ...
        Kd_theta*s(11);

    tau_psi = ...
        Kp_psi*(0-s(9)) - ...
        Kd_psi*s(12);

    requested = M \ [ ...
        T_cmd;
        tau_phi;
        tau_theta;
        tau_psi];

    sat(k) = any( ...
        requested<Tmin | ...
        requested>Tmax);

end

duration = trapz( ...
    t, ...
    double(sat));

pct = ...
    100*duration/(t(end)-t(1));

end

%% ============================================================
% SATURATION: LQR
% ============================================================

function pct = saturation_percentage_lqr( ...
    t,X,K, ...
    x_des,y_des,z_des, ...
    m_nominal,g,L,k_yaw,Tmin,Tmax)

N = length(t);

sat = false(N,1);

M = [ ...
    1,1,1,1;
    0,L,0,-L;
    -L,0,L,0;
    k_yaw,-k_yaw,k_yaw,-k_yaw];

x_ref = zeros(12,1);

x_ref(1) = x_des;
x_ref(2) = y_des;
x_ref(3) = z_des;

for k = 1:N

    state = X(k,:)';

    u_cmd = [ ...
        m_nominal*g;
        0;
        0;
        0] - ...
        K*(state-x_ref);

    requested = M\u_cmd;

    sat(k) = any( ...
        requested<Tmin | ...
        requested>Tmax);

end

duration = trapz( ...
    t, ...
    double(sat));

pct = ...
    100*duration/(t(end)-t(1));

end

%% ============================================================
% SATURATION: LQI
% ============================================================

function pct = saturation_percentage_lqi( ...
    t,X,Kx,Ki, ...
    x_des,y_des,z_des, ...
    m_nominal,g,L,k_yaw,Tmin,Tmax)

N = length(t);

sat = false(N,1);

M = [ ...
    1,1,1,1;
    0,L,0,-L;
    -L,0,L,0;
    k_yaw,-k_yaw,k_yaw,-k_yaw];

x_ref = zeros(12,1);

x_ref(1) = x_des;
x_ref(2) = y_des;
x_ref(3) = z_des;

for k = 1:N

    state = X(k,1:12)';

    xi = X(k,13:15)';

    u_cmd = [ ...
        m_nominal*g;
        0;
        0;
        0] - ...
        Kx*(state-x_ref) - ...
        Ki*xi;

    requested = M\u_cmd;

    sat(k) = any( ...
        requested<Tmin | ...
        requested>Tmax);

end

duration = trapz( ...
    t, ...
    double(sat));

pct = ...
    100*duration/(t(end)-t(1));

end