%% AeroStabilize
% LQR + FF vs 3-Axis LQI + FF
% Final Robustness Mission
%
% Mission:
%   0 - 8 s   : Nominal 3D Figure-8 tracking
%   8 - 10 s  : +5 N X wind gust
%   14 - 16 s : -4 N Y wind gust
%   t = 20 s  : Payload increase 1.5 kg -> 1.8 kg
%   26 - 34 s : Constant diagonal wind
%   34 - 40 s : Wind removed, recovery
%
% Both controllers use:
%   - Same nonlinear 6-DOF plant
%   - Same trajectory
%   - Same initial condition
%   - Same actuator limits
%   - Same disturbances
%
% Goal:
% Demonstrate transient robustness and steady-state
% disturbance rejection.

clear;
clc;
close all;

%% ============================================================
% PARAMETERS
% ============================================================

g = 9.81;

m_nominal = 1.5;
m_payload = 1.8;

L = 0.225;

Ix = 0.020;
Iy = 0.020;
Iz = 0.040;

I = diag([Ix Iy Iz]);

k_yaw = 0.02;

%% Motor limits

T_motor_min = 0.0;
T_motor_max = 7.5;

%% ============================================================
% FIGURE-8 TRAJECTORY PARAMETERS
% ============================================================

A_traj = 2.0;     % X amplitude [m]
B_traj = 1.5;     % Y amplitude [m]

omega_traj = 0.30;

z0_traj = 2.0;
C_traj  = 0.50;

%% ============================================================
% MISSION EVENTS
% ============================================================

gust_x_start = 8.0;
gust_x_end   = 10.0;

gust_y_start = 14.0;
gust_y_end   = 16.0;

payload_time = 20.0;

crosswind_start = 26.0;
crosswind_end   = 34.0;

%% Disturbance forces

F_gust_x = [ ...
    5.0;
    0.0;
    0.0];

F_gust_y = [ ...
    0.0;
   -4.0;
    0.0];

F_crosswind = [ ...
    2.0;
   -2.0;
    0.0];

%% ============================================================
% SIMULATION SETTINGS
% ============================================================

t_start = 0;
t_end   = 40;

%% ============================================================
% LINEARIZED HOVER MODEL
% ============================================================

A = zeros(12);

% Position kinematics
A(1,4) = 1;
A(2,5) = 1;
A(3,6) = 1;

% Translational coupling
A(4,8) = g;
A(5,7) = -g;

% Euler kinematics
A(7,10) = 1;
A(8,11) = 1;
A(9,12) = 1;

B = zeros(12,4);

B(6,1) = 1/m_nominal;

B(10,2) = 1/Ix;
B(11,3) = 1/Iy;
B(12,4) = 1/Iz;

%% ============================================================
% LQR DESIGN
% ============================================================

Q = diag([ ...
    20, ...
    20, ...
    30, ...
    5, ...
    5, ...
    8, ...
    40, ...
    40, ...
    10, ...
    2, ...
    2, ...
    2]);

R = diag([ ...
    1.0, ...
    0.5, ...
    0.5, ...
    0.5]);

K_lqr = lqr(A,B,Q,R);

%% ============================================================
% 3-AXIS LQI DESIGN
% ============================================================

C_pos = zeros(3,12);

C_pos(1,1) = 1;
C_pos(2,2) = 1;
C_pos(3,3) = 1;

A_aug = zeros(15,15);

A_aug(1:12,1:12) = A;

% xi_dot = desired - actual
A_aug(13:15,1:12) = -C_pos;

B_aug = zeros(15,4);
B_aug(1:12,:) = B;

Q_aug = diag([ ...
    20, ...
    20, ...
    30, ...
    5, ...
    5, ...
    8, ...
    40, ...
    40, ...
    10, ...
    2, ...
    2, ...
    2, ...
    20, ...
    20, ...
    25]);

K_aug = lqr( ...
    A_aug, ...
    B_aug, ...
    Q_aug, ...
    R);

Kx_lqi = K_aug(:,1:12);

Ki_lqi = K_aug(:,13:15);

%% ============================================================
% CONTROLLABILITY
% ============================================================

rank_lqr = rank(ctrb(A,B));

rank_lqi = rank(ctrb(A_aug,B_aug));

fprintf('============================================\n');
fprintf('AeroStabilize Final Robustness Mission\n');
fprintf('============================================\n');

fprintf('LQR controllability: %d / 12\n',rank_lqr);
fprintf('LQI controllability: %d / 15\n',rank_lqi);

%% ============================================================
% INITIAL CONDITION
% ============================================================

[ ...
    xd0, ...
    yd0, ...
    zd0, ...
    vxd0, ...
    vyd0, ...
    vzd0, ...
    ax0, ...
    ay0, ...
    ~] = figure8_reference( ...
    0, ...
    A_traj, ...
    B_traj, ...
    omega_traj, ...
    z0_traj, ...
    C_traj);

theta_ff_0 = ax0/g;
phi_ff_0   = -ay0/g;

x0 = zeros(12,1);

x0(1) = xd0;
x0(2) = yd0;
x0(3) = zd0;

x0(4) = vxd0;
x0(5) = vyd0;
x0(6) = vzd0;

x0(7) = phi_ff_0;
x0(8) = theta_ff_0;

%% LQI initial state

x0_lqi = zeros(15,1);

x0_lqi(1:12) = x0;

%% ============================================================
% ODE OPTIONS
% ============================================================

options = odeset( ...
    'RelTol',1e-7, ...
    'AbsTol',1e-9);

%% ============================================================
% RUN LQR
% ============================================================

ode_lqr = @(t,x) mission_lqr_dynamics( ...
    t, ...
    x, ...
    K_lqr, ...
    m_nominal, ...
    m_payload, ...
    payload_time, ...
    g, ...
    I, ...
    L, ...
    k_yaw, ...
    T_motor_min, ...
    T_motor_max, ...
    A_traj, ...
    B_traj, ...
    omega_traj, ...
    z0_traj, ...
    C_traj, ...
    gust_x_start, ...
    gust_x_end, ...
    gust_y_start, ...
    gust_y_end, ...
    crosswind_start, ...
    crosswind_end, ...
    F_gust_x, ...
    F_gust_y, ...
    F_crosswind);

[t_lqr,X_lqr] = ode45( ...
    ode_lqr, ...
    [t_start t_end], ...
    x0, ...
    options);

%% ============================================================
% RUN LQI
% ============================================================

ode_lqi = @(t,x) mission_lqi_dynamics( ...
    t, ...
    x, ...
    Kx_lqi, ...
    Ki_lqi, ...
    m_nominal, ...
    m_payload, ...
    payload_time, ...
    g, ...
    I, ...
    L, ...
    k_yaw, ...
    T_motor_min, ...
    T_motor_max, ...
    A_traj, ...
    B_traj, ...
    omega_traj, ...
    z0_traj, ...
    C_traj, ...
    gust_x_start, ...
    gust_x_end, ...
    gust_y_start, ...
    gust_y_end, ...
    crosswind_start, ...
    crosswind_end, ...
    F_gust_x, ...
    F_gust_y, ...
    F_crosswind);

[t_lqi,X_lqi] = ode45( ...
    ode_lqi, ...
    [t_start t_end], ...
    x0_lqi, ...
    options);

%% ============================================================
% COMMON TIME VECTOR
% ============================================================

t = linspace( ...
    t_start, ...
    t_end, ...
    4001)';

Xlqr = interp1( ...
    t_lqr, ...
    X_lqr, ...
    t, ...
    'linear');

Xlqi = interp1( ...
    t_lqi, ...
    X_lqi, ...
    t, ...
    'linear');

%% ============================================================
% REFERENCE TRAJECTORY
% ============================================================

N = length(t);

ref = zeros(N,9);

for k = 1:N

    [ ...
        ref(k,1), ...
        ref(k,2), ...
        ref(k,3), ...
        ref(k,4), ...
        ref(k,5), ...
        ref(k,6), ...
        ref(k,7), ...
        ref(k,8), ...
        ref(k,9)] = figure8_reference( ...
        t(k), ...
        A_traj, ...
        B_traj, ...
        omega_traj, ...
        z0_traj, ...
        C_traj);

end

%% ============================================================
% POSITION ERRORS
% ============================================================

error_xyz_lqr = ...
    ref(:,1:3) - Xlqr(:,1:3);

error_xyz_lqi = ...
    ref(:,1:3) - Xlqi(:,1:3);

error_lqr = sqrt( ...
    sum(error_xyz_lqr.^2,2));

error_lqi = sqrt( ...
    sum(error_xyz_lqi.^2,2));

%% ============================================================
% CONTROL HISTORY
% ============================================================

[ ...
    motor_lqr, ...
    thrust_lqr, ...
    saturation_lqr] = reconstruct_mission_lqr( ...
    t, ...
    Xlqr, ...
    K_lqr, ...
    m_nominal, ...
    g, ...
    L, ...
    k_yaw, ...
    T_motor_min, ...
    T_motor_max, ...
    A_traj, ...
    B_traj, ...
    omega_traj, ...
    z0_traj, ...
    C_traj);

[ ...
    motor_lqi, ...
    thrust_lqi, ...
    saturation_lqi] = reconstruct_mission_lqi( ...
    t, ...
    Xlqi, ...
    Kx_lqi, ...
    Ki_lqi, ...
    m_nominal, ...
    g, ...
    L, ...
    k_yaw, ...
    T_motor_min, ...
    T_motor_max, ...
    A_traj, ...
    B_traj, ...
    omega_traj, ...
    z0_traj, ...
    C_traj);

%% ============================================================
% PERFORMANCE WINDOWS
% ============================================================

idx_nominal = t < gust_x_start;

idx_gust_x = ...
    t >= gust_x_start & ...
    t <= 12;

idx_gust_y = ...
    t >= gust_y_start & ...
    t <= 18;

idx_payload = ...
    t >= payload_time & ...
    t < crosswind_start;

idx_crosswind = ...
    t >= crosswind_start & ...
    t < crosswind_end;

idx_recovery = ...
    t >= crosswind_end;

%% ============================================================
% RMSE VALUES
% ============================================================

rmse_lqr_all = sqrt(mean(error_lqr.^2));
rmse_lqi_all = sqrt(mean(error_lqi.^2));

rmse_lqr_nominal = sqrt( ...
    mean(error_lqr(idx_nominal).^2));

rmse_lqi_nominal = sqrt( ...
    mean(error_lqi(idx_nominal).^2));

rmse_lqr_payload = sqrt( ...
    mean(error_lqr(idx_payload).^2));

rmse_lqi_payload = sqrt( ...
    mean(error_lqi(idx_payload).^2));

rmse_lqr_crosswind = sqrt( ...
    mean(error_lqr(idx_crosswind).^2));

rmse_lqi_crosswind = sqrt( ...
    mean(error_lqi(idx_crosswind).^2));

rmse_lqr_recovery = sqrt( ...
    mean(error_lqr(idx_recovery).^2));

rmse_lqi_recovery = sqrt( ...
    mean(error_lqi(idx_recovery).^2));

%% ============================================================
% PEAK ERRORS
% ============================================================

peak_lqr_gust_x = max(error_lqr(idx_gust_x));
peak_lqi_gust_x = max(error_lqi(idx_gust_x));

peak_lqr_gust_y = max(error_lqr(idx_gust_y));
peak_lqi_gust_y = max(error_lqi(idx_gust_y));

peak_lqr_crosswind = max(error_lqr(idx_crosswind));
peak_lqi_crosswind = max(error_lqi(idx_crosswind));

%% ============================================================
% FINAL ERROR
% ============================================================

final_lqr = error_lqr(end);
final_lqi = error_lqi(end);

final_xyz_lqr = error_xyz_lqr(end,:);
final_xyz_lqi = error_xyz_lqi(end,:);

%% ============================================================
% MOTOR SATURATION
% ============================================================

sat_time_lqr = trapz( ...
    t, ...
    double(saturation_lqr));

sat_time_lqi = trapz( ...
    t, ...
    double(saturation_lqi));

sat_pct_lqr = ...
    100*sat_time_lqr/t_end;

sat_pct_lqi = ...
    100*sat_time_lqi/t_end;

%% ============================================================
% RESULTS
% ============================================================

fprintf('\n');
fprintf('============================================\n');
fprintf('OVERALL PERFORMANCE\n');
fprintf('============================================\n');

fprintf('LQR RMSE: %.6f m\n',rmse_lqr_all);
fprintf('LQI RMSE: %.6f m\n',rmse_lqi_all);

fprintf('\n');

fprintf('Nominal RMSE:\n');
fprintf('LQR: %.6f m\n',rmse_lqr_nominal);
fprintf('LQI: %.6f m\n',rmse_lqi_nominal);

fprintf('\n');
fprintf('============================================\n');
fprintf('GUST PERFORMANCE\n');
fprintf('============================================\n');

fprintf('+5 N X gust peak error:\n');

fprintf('LQR: %.6f m\n',peak_lqr_gust_x);
fprintf('LQI: %.6f m\n',peak_lqi_gust_x);

fprintf('\n');

fprintf('-4 N Y gust peak error:\n');

fprintf('LQR: %.6f m\n',peak_lqr_gust_y);
fprintf('LQI: %.6f m\n',peak_lqi_gust_y);

fprintf('\n');
fprintf('============================================\n');
fprintf('PAYLOAD PERFORMANCE\n');
fprintf('============================================\n');

fprintf('Payload-window RMSE:\n');

fprintf('LQR: %.6f m\n',rmse_lqr_payload);
fprintf('LQI: %.6f m\n',rmse_lqi_payload);

fprintf('\n');
fprintf('============================================\n');
fprintf('CONSTANT CROSSWIND PERFORMANCE\n');
fprintf('============================================\n');

fprintf('Crosswind RMSE:\n');

fprintf('LQR: %.6f m\n',rmse_lqr_crosswind);
fprintf('LQI: %.6f m\n',rmse_lqi_crosswind);

fprintf('\n');

fprintf('Crosswind peak error:\n');

fprintf('LQR: %.6f m\n',peak_lqr_crosswind);
fprintf('LQI: %.6f m\n',peak_lqi_crosswind);

fprintf('\n');
fprintf('============================================\n');
fprintf('FINAL RECOVERY\n');
fprintf('============================================\n');

fprintf('Recovery RMSE:\n');

fprintf('LQR: %.6f m\n',rmse_lqr_recovery);
fprintf('LQI: %.6f m\n',rmse_lqi_recovery);

fprintf('\n');

fprintf('Final 3D error:\n');

fprintf('LQR: %.6f m\n',final_lqr);
fprintf('LQI: %.6f m\n',final_lqi);

fprintf('\n');

fprintf('LQR final XYZ errors:\n');

fprintf('Ex = %.6f m\n',final_xyz_lqr(1));
fprintf('Ey = %.6f m\n',final_xyz_lqr(2));
fprintf('Ez = %.6f m\n',final_xyz_lqr(3));

fprintf('\n');

fprintf('LQI final XYZ errors:\n');

fprintf('Ex = %.6f m\n',final_xyz_lqi(1));
fprintf('Ey = %.6f m\n',final_xyz_lqi(2));
fprintf('Ez = %.6f m\n',final_xyz_lqi(3));

fprintf('\n');
fprintf('============================================\n');
fprintf('ACTUATOR UTILIZATION\n');
fprintf('============================================\n');

fprintf('LQR saturation: %.3f s (%.2f %%)\n', ...
    sat_time_lqr, ...
    sat_pct_lqr);

fprintf('LQI saturation: %.3f s (%.2f %%)\n', ...
    sat_time_lqi, ...
    sat_pct_lqi);

fprintf('\n');

fprintf('LQR max motor thrust: %.3f N\n', ...
    max(motor_lqr,[],'all'));

fprintf('LQI max motor thrust: %.3f N\n', ...
    max(motor_lqi,[],'all'));

fprintf('\n');

fprintf('LQR final thrust: %.3f N\n', ...
    thrust_lqr(end));

fprintf('LQI final thrust: %.3f N\n', ...
    thrust_lqi(end));

fprintf('============================================\n');

%% ============================================================
% PLOT 1: 3D TRAJECTORY
% ============================================================

figure('Position',[120 100 900 600]);

plot3( ...
    ref(:,1), ...
    ref(:,2), ...
    ref(:,3), ...
    '--', ...
    'LineWidth',1.4);

hold on;

plot3( ...
    Xlqr(:,1), ...
    Xlqr(:,2), ...
    Xlqr(:,3), ...
    'LineWidth',1.5);

plot3( ...
    Xlqi(:,1), ...
    Xlqi(:,2), ...
    Xlqi(:,3), ...
    'LineWidth',1.7);

grid on;
axis equal;

xlabel('X [m]');
ylabel('Y [m]');
zlabel('Z [m]');

title('Final Robustness Mission');

legend( ...
    'Desired Figure-8', ...
    'LQR + FF', ...
    'LQI + FF', ...
    'Location','best');

view(40,25);

%% ============================================================
% PLOT 2: TOTAL TRACKING ERROR
% ============================================================

figure('Position',[150 120 900 520]);

plot( ...
    t, ...
    error_lqr, ...
    'LineWidth',1.5);

hold on;

plot( ...
    t, ...
    error_lqi, ...
    'LineWidth',1.7);

xline(gust_x_start,'--','+5 N X');
xline(gust_x_end,'--','Gust OFF');

xline(gust_y_start,'--','-4 N Y');
xline(gust_y_end,'--','Gust OFF');

xline(payload_time,'--','Payload +20%');

xline(crosswind_start,'--','Crosswind ON');
xline(crosswind_end,'--','Crosswind OFF');

grid on;

xlabel('Time [s]');
ylabel('3D Position Error [m]');

title('LQR vs LQI Tracking Error');

legend( ...
    'LQR + FF', ...
    'LQI + FF', ...
    'Location','best');

%% ============================================================
% PLOT 3: X ERROR
% ============================================================

figure('Position',[180 140 900 520]);

plot( ...
    t, ...
    error_xyz_lqr(:,1), ...
    'LineWidth',1.5);

hold on;

plot( ...
    t, ...
    error_xyz_lqi(:,1), ...
    'LineWidth',1.7);

yline(0,'--');

xline(gust_x_start,'--','+5 N X');
xline(gust_x_end,'--','OFF');

xline(payload_time,'--','Payload');

xline(crosswind_start,'--','Crosswind');
xline(crosswind_end,'--','OFF');

grid on;

xlabel('Time [s]');
ylabel('X Error [m]');

title('X-Axis Disturbance Rejection');

legend( ...
    'LQR + FF', ...
    'LQI + FF', ...
    'Location','best');

%% ============================================================
% PLOT 4: Y ERROR
% ============================================================

figure('Position',[210 160 900 520]);

plot( ...
    t, ...
    error_xyz_lqr(:,2), ...
    'LineWidth',1.5);

hold on;

plot( ...
    t, ...
    error_xyz_lqi(:,2), ...
    'LineWidth',1.7);

yline(0,'--');

xline(gust_y_start,'--','-4 N Y');
xline(gust_y_end,'--','OFF');

xline(crosswind_start,'--','Crosswind');
xline(crosswind_end,'--','OFF');

grid on;

xlabel('Time [s]');
ylabel('Y Error [m]');

title('Y-Axis Disturbance Rejection');

legend( ...
    'LQR + FF', ...
    'LQI + FF', ...
    'Location','best');

%% ============================================================
% PLOT 5: ALTITUDE ERROR
% ============================================================

figure('Position',[240 180 900 520]);

plot( ...
    t, ...
    error_xyz_lqr(:,3), ...
    'LineWidth',1.5);

hold on;

plot( ...
    t, ...
    error_xyz_lqi(:,3), ...
    'LineWidth',1.7);

yline(0,'--');

xline(payload_time,'--','Payload +20%');

xline(crosswind_start,'--','Crosswind');
xline(crosswind_end,'--','OFF');

grid on;

xlabel('Time [s]');
ylabel('Altitude Error [m]');

title('Payload Disturbance Rejection');

legend( ...
    'LQR + FF', ...
    'LQI + FF', ...
    'Location','best');

%% ============================================================
% PLOT 6: LQI INTEGRAL STATES
% ============================================================

figure('Position',[270 200 900 520]);

plot( ...
    t, ...
    Xlqi(:,13), ...
    'LineWidth',1.4);

hold on;

plot( ...
    t, ...
    Xlqi(:,14), ...
    'LineWidth',1.4);

plot( ...
    t, ...
    Xlqi(:,15), ...
    'LineWidth',1.4);

xline(gust_x_start,'--','X Gust');
xline(gust_y_start,'--','Y Gust');

xline(payload_time,'--','Payload');

xline(crosswind_start,'--','Crosswind');
xline(crosswind_end,'--','OFF');

grid on;

xlabel('Time [s]');
ylabel('Integral State');

title('LQI Integral Compensation');

legend( ...
    '\xi_x', ...
    '\xi_y', ...
    '\xi_z', ...
    'Location','best');

%% ============================================================
% PLOT 7: TOTAL THRUST
% ============================================================

figure('Position',[300 220 900 520]);

plot( ...
    t, ...
    thrust_lqr, ...
    'LineWidth',1.4);

hold on;

plot( ...
    t, ...
    thrust_lqi, ...
    'LineWidth',1.6);

yline( ...
    m_nominal*g, ...
    '--', ...
    '1.5 kg Hover');

yline( ...
    m_payload*g, ...
    '--', ...
    '1.8 kg Hover');

xline(payload_time,'--','Payload');

grid on;

xlabel('Time [s]');
ylabel('Total Thrust [N]');

title('Control Effort');

legend( ...
    'LQR + FF', ...
    'LQI + FF', ...
    'Location','best');

%% ============================================================
% LOCAL FUNCTION: FIGURE-8 TRAJECTORY
% ============================================================

function [ ...
    x, ...
    y, ...
    z, ...
    vx, ...
    vy, ...
    vz, ...
    ax, ...
    ay, ...
    az] = figure8_reference( ...
    t, ...
    A, ...
    B, ...
    omega, ...
    z0, ...
    C)

%% Position

x = A*sin(omega*t);

y = B*sin(2*omega*t);

z = z0 + C*sin(0.5*omega*t);

%% Velocity

vx = A*omega*cos(omega*t);

vy = 2*B*omega*cos(2*omega*t);

vz = 0.5*C*omega*cos(0.5*omega*t);

%% Acceleration

ax = -A*omega^2*sin(omega*t);

ay = -4*B*omega^2*sin(2*omega*t);

az = -0.25*C*omega^2*sin(0.5*omega*t);

end

%% ============================================================
% LOCAL FUNCTION: EXTERNAL FORCE
% ============================================================

function F = mission_disturbance( ...
    t, ...
    gust_x_start, ...
    gust_x_end, ...
    gust_y_start, ...
    gust_y_end, ...
    crosswind_start, ...
    crosswind_end, ...
    F_gust_x, ...
    F_gust_y, ...
    F_crosswind)

F = [0;0;0];

if t >= gust_x_start && t <= gust_x_end

    F = F + F_gust_x;

end

if t >= gust_y_start && t <= gust_y_end

    F = F + F_gust_y;

end

if t >= crosswind_start && t <= crosswind_end

    F = F + F_crosswind;

end

end

%% ============================================================
% LOCAL FUNCTION: ACTUAL MASS
% ============================================================

function m_actual = mission_mass( ...
    t, ...
    m_nominal, ...
    m_payload, ...
    payload_time)

if t < payload_time

    m_actual = m_nominal;

else

    m_actual = m_payload;

end

end

%% ============================================================
% LOCAL FUNCTION: LQR DYNAMICS
% ============================================================

function dx = mission_lqr_dynamics( ...
    t, ...
    state, ...
    K, ...
    m_nominal, ...
    m_payload, ...
    payload_time, ...
    g, ...
    I, ...
    L, ...
    k_yaw, ...
    Tmin, ...
    Tmax, ...
    A_traj, ...
    B_traj, ...
    omega_traj, ...
    z0_traj, ...
    C_traj, ...
    gust_x_start, ...
    gust_x_end, ...
    gust_y_start, ...
    gust_y_end, ...
    crosswind_start, ...
    crosswind_end, ...
    F_gust_x, ...
    F_gust_y, ...
    F_crosswind)

%% Reference

[xd,yd,zd,vxd,vyd,vzd,ax,ay,az] = ...
    figure8_reference( ...
    t, ...
    A_traj, ...
    B_traj, ...
    omega_traj, ...
    z0_traj, ...
    C_traj);

phi_ff = -ay/g;
theta_ff = ax/g;

x_ref = zeros(12,1);

x_ref(1:6) = [ ...
    xd;
    yd;
    zd;
    vxd;
    vyd;
    vzd];

x_ref(7) = phi_ff;
x_ref(8) = theta_ff;

%% LQR

e = state-x_ref;

delta_u = -K*e;

u_cmd = [ ...
    m_nominal*(g+az);
    0;
    0;
    0] + delta_u;

%% Mission conditions

m_actual = mission_mass( ...
    t, ...
    m_nominal, ...
    m_payload, ...
    payload_time);

F_external = mission_disturbance( ...
    t, ...
    gust_x_start, ...
    gust_x_end, ...
    gust_y_start, ...
    gust_y_end, ...
    crosswind_start, ...
    crosswind_end, ...
    F_gust_x, ...
    F_gust_y, ...
    F_crosswind);

%% Plant

dx = nonlinear_quad_plant( ...
    state, ...
    u_cmd, ...
    m_actual, ...
    F_external, ...
    g, ...
    I, ...
    L, ...
    k_yaw, ...
    Tmin, ...
    Tmax);

end

%% ============================================================
% LOCAL FUNCTION: LQI DYNAMICS
% ============================================================

function dx_aug = mission_lqi_dynamics( ...
    t, ...
    x_aug, ...
    Kx, ...
    Ki, ...
    m_nominal, ...
    m_payload, ...
    payload_time, ...
    g, ...
    I, ...
    L, ...
    k_yaw, ...
    Tmin, ...
    Tmax, ...
    A_traj, ...
    B_traj, ...
    omega_traj, ...
    z0_traj, ...
    C_traj, ...
    gust_x_start, ...
    gust_x_end, ...
    gust_y_start, ...
    gust_y_end, ...
    crosswind_start, ...
    crosswind_end, ...
    F_gust_x, ...
    F_gust_y, ...
    F_crosswind)

state = x_aug(1:12);

xi = x_aug(13:15);

%% Reference

[xd,yd,zd,vxd,vyd,vzd,ax,ay,az] = ...
    figure8_reference( ...
    t, ...
    A_traj, ...
    B_traj, ...
    omega_traj, ...
    z0_traj, ...
    C_traj);

phi_ff = -ay/g;
theta_ff = ax/g;

x_ref = zeros(12,1);

x_ref(1:6) = [ ...
    xd;
    yd;
    zd;
    vxd;
    vyd;
    vzd];

x_ref(7) = phi_ff;
x_ref(8) = theta_ff;

%% LQI

e = state-x_ref;

delta_u = ...
    -Kx*e - ...
    Ki*xi;

u_cmd = [ ...
    m_nominal*(g+az);
    0;
    0;
    0] + delta_u;

%% Mission conditions

m_actual = mission_mass( ...
    t, ...
    m_nominal, ...
    m_payload, ...
    payload_time);

F_external = mission_disturbance( ...
    t, ...
    gust_x_start, ...
    gust_x_end, ...
    gust_y_start, ...
    gust_y_end, ...
    crosswind_start, ...
    crosswind_end, ...
    F_gust_x, ...
    F_gust_y, ...
    F_crosswind);

%% Plant

dx = nonlinear_quad_plant( ...
    state, ...
    u_cmd, ...
    m_actual, ...
    F_external, ...
    g, ...
    I, ...
    L, ...
    k_yaw, ...
    Tmin, ...
    Tmax);

%% Integral states

xi_dot = [ ...
    xd-state(1);
    yd-state(2);
    zd-state(3)];

dx_aug = [ ...
    dx;
    xi_dot];

end

%% ============================================================
% LOCAL FUNCTION: NONLINEAR QUADCOPTER
% ============================================================

function dx = nonlinear_quad_plant( ...
    state, ...
    u_cmd, ...
    m, ...
    F_external, ...
    g, ...
    I, ...
    L, ...
    k_yaw, ...
    Tmin, ...
    Tmax)

vx = state(4);
vy = state(5);
vz = state(6);

phi = state(7);
theta = state(8);
psi = state(9);

p = state(10);
q = state(11);
r = state(12);

%% Mixer

M = [ ...
    1,      1,      1,      1;
    0,      L,      0,     -L;
   -L,      0,      L,      0;
    k_yaw, -k_yaw,  k_yaw, -k_yaw];

motors = M\u_cmd;

motors = min( ...
    max(motors,Tmin), ...
    Tmax);

u_actual = M*motors;

T = u_actual(1);

tau = u_actual(2:4);

%% Rotation

Rx = [ ...
    1,0,0;
    0,cos(phi),-sin(phi);
    0,sin(phi),cos(phi)];

Ry = [ ...
    cos(theta),0,sin(theta);
    0,1,0;
    -sin(theta),0,cos(theta)];

Rz = [ ...
    cos(psi),-sin(psi),0;
    sin(psi),cos(psi),0;
    0,0,1];

Rbw = Rz*Ry*Rx;

%% Translation

F_thrust = ...
    Rbw*[0;0;T];

F_gravity = ...
    [0;0;-m*g];

acc = ...
    (F_thrust + ...
     F_gravity + ...
     F_external)/m;

%% Rotation

omega_body = [p;q;r];

omega_dot = I \ ( ...
    tau - ...
    cross(omega_body,I*omega_body));

%% Euler kinematics

E = [ ...
    1, ...
    sin(phi)*tan(theta), ...
    cos(phi)*tan(theta);
    0, ...
    cos(phi), ...
    -sin(phi);
    0, ...
    sin(phi)/cos(theta), ...
    cos(phi)/cos(theta)];

euler_dot = E*omega_body;

%% State derivative

dx = zeros(12,1);

dx(1:3) = [vx;vy;vz];

dx(4:6) = acc;

dx(7:9) = euler_dot;

dx(10:12) = omega_dot;

end

%% ============================================================
% CONTROL RECONSTRUCTION: LQR
% ============================================================

function [motor_log,T_log,sat_log] = ...
    reconstruct_mission_lqr( ...
    t, ...
    X, ...
    K, ...
    m_nominal, ...
    g, ...
    L, ...
    k_yaw, ...
    Tmin, ...
    Tmax, ...
    A_traj, ...
    B_traj, ...
    omega_traj, ...
    z0_traj, ...
    C_traj)

N = length(t);

motor_log = zeros(N,4);
T_log = zeros(N,1);
sat_log = false(N,1);

M = [ ...
    1,      1,      1,      1;
    0,      L,      0,     -L;
   -L,      0,      L,      0;
    k_yaw, -k_yaw,  k_yaw, -k_yaw];

for k = 1:N

    [xd,yd,zd,vxd,vyd,vzd,ax,ay,az] = ...
        figure8_reference( ...
        t(k), ...
        A_traj, ...
        B_traj, ...
        omega_traj, ...
        z0_traj, ...
        C_traj);

    phi_ff = -ay/g;
    theta_ff = ax/g;

    x_ref = zeros(12,1);

    x_ref(1:6) = [ ...
        xd;
        yd;
        zd;
        vxd;
        vyd;
        vzd];

    x_ref(7) = phi_ff;
    x_ref(8) = theta_ff;

    state = X(k,:)';

    delta_u = ...
        -K*(state-x_ref);

    u_cmd = [ ...
        m_nominal*(g+az);
        0;
        0;
        0] + delta_u;

    requested = M\u_cmd;

    sat_log(k) = any( ...
        requested<Tmin | ...
        requested>Tmax);

    motors = min( ...
        max(requested,Tmin), ...
        Tmax);

    u_actual = M*motors;

    motor_log(k,:) = motors';

    T_log(k) = u_actual(1);

end

end

%% ============================================================
% CONTROL RECONSTRUCTION: LQI
% ============================================================

function [motor_log,T_log,sat_log] = ...
    reconstruct_mission_lqi( ...
    t, ...
    X, ...
    Kx, ...
    Ki, ...
    m_nominal, ...
    g, ...
    L, ...
    k_yaw, ...
    Tmin, ...
    Tmax, ...
    A_traj, ...
    B_traj, ...
    omega_traj, ...
    z0_traj, ...
    C_traj)

N = length(t);

motor_log = zeros(N,4);
T_log = zeros(N,1);
sat_log = false(N,1);

M = [ ...
    1,      1,      1,      1;
    0,      L,      0,     -L;
   -L,      0,      L,      0;
    k_yaw, -k_yaw,  k_yaw, -k_yaw];

for k = 1:N

    [xd,yd,zd,vxd,vyd,vzd,ax,ay,az] = ...
        figure8_reference( ...
        t(k), ...
        A_traj, ...
        B_traj, ...
        omega_traj, ...
        z0_traj, ...
        C_traj);

    phi_ff = -ay/g;
    theta_ff = ax/g;

    x_ref = zeros(12,1);

    x_ref(1:6) = [ ...
        xd;
        yd;
        zd;
        vxd;
        vyd;
        vzd];

    x_ref(7) = phi_ff;
    x_ref(8) = theta_ff;

    state = X(k,1:12)';

    xi = X(k,13:15)';

    delta_u = ...
        -Kx*(state-x_ref) - ...
        Ki*xi;

    u_cmd = [ ...
        m_nominal*(g+az);
        0;
        0;
        0] + delta_u;

    requested = M\u_cmd;

    sat_log(k) = any( ...
        requested<Tmin | ...
        requested>Tmax);

    motors = min( ...
        max(requested,Tmin), ...
        Tmax);

    u_actual = M*motors;

    motor_log(k,:) = motors';

    T_log(k) = u_actual(1);

end

end