%% AeroStabilize - Motor Mixer Test

clear;
clc;

addpath('../models');

% Load parameters
run('../parameters/quadcopter_params.m');

%% Test 1: Hover

T = m * g;

tau_phi = 0;
tau_theta = 0;
tau_psi = 0;

motor_thrusts = motor_mixer( ...
    T, ...
    tau_phi, ...
    tau_theta, ...
    tau_psi, ...
    L, ...
    k_yaw);

disp('Hover motor thrusts [N]:');
disp(motor_thrusts);

%% Test 2: Positive roll torque

tau_phi = 0.05;

motor_thrusts_roll = motor_mixer( ...
    T, ...
    tau_phi, ...
    0, ...
    0, ...
    L, ...
    k_yaw);

disp('Positive roll torque motor thrusts [N]:');
disp(motor_thrusts_roll);

%% Test 3: Positive pitch torque

tau_theta = 0.05;

motor_thrusts_pitch = motor_mixer( ...
    T, ...
    0, ...
    tau_theta, ...
    0, ...
    L, ...
    k_yaw);

disp('Positive pitch torque motor thrusts [N]:');
disp(motor_thrusts_pitch);